import type { LanguageCode } from "@/lib/i18n/translations"
import type { Category, Unit, Presentation } from "@/types/ingredient"

/**
 * Mismo patrón no invasivo que lib/classification-labels.ts: las categorías, unidades y
 * presentaciones de ingrediente (types/ingredient.ts) se guardan en Español fijo — son
 * el VALOR canónico que usa merma, PDFs, filtros, etc. — y NUNCA se traducen. Este
 * archivo solo controla la ETIQUETA que ve el usuario, por idioma. Español no necesita
 * tabla propia: el valor guardado YA es la etiqueta en Español.
 */

const CATEGORY_LABELS: Partial<Record<LanguageCode, Record<Category, string>>> = {
  en: {
    ACEITES: "Oils",
    ALCOHOL: "Alcohol",
    AVES: "Poultry",
    BEBIDAS: "Beverages",
    CAFÉ: "Coffee",
    CERDO: "Pork",
    CHOCOLATE: "Chocolate",
    GAME: "Game",
    DESECHABLES: "Disposables",
    DULCE: "Sweets",
    EMBUTIDO: "Cured Meats",
    ESENCIA: "Extracts",
    ESPECIAS: "Spices",
    FIDEOS: "Noodles / Pasta",
    FLORES: "Edible Flowers",
    FRUTA: "Fruit",
    GRANOS: "Grains",
    GRASAS: "Fats",
    GUARNICIÓN: "Garnish / Sides",
    HARINA: "Flour",
    HIERBAS: "Herbs",
    HUEVO: "Eggs",
    "LÁCTEOS Y DERIVADOS": "Dairy and Derivatives",
    LEVADURA: "Yeast",
    MARISCOS: "Shellfish",
    MASA: "Dough",
    MOLECULAR: "Molecular",
    NUECES: "Nuts",
    OTROS: "Other",
    PESCADO: "Fish",
    REPOSTERÍA: "Pastry",
    RES: "Beef",
    SAL: "Salt",
    "SECOS Y ABARROTES": "Dry Goods",
    SIROPES: "Syrups",
    "Sub Receta / produccion (Mise en place)": "Sub-recipe",
    VEGETAL: "Vegetables",
  },
  da: {
    ACEITES: "Olier",
    ALCOHOL: "Alkohol",
    AVES: "Fjerkræ",
    BEBIDAS: "Drikkevarer",
    CAFÉ: "Kaffe",
    CERDO: "Svinekød",
    CHOCOLATE: "Chokolade",
    GAME: "Vildt",
    DESECHABLES: "Engangsartikler",
    DULCE: "Slik",
    EMBUTIDO: "Pålæg / pølser",
    ESENCIA: "Essenser",
    ESPECIAS: "Krydderier",
    FIDEOS: "Nudler",
    FLORES: "Spiselige blomster",
    FRUTA: "Frugt",
    GRANOS: "Korn",
    GRASAS: "Fedtstoffer",
    GUARNICIÓN: "Tilbehør",
    HARINA: "Mel",
    HIERBAS: "Krydderurter",
    HUEVO: "Æg",
    "LÁCTEOS Y DERIVADOS": "Mejeriprodukter",
    LEVADURA: "Gær",
    MARISCOS: "Skaldyr",
    MASA: "Dej",
    MOLECULAR: "Molekylær",
    NUECES: "Nødder",
    OTROS: "Andet",
    PESCADO: "Fisk",
    REPOSTERÍA: "Bagværk",
    RES: "Oksekød",
    SAL: "Salt",
    "SECOS Y ABARROTES": "Tørvarer",
    SIROPES: "Sirupper",
    "Sub Receta / produccion (Mise en place)": "Underopskrift",
    VEGETAL: "Grøntsager",
  },
  fr: {
    ACEITES: "Huiles",
    ALCOHOL: "Alcool",
    AVES: "Volaille",
    BEBIDAS: "Boissons",
    CAFÉ: "Café",
    CERDO: "Porc",
    CHOCOLATE: "Chocolat",
    GAME: "Gibier",
    DESECHABLES: "Jetables",
    DULCE: "Sucreries",
    EMBUTIDO: "Charcuterie",
    ESENCIA: "Essences",
    ESPECIAS: "Épices",
    FIDEOS: "Pâtes",
    FLORES: "Fleurs comestibles",
    FRUTA: "Fruits",
    GRANOS: "Céréales",
    GRASAS: "Graisses",
    GUARNICIÓN: "Garnitures",
    HARINA: "Farine",
    HIERBAS: "Herbes",
    HUEVO: "Œufs",
    "LÁCTEOS Y DERIVADOS": "Produits laitiers",
    LEVADURA: "Levure",
    MARISCOS: "Fruits de mer",
    MASA: "Pâte",
    MOLECULAR: "Moléculaire",
    NUECES: "Noix",
    OTROS: "Autres",
    PESCADO: "Poisson",
    REPOSTERÍA: "Pâtisserie",
    RES: "Bœuf",
    SAL: "Sel",
    "SECOS Y ABARROTES": "Épicerie sèche",
    SIROPES: "Sirops",
    "Sub Receta / produccion (Mise en place)": "Sous-recette",
    VEGETAL: "Légumes",
  },
  pt: {
    ACEITES: "Óleos",
    ALCOHOL: "Álcool",
    AVES: "Aves",
    BEBIDAS: "Bebidas",
    CAFÉ: "Café",
    CERDO: "Carne de porco",
    CHOCOLATE: "Chocolate",
    GAME: "Caça",
    DESECHABLES: "Descartáveis",
    DULCE: "Doces",
    EMBUTIDO: "Embutidos",
    ESENCIA: "Essências",
    ESPECIAS: "Especiarias",
    FIDEOS: "Massas",
    FLORES: "Flores comestíveis",
    FRUTA: "Frutas",
    GRANOS: "Grãos",
    GRASAS: "Gorduras",
    GUARNICIÓN: "Guarnições",
    HARINA: "Farinha",
    HIERBAS: "Ervas",
    HUEVO: "Ovos",
    "LÁCTEOS Y DERIVADOS": "Laticínios",
    LEVADURA: "Fermento",
    MARISCOS: "Frutos do mar",
    MASA: "Massa (crua)",
    MOLECULAR: "Molecular",
    NUECES: "Nozes",
    OTROS: "Outros",
    PESCADO: "Peixe",
    REPOSTERÍA: "Confeitaria",
    RES: "Carne bovina",
    SAL: "Sal",
    "SECOS Y ABARROTES": "Mercearia seca",
    SIROPES: "Xaropes",
    "Sub Receta / produccion (Mise en place)": "Sub-receita",
    VEGETAL: "Vegetais",
  },
  zh: {
    ACEITES: "油类",
    ALCOHOL: "酒类",
    AVES: "禽类",
    BEBIDAS: "饮料",
    CAFÉ: "咖啡",
    CERDO: "猪肉",
    CHOCOLATE: "巧克力",
    GAME: "野味",
    DESECHABLES: "一次性用品",
    DULCE: "甜食",
    EMBUTIDO: "熟食香肠",
    ESENCIA: "香精",
    ESPECIAS: "香料",
    FIDEOS: "面条",
    FLORES: "食用花卉",
    FRUTA: "水果",
    GRANOS: "谷物",
    GRASAS: "脂肪",
    GUARNICIÓN: "配菜",
    HARINA: "面粉",
    HIERBAS: "香草",
    HUEVO: "蛋类",
    "LÁCTEOS Y DERIVADOS": "乳制品",
    LEVADURA: "酵母",
    MARISCOS: "海鲜",
    MASA: "面团",
    MOLECULAR: "分子料理",
    NUECES: "坚果",
    OTROS: "其他",
    PESCADO: "鱼类",
    REPOSTERÍA: "糕点",
    RES: "牛肉",
    SAL: "盐",
    "SECOS Y ABARROTES": "干货杂货",
    SIROPES: "糖浆",
    "Sub Receta / produccion (Mise en place)": "子配方",
    VEGETAL: "蔬菜",
  },
}

const UNIT_LABELS: Partial<Record<LanguageCode, Record<Unit, string>>> = {
  en: {
    gramos: "Grams",
    kilogramos: "Kilograms",
    mililitros: "Milliliters",
    litros: "Liters",
    onzas: "Ounces",
    "onzas líquidas": "Fluid Ounces",
    libras: "Pounds",
    galones: "Gallons",
    unidad: "Unit",
  },
  da: {
    gramos: "Gram",
    kilogramos: "Kilogram",
    mililitros: "Milliliter",
    litros: "Liter",
    onzas: "Ounce",
    "onzas líquidas": "Væskeunser",
    libras: "Pund",
    galones: "Gallon",
    unidad: "Enhed",
  },
  fr: {
    gramos: "Grammes",
    kilogramos: "Kilogrammes",
    mililitros: "Millilitres",
    litros: "Litres",
    onzas: "Onces",
    "onzas líquidas": "Onces liquides",
    libras: "Livres",
    galones: "Gallons",
    unidad: "Unité",
  },
  pt: {
    gramos: "Gramas",
    kilogramos: "Quilogramas",
    mililitros: "Mililitros",
    litros: "Litros",
    onzas: "Onças",
    "onzas líquidas": "Onças líquidas",
    libras: "Libras",
    galones: "Galões",
    unidad: "Unidade",
  },
  zh: {
    gramos: "克",
    kilogramos: "千克",
    mililitros: "毫升",
    litros: "升",
    onzas: "盎司",
    "onzas líquidas": "液量盎司",
    libras: "磅",
    galones: "加仑",
    unidad: "单位",
  },
}

const PRESENTATION_LABELS: Partial<Record<LanguageCode, Record<Presentation, string>>> = {
  en: {
    Lata: "Can",
    Botella: "Bottle",
    Frasco: "Jar",
    Caja: "Box",
    Bolsa: "Bag",
    Bote: "Tub",
    Paquete: "Package",
    "Envase plástico": "Plastic Container",
    Saco: "Sack",
    Tarrina: "Tub / Punnet",
    "Tetra Pak": "Tetra Pak",
    Ampolla: "Ampoule",
    Sobre: "Sachet",
    Granel: "Bulk",
  },
  da: {
    Lata: "Dåse",
    Botella: "Flaske",
    Frasco: "Glas",
    Caja: "Kasse",
    Bolsa: "Pose",
    Bote: "Bøtte",
    Paquete: "Pakke",
    "Envase plástico": "Plastbeholder",
    Saco: "Sæk",
    Tarrina: "Bakke",
    "Tetra Pak": "Tetra Pak",
    Ampolla: "Ampul",
    Sobre: "Brev",
    Granel: "Løsvægt",
  },
  fr: {
    Lata: "Boîte de conserve",
    Botella: "Bouteille",
    Frasco: "Bocal",
    Caja: "Boîte",
    Bolsa: "Sac",
    Bote: "Pot",
    Paquete: "Paquet",
    "Envase plástico": "Contenant plastique",
    Saco: "Grand sac",
    Tarrina: "Barquette",
    "Tetra Pak": "Tetra Pak",
    Ampolla: "Ampoule",
    Sobre: "Sachet",
    Granel: "Vrac",
  },
  pt: {
    Lata: "Lata",
    Botella: "Garrafa",
    Frasco: "Frasco",
    Caja: "Caixa",
    Bolsa: "Saco",
    Bote: "Pote",
    Paquete: "Pacote",
    "Envase plástico": "Recipiente plástico",
    Saco: "Saco grande",
    Tarrina: "Tarrina",
    "Tetra Pak": "Tetra Pak",
    Ampolla: "Ampola",
    Sobre: "Sachê",
    Granel: "A granel",
  },
  zh: {
    Lata: "罐头",
    Botella: "瓶",
    Frasco: "玻璃瓶",
    Caja: "箱",
    Bolsa: "袋",
    Bote: "桶",
    Paquete: "包",
    "Envase plástico": "塑料容器",
    Saco: "麻袋",
    Tarrina: "小盒",
    "Tetra Pak": "利乐包",
    Ampolla: "安瓿",
    Sobre: "小袋",
    Granel: "散装",
  },
}

// Claves = el texto crudo que devuelve lib/merma-categories.ts#getMermaLevel (canónico
// en Español, usado también como key de estilos de color en la UI).
const MERMA_LEVEL_LABELS: Partial<Record<LanguageCode, Record<string, string>>> = {
  en: { Ninguna: "None", Baja: "Low", Media: "Medium", Alta: "High", "Muy Alta": "Very High" },
  da: { Ninguna: "Ingen", Baja: "Lav", Media: "Middel", Alta: "Høj", "Muy Alta": "Meget høj" },
  fr: { Ninguna: "Aucune", Baja: "Faible", Media: "Moyenne", Alta: "Élevée", "Muy Alta": "Très élevée" },
  pt: { Ninguna: "Nenhuma", Baja: "Baixa", Media: "Média", Alta: "Alta", "Muy Alta": "Muito alta" },
  zh: { Ninguna: "无", Baja: "低", Media: "中", Alta: "高", "Muy Alta": "非常高" },
}

export function getCategoryLabel(category: string, language: LanguageCode): string {
  if (language === "es") return category
  return CATEGORY_LABELS[language]?.[category as Category] ?? category
}

export function getUnitLabel(unit: string, language: LanguageCode): string {
  if (language === "es") return unit
  return UNIT_LABELS[language]?.[unit as Unit] ?? unit
}

export function getPresentationLabel(presentation: string, language: LanguageCode): string {
  if (language === "es") return presentation
  return PRESENTATION_LABELS[language]?.[presentation as Presentation] ?? presentation
}

export function getMermaLevelLabel(level: string, language: LanguageCode): string {
  if (language === "es") return level
  return MERMA_LEVEL_LABELS[language]?.[level] ?? level
}
