import type { RecipeStep } from "@/types/recipe"
import type { LanguageCode } from "@/lib/i18n/translations"

/**
 * Mismo patrón no invasivo que lib/classification-labels.ts: los pasos de receta
 * (types/recipe.ts, recipeSteps) se guardan en Español fijo — es el VALOR canónico que
 * usa el campo `recipe.plate`/`recipe.step`, comparaciones y PDFs — y NUNCA se traduce.
 * Este archivo solo controla la ETIQUETA que ve el usuario, por idioma. Español no
 * necesita tabla propia: el valor guardado YA es la etiqueta en Español.
 */

const EN_LABELS: Record<RecipeStep, string> = {
  Bienvenida: "Welcome",
  "Amuse-bouche": "Amuse-bouche",
  "Pan y mantequilla": "Bread and Butter",
  Entrada: "Starter",
  "Entrada fría": "Cold Starter",
  "Entrada caliente": "Hot Starter",
  Sopa: "Soup",
  Consomé: "Consommé",
  "Intermedio vegetal": "Vegetable Intermezzo",
  Pasta: "Pasta",
  Arroz: "Rice",
  "Plato intermedio": "Intermediate Course",
  Pescado: "Fish",
  Mariscos: "Seafood",
  "Carne blanca": "White Meat",
  "Carne roja": "Red Meat",
  Vegetariano: "Vegetarian",
  Vegano: "Vegan",
  "Limpieza de paladar": "Palate Cleanser",
  "Plato fuerte": "Main Course",
  "Plato compartido": "Shared Plate",
  Quesos: "Cheeses",
  Prepostre: "Pre-dessert",
  Postre: "Dessert",
  "Postre de chocolate": "Chocolate Dessert",
  "Petit fours": "Petit Fours",
  Café: "Coffee",
  Té: "Tea",
  Infusión: "Herbal Tea",
  Digestivo: "Digestif",
  "Maridaje de cierre": "Closing Pairing",
  "Pan dulce": "Sweet Bread",
  "Degustación especial": "Special Tasting",
  "Menú infantil": "Kids Menu",
  "Cierre de experiencia": "Experience Closing",
}

const DA_LABELS: Record<RecipeStep, string> = {
  Bienvenida: "Velkomst",
  "Amuse-bouche": "Amuse-bouche",
  "Pan y mantequilla": "Brød og smør",
  Entrada: "Forret",
  "Entrada fría": "Kold forret",
  "Entrada caliente": "Varm forret",
  Sopa: "Suppe",
  Consomé: "Konsommé",
  "Intermedio vegetal": "Grøntsagsmellemret",
  Pasta: "Pasta",
  Arroz: "Ris",
  "Plato intermedio": "Mellemret",
  Pescado: "Fisk",
  Mariscos: "Skaldyr",
  "Carne blanca": "Hvidt kød",
  "Carne roja": "Rødt kød",
  Vegetariano: "Vegetarisk",
  Vegano: "Vegansk",
  "Limpieza de paladar": "Gane-renser",
  "Plato fuerte": "Hovedret",
  "Plato compartido": "Delt ret",
  Quesos: "Oste",
  Prepostre: "Fordessert",
  Postre: "Dessert",
  "Postre de chocolate": "Chokoladedessert",
  "Petit fours": "Petit fours",
  Café: "Kaffe",
  Té: "Te",
  Infusión: "Urtete",
  Digestivo: "Digestif",
  "Maridaje de cierre": "Afsluttende parring",
  "Pan dulce": "Sødt brød",
  "Degustación especial": "Speciel smagning",
  "Menú infantil": "Børnemenu",
  "Cierre de experiencia": "Afslutning af oplevelsen",
}

const FR_LABELS: Record<RecipeStep, string> = {
  Bienvenida: "Bienvenue",
  "Amuse-bouche": "Amuse-bouche",
  "Pan y mantequilla": "Pain et beurre",
  Entrada: "Entrée",
  "Entrada fría": "Entrée froide",
  "Entrada caliente": "Entrée chaude",
  Sopa: "Soupe",
  Consomé: "Consommé",
  "Intermedio vegetal": "Intermède végétal",
  Pasta: "Pâtes",
  Arroz: "Riz",
  "Plato intermedio": "Plat intermédiaire",
  Pescado: "Poisson",
  Mariscos: "Fruits de mer",
  "Carne blanca": "Viande blanche",
  "Carne roja": "Viande rouge",
  Vegetariano: "Végétarien",
  Vegano: "Végane",
  "Limpieza de paladar": "Trou normand",
  "Plato fuerte": "Plat principal",
  "Plato compartido": "Plat à partager",
  Quesos: "Fromages",
  Prepostre: "Pré-dessert",
  Postre: "Dessert",
  "Postre de chocolate": "Dessert au chocolat",
  "Petit fours": "Petits fours",
  Café: "Café",
  Té: "Thé",
  Infusión: "Infusion",
  Digestivo: "Digestif",
  "Maridaje de cierre": "Accord de clôture",
  "Pan dulce": "Pain sucré",
  "Degustación especial": "Dégustation spéciale",
  "Menú infantil": "Menu enfant",
  "Cierre de experiencia": "Clôture de l'expérience",
}

const PT_LABELS: Record<RecipeStep, string> = {
  Bienvenida: "Boas-vindas",
  "Amuse-bouche": "Amuse-bouche",
  "Pan y mantequilla": "Pão e manteiga",
  Entrada: "Entrada",
  "Entrada fría": "Entrada fria",
  "Entrada caliente": "Entrada quente",
  Sopa: "Sopa",
  Consomé: "Consomê",
  "Intermedio vegetal": "Intermédio vegetal",
  Pasta: "Massa",
  Arroz: "Arroz",
  "Plato intermedio": "Prato intermédio",
  Pescado: "Peixe",
  Mariscos: "Frutos do mar",
  "Carne blanca": "Carne branca",
  "Carne roja": "Carne vermelha",
  Vegetariano: "Vegetariano",
  Vegano: "Vegano",
  "Limpieza de paladar": "Limpeza de paladar",
  "Plato fuerte": "Prato principal",
  "Plato compartido": "Prato para compartilhar",
  Quesos: "Queijos",
  Prepostre: "Pré-sobremesa",
  Postre: "Sobremesa",
  "Postre de chocolate": "Sobremesa de chocolate",
  "Petit fours": "Petit fours",
  Café: "Café",
  Té: "Chá",
  Infusión: "Infusão",
  Digestivo: "Digestivo",
  "Maridaje de cierre": "Harmonização final",
  "Pan dulce": "Pão doce",
  "Degustación especial": "Degustação especial",
  "Menú infantil": "Menu infantil",
  "Cierre de experiencia": "Encerramento da experiência",
}

const ZH_LABELS: Record<RecipeStep, string> = {
  Bienvenida: "欢迎",
  "Amuse-bouche": "开胃小点",
  "Pan y mantequilla": "面包与黄油",
  Entrada: "前菜",
  "Entrada fría": "冷前菜",
  "Entrada caliente": "热前菜",
  Sopa: "汤",
  Consomé: "清汤",
  "Intermedio vegetal": "蔬菜间菜",
  Pasta: "意面",
  Arroz: "米饭",
  "Plato intermedio": "中间course",
  Pescado: "鱼",
  Mariscos: "海鲜",
  "Carne blanca": "白肉",
  "Carne roja": "红肉",
  Vegetariano: "素食",
  Vegano: "纯素",
  "Limpieza de paladar": "清味",
  "Plato fuerte": "主菜",
  "Plato compartido": "分享菜",
  Quesos: "奶酪",
  Prepostre: "餐前甜点",
  Postre: "甜点",
  "Postre de chocolate": "巧克力甜点",
  "Petit fours": "小点心",
  Café: "咖啡",
  Té: "茶",
  Infusión: "花草茶",
  Digestivo: "餐后酒",
  "Maridaje de cierre": "收尾搭配",
  "Pan dulce": "甜面包",
  "Degustación especial": "特别品鉴",
  "Menú infantil": "儿童菜单",
  "Cierre de experiencia": "体验结束",
}

const LABELS_BY_LANGUAGE: Partial<Record<LanguageCode, Record<RecipeStep, string>>> = {
  en: EN_LABELS,
  da: DA_LABELS,
  fr: FR_LABELS,
  pt: PT_LABELS,
  zh: ZH_LABELS,
}

export function getRecipeStepLabel(step: string, language: LanguageCode): string {
  if (language === "es") return step
  return LABELS_BY_LANGUAGE[language]?.[step as RecipeStep] ?? step
}
