export const countries = [
  { code: "US", name: "Estados Unidos" },
  { code: "ES", name: "España" },
  { code: "MX", name: "México" },
  { code: "AR", name: "Argentina" },
  { code: "CO", name: "Colombia" },
  { code: "PE", name: "Perú" },
  { code: "CL", name: "Chile" },
  { code: "EC", name: "Ecuador" },
  { code: "VE", name: "Venezuela" },
  { code: "GT", name: "Guatemala" },
  { code: "CU", name: "Cuba" },
  { code: "BO", name: "Bolivia" },
  { code: "DO", name: "República Dominicana" },
  { code: "HN", name: "Honduras" },
  { code: "PY", name: "Paraguay" },
  { code: "SV", name: "El Salvador" },
  { code: "NI", name: "Nicaragua" },
  { code: "CR", name: "Costa Rica" },
  { code: "PR", name: "Puerto Rico" },
  { code: "PA", name: "Panamá" },
  { code: "UY", name: "Uruguay" },
  // Añade más países según sea necesario
]

export const currencies = [
  { code: "USD", name: "Dólar estadounidense", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "MXN", name: "Peso mexicano", symbol: "$" },
  { code: "ARS", name: "Peso argentino", symbol: "$" },
  { code: "COP", name: "Peso colombiano", symbol: "$" },
  { code: "PEN", name: "Sol peruano", symbol: "S/" },
  { code: "CLP", name: "Peso chileno", symbol: "$" },
  { code: "VES", name: "Bolívar soberano", symbol: "Bs." },
  { code: "GTQ", name: "Quetzal guatemalteco", symbol: "Q" },
  { code: "CUP", name: "Peso cubano", symbol: "₱" },
  { code: "BOB", name: "Boliviano", symbol: "Bs" },
  { code: "DOP", name: "Peso dominicano", symbol: "RD$" },
  { code: "HNL", name: "Lempira hondureño", symbol: "L" },
  { code: "PYG", name: "Guaraní paraguayo", symbol: "₲" },
  { code: "SVC", name: "Colón salvadoreño", symbol: "₡" },
  { code: "NIO", name: "Córdoba nicaragüense", symbol: "C$" },
  { code: "CRC", name: "Colón costarricense", symbol: "₡" },
  { code: "PAB", name: "Balboa panameño", symbol: "B/." },
  { code: "UYU", name: "Peso uruguayo", symbol: "$U" },
  // Añade más monedas según sea necesario
]
