// Brugermanual — dansk. Skal følge content/es.mjs blok for blok (kontrolleres af scripts/build.mjs).
export default {
  ui: {
    manualName: "Brugermanual",
    contents: "Indhold",
    contentsLede: "Er det første gang, så læs kapitel 1 og hop derefter direkte til det, du har brug for: hvert kapitel kan læses for sig.",
    inThisChapter: "I dette kapitel",
    figure: "Figur",
    coverKicker: "Brugermanual",
    coverTitle: "Kalkulér, sælg og voks med Gastrometrics",
    coverLede: "Den komplette guide til at gøre dine opskrifter til fair priser, holde styr på dit lager og forstå tallene bag dit køkken.",
    coverModules: ["Ingredienser", "Opskriftsark", "Lager", "Menuer", "Indkøbsordrer", "Salg", "Rapporter", "Team"],
    edition: "Udgave september 2026",
  },
  chapters: [
    {
      id: "bienvenida",
      title: "Velkommen til Gastrometrics",
      intro: "Gastrometrics gør dine opskrifter til klare tal: hvad hver ret koster dig, hvad du skal sælge den til, og hvad den giver dig. Dette kapitel viser dig det store billede og den hurtigste vej til dit første resultat.",
      blocks: [
        ["h3", "Hvad Gastrometrics gør for dig"],
        ["p", "Du indtaster dine ingredienser med det, du betaler for dem, bygger dine opskrifter med de mængder, du bruger, og appen beregner selv <strong>den reelle kostpris for hver ret</strong>, foreslår en <strong>salgspris</strong> og viser din <strong>margin</strong>. Derfra bruger alt andet —lager, menuer, indkøb, salg og rapporter— de samme tal, så du aldrig skal skrive dem to gange."],
        ["h3", "Sådan hænger modulerne sammen"],
        ["flow", [
          ["Ingredienser", "pris og svind"],
          ["Opskrifter", "kostpris og pris"],
          ["Menuer", "menuer og events"],
          ["Indkøb", "ordrer til leverandører"],
          ["Underopskrifter", "bliver ingredienser igen"],
          ["Lager", "beholdning og optællinger"],
          ["Salg", "manuelt, POS, fakturaer"],
          ["Rapporter", "reel margin og resultat"],
          "Fuld pil = automatisk · stiplet pil = du registrerer det selv (en optælling eller et indkøb)",
        ]],
        ["p", "<strong>Opskrifterne</strong> er i centrum: de læser dine ingredienspriser og fodrer menuer, indkøbsordrer og rapporter. Ændrer du prisen på en ingrediens, genberegnes alle opskrifter, der bruger den, af sig selv."],
        ["h3", "Dine første 10 minutter"],
        ["steps", [
          "<strong>Opret 3 eller 4 ingredienser</strong> under Ingredienser med deres indkøbspris og nettoindhold. Du behøver ikke hele dit lager for at komme i gang.",
          "<strong>Opret din første opskrift</strong> i Opskriftsark: vælg de ingredienser, og skriv den mængde, du bruger af hver.",
          "<strong>Se resultatet</strong>: produktionsomkostning, foreslået pris og margin vises på samme skærm i realtid.",
          "<strong>Gem og eksportér</strong> arket som PDF til dit køkken eller din revisor.",
          "<strong>Fortsæt når du vil</strong> med lager, menuer eller indkøb. De er ikke nødvendige for at se din første pris.",
        ]],
        ["tip", "Vil du hellere se et eksempel først?", "Hvis du endnu ikke har nogen opskrifter, tilbyder Dashboard <strong>»Se et eksempel først«</strong>: det opretter en eksempelopskrift med kostpris og pris allerede beregnet, så du kan se, hvordan det virker. Du kan slette den når som helst."],
        ["h3", "Sådan læser du denne manual"],
        ["cards", [
          ["", "Tip", "Genveje og gode vaner, der sparer dig tid."],
          ["", "Vigtigt", "Detaljer, der er værd at kende, før du trykker på en knap."],
          ["", "Plan", "Funktioner, der afhænger af dit abonnement (kapitel 14)."],
        ]],
      ],
    },
    {
      id: "cuenta",
      title: "Din konto og dine virksomheder",
      intro: "Alt i Gastrometrics hører til en virksomhed. Her ser du, hvordan du tilmelder dig, opretter virksomheder, skifter mellem dem og får mest ud af Dashboard.",
      blocks: [
        ["h3", "Opret din konto"],
        ["p", "Tilmeldingen er en guide i 5 trin: dine oplysninger og adgangskode, dine professionelle oplysninger (land, valuta, virksomhedstype og -størrelse), den <strong>plan</strong> du vil bruge, accept af vilkårene og et resumé. Kommer du fra prissiden med en plan allerede valgt, er den forvalgt."],
        ["p", "Det sidste trin har et valgfrit felt til at <strong>modtage nyheder og påmindelser via e-mail</strong>. Det er ikke markeret fra start, og du kan ændre det når som helst under Indstillinger (kapitel 15)."],
        ["p", "Når du logger ind, er feltet <strong>Husk mig på denne enhed</strong> markeret: din session forbliver åben. Fjern markeringen på en delt computer, så lukkes sessionen, når du lukker browseren."],
        ["h3", "Opret en virksomhed"],
        ["steps", [
          "<strong>Grunddata og logo.</strong> Navn, beskrivelse, virksomhedstype og eventuelt et logo, der vises i toppen af dine PDF'er.",
          "<strong>Faste månedlige udgifter.</strong> Husleje, forsyning, personale, markedsføring og andet. De bruges til at fordele dine faste omkostninger i prisen på hver ret (kapitel 4).",
          "<strong>Standardprismetode.</strong> »Gastrometrics« (6 poster) eller »Food Cost %«. Hver ny opskrift arver den, og du kan ændre den opskrift for opskrift.",
        ]],
        ["chips", ["Restaurant", "Café", "Bageri", "Konditori", "Food Truck", "Catering", "Bar", "Pizzeria", "Fastfood", "Andet"]],
        ["p", "Hver virksomhed har sine egne ingredienser, opskrifter, lager, menuer og indkøb: intet blandes mellem virksomheder. I hver virksomheds panel kan du vælge mellem 12 temafarver, som også farver accenterne i dens PDF'er."],
        ["h3", "Skift mellem virksomheder"],
        ["p", "<strong>Virksomheder</strong> viser et kort for hver virksomhed med knappen »Åbn«. Mens du arbejder i et modul, viser sidemenuen også dine virksomheder, så du kan skifte uden at gå tilbage til start."],
        ["h3", "Dashboard"],
        ["figure", "01-dashboard.jpg", "Dashboard: det, der kræver din opmærksomhed i dag, dine nøgletal og genveje til hvert modul."],
        ["list", [
          "<strong>Hvad skal du gøre i dag</strong>: ingredienser under minimum, opskrifter uden salgspris og din gennemsnitlige margin. Hvert kort fører dig direkte derhen, hvor du kan løse det.",
          "<strong>Nøgletal</strong>: antal opskrifter, ingredienser, virksomheder og gennemsnitlig kostpris på tværs af alle dine virksomheder.",
          "<strong>Hurtige handlinger</strong>: en genvej pr. modul, så du kommer ind uden sidemenuen.",
        ]],
        ["p", "Mens du kommer i gang, viser Dashboardet <strong>Din vej</strong>: tilføj ingredienser, opret din første opskrift, nå 3 opskrifter, og udforsk det nye. Hvert trin fører dig direkte derhen. Du kan skjule det med X."],
        ["p", "Knapperne i Din vej åbner importen direkte: \"Importér mine ingredienser\" og \"Importér en opskrift\". Vil du hellere starte fra bunden, har hvert trin også den manuelle mulighed."],
        ["h3", "Sidemenuen"],
        ["table", ["Afsnit", "Hvad det bruges til"], [
          ["Dashboard", "Overblik over hele din konto og det, der kræver opmærksomhed."],
          ["Opskriftsark", "Opret eller redigér en opskrift med kostpris og pris."],
          ["Mine Opskrifter", "Søg, duplikér, flyt og gendan opskrifter."],
          ["Ingredienser", "Din ingrediensdatabase, priser og svind."],
          ["Lager", "Beholdning, optællinger og minimumsalarmer."],
          ["Team", "Invitér personer og giv dem rettigheder."],
          ["Menuer", "Byg menuer efter retter til service eller events."],
          ["Indkøbsordrer", "Ordrer til leverandører, manuelle eller foreslåede."],
          ["Salg", "Registrér salg, importér dit POS og udsted fakturaer."],
          ["Rapporter", "Overblik over virksomheden og økonomi."],
          ["Virksomheder", "Opret, åbn og slet virksomheder."],
        ]],
        ["info", "Menuen udfyldes undervejs", "For ikke at overvælde dig starter menuen med det vigtigste. Med din første opskrift dukker Rapporter og Salg op; med 3 opskrifter Lager, Menuer, Indkøbsordrer og Team, markeret \"Ny\". Vil du se det hele fra start, så brug \"Vis alle moduler nu\" nederst i menuen."],
        ["info", "Indstillinger og Min plan", "Indstillinger er ikke en side: det er et vindue, du åbner fra enhver skærm med tandhjulsikonet. Din plan og dit abonnement findes under <strong>Min plan</strong> nederst i menuen."],
      ],
    },
    {
      id: "ingredientes",
      title: "Ingredienser",
      intro: "Dine ingredienser er grundlaget for al kalkulation. Er deres priser opdaterede, er dine opskrifter, menuer og rapporter det også.",
      blocks: [
        ["figure", "02-ingredientes.jpg", "Virksomhedens ingrediensdatabase med kategori, enhed, pris og leverandør."],
        ["h3", "Hvad en ingrediens indeholder"],
        ["p", "Navn, kategori, måleenhed, leverandør, indkøbsemballage (valgfri) og prisen: hvad du betaler for hele pakken, og hvor meget den indeholder. Ud fra det beregner appen <strong>prisen pr. enhed</strong>, som er den, dine opskrifter faktisk bruger."],
        ["formula", "Pris pr. enhed", ["Pris pr. enhed = Indkøbspris ÷ Nettoindhold"], "Nettoindholdet angives i ingrediensens basisenhed (gram, milliliter, stk…)."],
        ["example", "Eksempel · en sæk mel", [
          ["Indkøbspris for sækken", "450.00"],
          ["Nettoindhold", "25000 g"],
          ["Pris pr. gram", "0.018", true],
          ["En opskrift, der bruger 300 g, koster", "300 × 0.018 = 5.40"],
        ]],
        ["h3", "Kategorier og enheder"],
        ["p", "Kategorierne er en fast liste på 40 (Fjerkræ, Oksekød, Fisk, Mejeri, Mel, Krydderier, Drikkevarer, Spiritus, Vin, Øl, Sodavand og mixere, Engangsartikler…) plus en særlig, <strong>Underopskrift / produktion</strong>, som automatisk tildeles tilberedninger, du bruger som ingrediens (kapitel 5). De tilgængelige enheder er:"],
        ["chips", ["Gram", "Kilogram", "Milliliter", "Liter", "Ounce", "Flydende ounce", "Pund", "Gallon", "Stk"]],
        ["p", "Brug <strong>Stk</strong> til ting, du tæller (æg, dåser, boller). Appen behandler dem særligt, for eksempel for at advare dig, hvis en opskrifts udbytte ser for lavt ud."],
        ["tip", "Glem ikke emballagen", "Kopper, takeaway-bokse, poser, servietter eller sugerør er også en del af hver rets omkostning. Opret dem som ingredienser i kategorien <strong>Engangsartikler</strong> (f.eks. en pakke med 100 bokse, i stk.) og tilføj dem til opskriften på det, du sælger som takeaway. Ellers dækker din pris dem ikke."],
        ["h3", "Indkøbsemballage"],
        ["p", "Køber du pr. kasse, sæk, flaske, dåse, pose eller glas, så gem hvor meget hver pakke indeholder. Så står der »4 kasser« på dine indkøbsordrer i stedet for en mængde i gram, som ingen ville bestille."],
        ["h3", "Import af din ingrediensliste"],
        ["p", "Indlæs hele din database på én gang fra Excel, CSV eller en indsat liste, og eksportér den til Excel, når du vil. Vil du hellere starte fra et format, laver appen en skabelon med sine rigtige kategorier og enheder; overskrifter genkendes på alle 6 sprog."],
        ["p", "Den guidede tur i Ingredienser slutter med at åbne denne import, så du kan indlæse hele listen på én gang. Du kan også tilføje dem én ad gangen med \"Ny ingrediens\"."],
        ["p", "Du behøver ikke skabelonen: upload din fil, som den er (.xlsx, .xls eller .csv), eller <strong>indsæt din liste</strong> kopieret fra Excel, Google Sheets, en e-mail eller WhatsApp, én pr. linje (f.eks. \"Tomat, 2 kg, 12.50\"). Appen genkender kolonner, selv med andre navne eller uden overskrifter, priser med valutategn og decimalkomma eller -punktum (\"12,50 kr\", \"1.250,75\") og indhold skrevet sammen med enheden (\"sæk 25 kg\"). Har listen ingen kategori, foreslås en ud fra navnet."],
        ["tip", "Du ser alt før importen", "Forhåndsvisningen viser hver ingrediens med indhold, pris og status: \"Klar\", \"Ingen pris\" eller \"Findes allerede\" (de springes over). Når den er færdig, foreslår appen næste skridt: at importere dine opskrifter."],
        ["info", "Priser og valuta", "Priserne gemmes i din kontos valuta (Indstillinger); appen omregner ikke mellem valutaer. De accepteres med valutategn eller -kode og med decimalkomma eller -punktum: \"12,50 kr\" og \"12.50\" er 12.50, \"1.250,75\" og \"1,250.75\" er 1250.75. Et tal som \"1.500\" læses som ét tusind fem hundrede, hvis din valuta bruges uden decimaler (costaricansk colón, colombiansk, chilensk eller argentinsk peso, guaraní), eller hvis det har \"₡\"; med andre valutaer er det 1.5. Tjek kolonnen Pris i forhåndsvisningen, før du importerer."],
        ["h3", "Svind"],
        ["p", "Svind er det, du betaler for, men ikke kan bruge: skræller, ben, afskær, fordampning. Under <strong>Administrer Svind</strong> slår du systemet til og vælger for hver ingrediens enten den typiske procent for dens kategori eller din egen (eller en fast mængde)."],
        ["formula", "Reel kostpris med svind", ["Brugbart indhold = Nettoindhold × (1 − svind %)", "Pris pr. enhed = Indkøbspris ÷ Brugbart indhold"], "Du betaler for det hele, men bruger kun en del, så den reelle pris pr. enhed stiger. Slår du svind fra, vender alt tilbage til de oprindelige værdier."],
        ["p", "Nogle typiske procenter pr. kategori: Skaldyr 63 %, Fisk 52 %, Oksekød 33 %, Fjerkræ 27 %, Frugt 24 %, Grøntsager 21 %. Tørvarer og emballerede varer starter på 0 %. Barkategorierne har deres eget typiske svind: spiritus 2 %, vin 5 %, fadøl 18 % og flaskeøl 0 % (kapitel 6)."],
        ["info", "Plan", "Svindstyring er tilgængelig fra planen <strong>Home Cook</strong>."],
        ["h3", "Allergener"],
        ["p", "I det sidste trin for hver ingrediens markerer du, hvilke af de 14 allergener, der skal deklareres, den indeholder (gluten, mælk, æg, nødder, soja, fisk, krebsdyr, sesam…). Opskrifter, der bruger den —også via deres underopskrifter— viser dem automatisk i Opskriftsarket, i opskriftens tre PDF'er og under hver ret på gæstemenuen. De skrives aldrig manuelt i opskriften, så de bliver ikke forældede."],
        ["h3", "Slet en ingrediens"],
        ["p", "Før du bekræfter, viser appen hvilke opskrifter der bruger den. Den forhindrer dig ikke i at slette, men du ved, hvilke opskrifter der vil mangle en ingrediens."],
      ],
    },
    {
      id: "ficha",
      title: "Opskrifter og Opskriftsark",
      intro: "Hjertet i Gastrometrics: du gør en liste af ingredienser til en præcis kostpris og en velbegrundet salgspris og ser altid, hvor hvert tal kommer fra.",
      blocks: [
        ["figure", "03-ficha-tecnica.jpg", "En opskrift åbnet i Opskriftsark: generelle oplysninger, ingredienser og kostberegning."],
        ["h3", "Udfyld arket"],
        ["list", [
          "<strong>Navn</strong> og <strong>Klassifikation</strong> (22 muligheder, fra Varm linje til Konditori eller R&D). Klassifikationen »Underopskrift« gør opskriften til en ingrediens (kapitel 5). De 5 »Bar · …«-klassifikationer beregner prisen med pour cost (kapitel 6).",
          "<strong>Trin</strong>: hvor i serveringen den hører til (forret, hovedret, dessert…).",
          "<strong>Udbytte</strong>: hvor meget opskriften giver (8 portioner, 1200 g…) med enhed.",
          "<strong>Ingredienser</strong>: søg i din database og skriv mængden. Hver linje viser, hvad den koster.",
          "<strong>Fremgangsmåde og bemærkninger</strong> samt et <strong>billede</strong> af retten.",
        ]],
        ["tip", "Gå videre med Enter", "I de første felter fører Enter dig til det næste, så du kan udfylde arket næsten uden at røre musen."],
        ["h3", "Dit arbejde gemmes i 24 timer"],
        ["p", "Mens du opretter en ny opskrift, gemmer Gastrometrics en <strong>automatisk kladde</strong>. Lukker du fanen, mister forbindelsen eller går til et andet modul, kommer opskriften tilbage præcis som du forlod den, når du vender tilbage til Opskriftsark, med en besked øverst. Kladden holder <strong>24 timer fra din seneste ændring</strong> og findes også, hvis du logger ind fra en anden enhed."],
        ["figure", "05-borrador.jpg", "Når du vender tilbage, bekræfter en besked, at din opskrift er gendannet. »Ryd arket« gør den tom."],
        ["p", "Vil du starte forfra? Brug <strong>Ryd arket</strong> (ved siden af »Gem Opskrift« eller i beskeden). Den beder om bekræftelse og sletter alt: navn, ingredienser, fremgangsmåde, billede, priser og den gemte kladde. Når du gemmer opskriften, slettes kladden automatisk."],
        ["h3", "Produktionsomkostning"],
        ["formula", "Kostpris pr. ingrediens og for opskriften", ["Linjens kostpris = Mængde × Pris pr. enhed", "Produktionsomkostning = Summen af alle linjer"]],
        ["formula", "Enhedskostpris", ["Enhedskostpris = Produktionsomkostning ÷ Udbytte"], "Angiver du ikke et udbytte, estimerer appen det ud fra den samlede vægt af ingredienser målt i g, ml, kg eller liter."],
        ["h3", "To måder at beregne prisen på"],
        ["p", "Hver opskrift bruger én af to metoder. Din virksomhed bestemmer standarden, men du kan ændre den opskrift for opskrift uden at miste noget: begge tager udgangspunkt i den samme reelle kostpris."],
        ["cards", [
          ["Metode 1", "Gastrometrics (6 poster)", "Fordeler din fortjeneste på seks poster, hver som procent af produktionsomkostningen: forsyning 10 %, markedsføring 10 %, driftsomkostninger 30 %, løn 25 %, skat 0 % og nettofortjeneste 30 % (alle kan redigeres)."],
          ["Metode 2", "Food Cost %", "Du vælger, hvor stor en del af prisen råvareomkostningen skal udgøre (typisk 28 % til 35 %), og prisen beregnes ud fra det. Det er branchestandarden."],
        ]],
        ["formula", "Foreslået salgspris", ["6 poster: Pris = Enhedskostpris + (Sum af poster ÷ Udbytte)", "Food Cost: Pris = Enhedskostpris ÷ Mål i %"], "I begge tilfælde rundes prisen <strong>op</strong> til din valutas trin: til 5 i lempira (61 bliver 65, aldrig 60), til 0.50 i dollar eller euro (10.60 bliver 11.00), til 100 i colón. Det er den eneste afrunding i beregningen. Eksemplet nedenfor er i lempira."],
        ["example", "Eksempel · samme kostpris, to metoder (enhedskostpris 20, udbytte 1)", [
          ["6 poster: 2 + 2 + 6 + 5 + 0 + 6", "21"],
          ["20 + 21 = 41 → afrundet", "45", true],
          ["Food Cost 30 %: 20 ÷ 0.30 = 66.67 → afrundet", "70", true],
        ]],
        ["p", "Har din virksomhed faste udgifter og et skøn over antal retter pr. måned, lægges deres forholdsmæssige andel automatisk til prisen som en ekstra post:"],
        ["formula", "Fast omkostning pr. ret", ["Fast omkostning pr. ret = Faste udgifter pr. måned ÷ Forventede retter pr. måned"]],
        ["h3", "Provision til levering eller kort"],
        ["p", "Sælger du via en leveringsapp eller tager imod kortbetaling, skriver du i opskriften den <strong>provision i %</strong>, de tager af prisen. Den foreslåede pris dækker den, og arket viser provisionen pr. enhed, og hvad du har tilbage efter at have betalt den. Fortjeneste og margin trækker den allerede fra."],
        ["formula", "Pris med provision", ["Pris = Pris uden provision ÷ (1 − Provision i %)"], "Det virker med begge metoder og afrundes bagefter, som altid."],
        ["example", "Eksempel · enhedskostpris 20, Food Cost 30 %, provision 30 % (i lempira)", [
          ["Pris uden provision: 20 ÷ 0.30", "66.67"],
          ["66.67 ÷ (1 − 0.30) = 95.24 → rundet op", "100", true],
          ["Appen tager 30 %", "30"],
          ["Du har tilbage pr. ret", "70", true],
        ]],
        ["figure", "04-ficha-tecnica-precio.jpg", "Beregningen af salgsprisen med opskriftens valgte metode, efterfulgt af omkostningsoversigten."],
        ["h3", "Marginer og manuel pris"],
        ["formula", "Opskriftens nøgletal", ["Samlet salg = Endelig pris × Udbytte", "Dækningsbidrag = (Samlet salg − Produktionsomkostning) ÷ Samlet salg", "Kostpris % = Produktionsomkostning ÷ Samlet salg"]],
        ["p", "Den foreslåede pris er aldrig obligatorisk: du kan skrive din egen <strong>salgspris</strong> eller din egen <strong>enhedsfortjeneste</strong>. Marginerne genberegnes med dit tal, men kostprisen afspejler altid, hvad du reelt betaler."],
        ["h3", "Skalér med PAX-modifikatoren"],
        ["p", "Skriv, hvor mange personer du vil servere for, og appen skalerer alle mængder og omkostninger med det samme, altid rundet <strong>op</strong>, så du aldrig mangler. Det er en forhåndsvisning: den gemte opskrift ændres ikke."],
        ["list", [
          "<strong>Eksportér PDF</strong> eller <strong>Generer Indkøbsordre</strong> med PAX aktiv bruger de skalerede mængder uden at gemme noget. Knappen advarer »Skaleret til N«.",
          "<strong>Gem</strong> med PAX aktiv beder om bekræftelse: opskriften gemmes i den nye størrelse, og den tidligere størrelse bevares som »original«.",
          "<strong>Gendan original opskrift</strong> går tilbage til den originale størrelse. Tryk derefter Gem for at bekræfte.",
        ]],
        ["warn", "Mistænkeligt udbytte", "Hvis en ingrediens målt i »stk« er 20 gange det angivne udbytte eller mere (for eksempel 200 æg til et udbytte på 1), ser du en gul advarsel i arket og i PDF'en. Den blokerer ikke noget: den hjælper dig bare med at fange en tastefejl."],
        ["h3", "Importér dine opskrifter"],
        ["p", "Under Mine opskrifter gør <strong>Importér opskrift</strong> en opskrift, du allerede har, til et opskriftsark: indsæt den, som du har den (fra Word, WhatsApp eller en hjemmeside), upload en tekstfil (.txt, .csv, .md), en <strong>Excel</strong>-fil (.xlsx, .xls) eller en <strong>PDF</strong>, eller <strong>tag et foto</strong> med mobilens kamera. Appen genkender navn, portioner, ingredienser med mængde og enhed (200 g, 2 kopper, ½ kg, \"efter smag\", tabeller, lister…) og trinene."],
        ["tip", "Du gennemgår den, før den åbnes", "Hver ingrediens matches med din database, og mængden omregnes til ingrediensens enhed. Dem, du ikke har, kan oprettes (uden pris; du udfylder den senere under Ingredienser), vælges fra din liste eller springes over. Intet gemmes, før du trykker Gem i Opskriftsarket."],
        ["info", "Fotos af opskrifter", "Fotoet læses på din egen telefon eller computer (det uploades ikke til nogen server). Du ser fotoet ved siden af den læste tekst med læsesikkerheden og de usikre linjer markeret: tryk på dem for at rette dem, før du fortsætter. Det bedste resultat får du med et foto taget lige forfra, i godt lys og uden skygger, og ved at vælge det sprog, opskriften er skrevet på."],
        ["info", "Opskriftens sprog", "Du behøver ikke vælge det: appen antager, at opskriften er på det sprog, du bruger i appen, og opdager selv, hvis den er på et andet (f.eks. en engelsk eller kinesisk opskrift), og læser den så igen med det rigtige sprog. Vil du selv fastlægge det, så brug \"Skift\" ved siden af sproget; skifter du det efter at have læst et foto eller en scannet PDF, vises \"Læs igen\". PDF'er med tekst læses, som de er, uden OCR; scannede sider læses på samme måde som fotos."],
        ["info", "Hvad den kan og ikke kan", "Den læser trykte opskrifter, tydelig håndskrift, skærme og PDF'er på appens 6 sprog; tabeller, lister og afsnit; brøker, intervaller (\"2-3\"), tal skrevet med bogstaver og \"efter smag\". Den læser ikke godt meget tæt skråskrift, slørede, mørke eller meget skæve fotos eller sider med flere opskrifter blandet sammen (importér én ad gangen). Den læser op til 6 sider af en PDF og det første ark i en Excel-fil. Den gemmer aldrig noget uden din bekræftelse: du kan altid rette teksten, hver ingrediens og dens mængde."],
        ["p", "Når du gemmer en importeret opskrift, kommer du tilbage til Mine opskrifter med muligheden \"Importér en opskrift mere\", så du kan hente dine opskrifter ind én efter én: de ingredienser, du allerede har oprettet, genkendes automatisk."],
        ["h3", "Mine Opskrifter: duplikér, flyt og papirkurv"],
        ["figure", "06-mis-recetas.jpg", "Mine Opskrifter: alle dine opskrifter med kostpris, udbytte og hurtige handlinger."],
        ["list", [
          "<strong>Dupliker</strong> laver en kopi i samme virksomhed med »(kopi)« i navnet.",
          "<strong>Flyt</strong> kopierer opskriften til en anden af dine virksomheder. Den spørger, om ingredienser og underopskrifter skal med (dem, der allerede findes, genbruges) eller kun opskriften: så åbnes arket i virksomheden, så du vælger ingredienserne fra dens egen database (dem med samme navn kobles automatisk).",
          "<strong>Slet</strong> sender den i <strong>papirkurven</strong>, hvor du kan gendanne den i 30 dage, før den slettes automatisk.",
        ]],
      ],
    },
    {
      id: "subrecetas",
      title: "Underopskrifter",
      intro: "En grundsauce, en fond eller en dej, du bruger i mange retter. Du opretter den én gang og bruger den som enhver anden ingrediens.",
      blocks: [
        ["h3", "Opret en underopskrift"],
        ["p", "Opret opskriften som normalt, og giv den klassifikationen <strong>»Underopskrift«</strong>. Når du gemmer den, opretter Gastrometrics en ingrediens med samme navn, som du kan søge efter og tilføje i ethvert andet opskriftsark."],
        ["formula", "Forbrugsomkostning", ["Forbrugsomkostning = Underopskriftens samlede kostpris ÷ Udbytte"], "Det er, hvad hver enhed af tilberedningen koster (hvert gram sauce, for eksempel), når du bruger den i en anden opskrift."],
        ["h3", "Hvad der er anderledes i en underopskrift"],
        ["p", "Da den ikke sælges alene, har den ingen salgspris, poster eller marginer. Dens oversigt viser kun tre tal: <strong>produktionsomkostning</strong>, <strong>udbytte</strong> og <strong>forbrugsomkostning</strong>."],
        ["h3", "Alt opdateres i kæde"],
        ["p", "Stiger prisen på en ingrediens i din grundsauce, genberegnes forbrugsomkostningen, og ændringen når automatisk ud til hver ret, der bruger den. Du skal ikke åbne en eneste opskrift."],
        ["warn", "Pas på mængderne", "Forbrugsomkostningen er som regel pr. gram eller milliliter. Skriver du »150« og tænker på stk i stedet for gram, stiger rettens kostpris voldsomt. Tjek enheden, før du gemmer."],
      ],
    },
    {
      id: "barra",
      title: "Bar og drikkevarer",
      intro: "Vin, øl, cocktails og alkoholfrie drikke kalkuleres ligesom mad: de er ingredienser og opskrifter med nogle få bartilpasninger. Der er intet separat modul at lære.",
      blocks: [
        ["h3", "Drikkevarer som ingredienser"],
        ["p", "Opret hver flaske, dåse eller fustage som en ingrediens, i milliliter eller liter, med pris og indhold. Der findes egne barkategorier, hver med sit typiske svind (spild, bunden af flasken, skum):"],
        ["table", ["Kategori", "Typisk svind", "Serveres som"], [
          ["Spiritus", "2 %", "Shot 45 ml, dobbelt 90 ml, flaske"],
          ["Vin", "5 %", "Glas 150 eller 125 ml, karaffel 500 ml, flaske"],
          ["Fadøl", "18 %", "Pint 473 ml, halv liter, glas 330 ml"],
          ["Flaskeøl", "0 %", "Hel flaske eller dåse"],
          ["Sodavand og mixere", "2 %", "Hel beholder eller glas 250 ml"],
        ]],
        ["h3", "Cocktails i Opskriftsarket"],
        ["p", "En cocktail er en opskrift med linjerne i milliliter. Når du vælger en <strong>Bar · …</strong>-klassifikation, beregnes prisen med <strong>pour cost</strong>: den andel af prisen, der er vareomkostning. Målet gælder kun den opskrift: det ændrer ikke målet for dine retter."],
        ["table", ["Klassifikation", "Standard pour cost", "Typisk interval"], [
          ["Bar · Cocktails", "20 %", "15–22 %"],
          ["Bar · Vin", "30 %", "25–35 %"],
          ["Bar · Øl", "24 %", "20–28 %"],
          ["Bar · Alkoholfri", "15 %", "10–20 %"],
          ["Bar · Kaffe og te", "20 %", "15–25 %"],
        ]],
        ["formula", "Pris på en drik", ["Pris = Pris pr. servering ÷ Mål for pour cost"], "Den rundes op til din valutas trin, som enhver foreslået pris."],
        ["example", "Eksempel · gin og tonic (i dollar)", [
          ["Gin, 45 ml", "1.69"],
          ["Tonic, 150 ml", "0.55"],
          ["Lime", "0.10"],
          ["Drinkens kostpris", "2.34", true],
          ["2.34 ÷ 0.22 = 10.64 → rundet op", "11.00", true],
        ]],
        ["h3", "Sælg pr. glas eller flaske"],
        ["steps", [
          "Find drikken i <strong>Ingredienser</strong>, og tryk på <strong>glas</strong>-ikonet i dens række.",
          "Vælg, hvordan den serveres: et mål (glas, shot, pint…), en anden mængde i milliliter eller hele beholderen.",
          "Tjek prisen pr. servering, hvor mange serveringer hver beholder giver, og den foreslåede pris; du kan skrive din egen pris.",
          "Tryk på <strong>Opret opskrift</strong>: den vises i Mine opskrifter og kan straks bruges i menuer, salg og teoretisk lager.",
        ]],
        ["formula", "Pris pr. servering", ["Pris pr. servering = Serverede milliliter × Pris pr. milliliter", "Serveringer pr. beholder = Brugbart indhold ÷ Serverede milliliter"], "Prisen pr. milliliter indeholder allerede ingrediensens svind. At sælge hele flasken koster præcis dens indkøbspris."],
        ["example", "Eksempel · et glas vin", [
          ["Flaske på 750 ml", "20.00"],
          ["Med 5 % svind er der", "712.5 ml"],
          ["Pris pr. milliliter", "0.028"],
          ["Glas på 150 ml", "4.21", true],
          ["Glas pr. flaske", "4.75"],
        ]],
        ["h3", "Optælling af baren"],
        ["p", "Når du registrerer lager pr. emballage, kan du bruge decimaler (2.3 flasker). I lagertabellen viser drikkevarer også beholdning, minimum og forskellen ved seneste optælling i flasker."],
        ["formula", "Tæl efter vægt", ["Åben andel = (Vægt − Tom) ÷ (Fuld − Tom)", "Beholdere = Uåbnede + Åben andel"], "Tryk på <strong>vægt</strong>-ikonet under optællingen. Du vejer kun én gang en uåbnet fuld flaske og en tom af samme produkt; de gemmes til fremtidige optællinger."],
        ["tip", "Hvad optællingen fortæller dig", "I en bar ender den faktiske omkostning ofte flere point over den teoretiske på grund af spild, overskænkning eller gratis drinks. Forskellen ved optællingen, i flasker, viser dig, hvor du skal kigge først."],
        ["h3", "Køkken og bar i Rapporter"],
        ["p", "Under Rapporter → Økonomi viser kortet <strong>Køkken vs. bar</strong> hvert områdes salg, andel af salget og teoretiske omkostning, samt den faktiske omkostning, hvis du har lavet en start- og en slutoptælling i perioden. Menu Engineering har et filter Alle / Køkken / Bar, så drinks sammenlignes med drinks og retter med retter."],
        ["info", "Plan", "Baropskrifter og »Sælg pr. glas«: alle planer. Svind: fra <strong>Home Cook</strong>. Lager: fra <strong>Chef de Partie</strong>. Køkken vs. bar i Økonomi: fra <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "inventario",
      title: "Lager",
      plan: "Plan Chef de Partie eller højere",
      intro: "Vid hvad du har, hvad der er ved at slippe op, og hvad dit lager er værd. Hver optælling gemmes som historik.",
      blocks: [
        ["figure", "07-inventario.jpg", "Lager: aktuel beholdning, minimum, status for hver vare og samlet værdi."],
        ["h3", "Status: normal, lav og kritisk"],
        ["p", "Hver vare har et <strong>minimum</strong>, som du selv sætter direkte i tabellen. Ud fra det markerer appen status:"],
        ["table", ["Status", "Hvornår den vises"], [
          ["Kritisk", "Beholdningen er lig med eller under minimum."],
          ["Lav", "Beholdningen er lig med eller under det dobbelte af minimum."],
          ["Normal", "Beholdningen er over det dobbelte af minimum, eller varen er endnu ikke talt."],
        ]],
        ["h3", "Registrer lager"],
        ["p", "»Registrer Lager« gemmer et øjebliksbillede af beholdningen og opdaterer de aktuelle mængder. Der er tre typer:"],
        ["cards", [
          ["Optælling", "Indledende Lager", "Det, du har ved starten af en vagt, en uge eller en måned."],
          ["Optælling", "Afsluttende Lager", "Det, der er tilbage ved periodens slutning, til sammenligning med den indledende optælling."],
          ["Tilgang", "Nyt Indkøb", "Varer, der lige er kommet, med den pris du betalte. Opdaterer dine opskrifters kostpris, hvis prisen har ændret sig."],
        ]],
        ["p", "Du kan tælle i basisenheden (f.eks. gram) eller pr. emballage (3 sække), og appen omregner. Pr. emballage kan du bruge decimaler: 2.3 flasker er 2 hele og 3 tiendedele af den åbne. Det er altid beholderens faktiske indhold, der tælles, også selvom ingrediensen har svind."],
        ["h3", "Dit lagers værdi"],
        ["formula", "Lagerværdi", ["Varens værdi = Beholdning × Beholderens pris ÷ Beholderens indhold", "Samlet værdi = Summen af alle varer"], "Beholdningen gemmes i ingrediensens enhed (ml, g…), og prisen gælder hele flasken, sækken eller kassen: derfor divideres med indholdet. Tre flasker på 750 ml til 20 er 60 værd."],
        ["p", "Ved hvert nyt indkøb fører appen også en <strong>vægtet gennemsnitspris</strong> som værdiansættelsesreference. Opskrifternes kalkulation bruger altid prisen fra det seneste indkøb."],
        ["tip", "Automatisk genberegning", "Ændrer et indkøb prisen på en ingrediens, genberegnes alle opskrifter og underopskrifter, der bruger den, og appen fortæller dig hvor mange."],
        ["h3", "Teoretisk lager: hvor meget der burde være tilbage"],
        ["p", "Ud over det optalte lager viser hver vare sit <strong>teoretiske lager</strong>: hvad der burde være tilbage ud fra de salg, du har registreret efter seneste optælling (manuelle, POS og fakturaer). Gastrometrics udfolder hvert salg via opskriften —inklusive underopskrifter og svind— og trækker det fra automatisk. Redigerer eller sletter du et salg, rettes tallet med det samme."],
        ["formula", "Teoretisk lager", ["Teoretisk lager = Seneste optælling + Modtagne indkøb − Forbrug fra salg"], "En solgt ret bruger én portion af sin opskrift; en solgt menu én portion af hver aktiv ret."],
        ["p", "Når du laver en ny optælling, ser du <strong>afvigelsen ved seneste optælling</strong>: det optalte minus det, teorien forventede. Er den negativ, er der gået mere ud, end opskrifterne forklarer (svind, spild, større portioner eller manko): så er det tid til at undersøge det."],
      ],
    },
    {
      id: "menus",
      title: "Menuer",
      plan: "Plan Chef de Partie eller højere",
      intro: "Saml dine opskrifter i serveringstrin til en menukort, en dagens ret eller et event, med gennemsnitspris og indkøbsordre.",
      blocks: [
        ["figure", "08-menus.jpg", "Menuer: hver menu med sine trin, aktive retter og gennemsnitspris."],
        ["h3", "Opret en menu i 4 trin"],
        ["steps", [
          "<strong>Oplysninger</strong>: navn, type (frokost, middag, brunch, buffet, smagsmenu, catering, særligt event eller andet), dato og antal gæster.",
          "<strong>Trin</strong>: Forret, Hovedret og Dessert som standard. Du kan omdøbe, fjerne eller tilføje flere.",
          "<strong>Retter</strong>: appen foreslår først de opskrifter, hvis »Trin« passer til hvert trin.",
          "<strong>Gennemgang</strong>: det fulde overblik med mulighed for at angive, hvor mange portioner af hver ret du skal bruge til den servering.",
        ]],
        ["tip", "Drikkekort", "Vælg typen <strong>Drikkekort</strong>, så skifter serveringerne til Cocktails, Vine, Øl og Alkoholfri drikke. Hver af dem foreslår opskrifterne med den tilsvarende barklassifikation (kapitel 6)."],
        ["p", "Hver ret kan have sin egen pris (ellers bruges prisen fra opskriftsarket) og kan midlertidigt slås fra uden at blive fjernet fra menuen."],
        ["formula", "Menuens gennemsnitspris", ["Gennemsnitspris = Summen af aktive retters priser ÷ Antal aktive retter"], "Retter, der er slået fra, tæller ikke med."],
        ["h3", "Eksport og indkøb"],
        ["p", "Fra hver menu kan du eksportere PDF'en til dine gæster eller den interne version med omkostninger (kapitel 12) eller generere indkøbsordren med alt, hvad der skal til for at lave den."],
      ],
    },
    {
      id: "compras",
      title: "Indkøbsordrer",
      intro: "Fortæl hver leverandør præcis hvad og hvor meget du har brug for: manuelt, fra en menu eller en opskrift, eller lad appen foreslå det ud fra dit lager.",
      blocks: [
        ["figure", "09-ordenes-compra.jpg", "Indkøbsordrer: det automatiske forslag ved lav beholdning og listen over ordrer med status."],
        ["h3", "Fire måder at oprette en ordre på"],
        ["list", [
          "<strong>Manuelt</strong>: søg efter hver ingrediens, og appen udfylder enhed, leverandør og pris.",
          "<strong>Foreslået ud fra lav beholdning</strong>: tjekker dit lager og laver ordren med alt, der er lavt eller kritisk.",
          "<strong>Fra en menu</strong>: alt, der skal til for at lave den, minus det du allerede har.",
          "<strong>Fra en opskrift</strong>: knappen »Generer Indkøbsordre« i Opskriftsark, allerede skaleret hvis du bruger PAX-modifikatoren.",
        ]],
        ["formula", "Foreslået mængde ved lav beholdning", ["Mængde at bestille = Den største af (2 × Minimum − Aktuel beholdning) og Minimum"], "Den fylder op til det dobbelte af dit minimum for at give dig luft og foreslår aldrig mindre end selve minimummet."],
        ["formula", "Ordrens total", ["Linjens kostpris = Mængde × Pris pr. enhed", "Total = Summen af linjer + Moms"], "Momsen er 0 % som standard og kan ændres. Har ingrediensen en emballage, fortæller ordren også hvor mange pakker du skal købe, rundet op."],
        ["h3", "Status og modtagelse"],
        ["chips", ["Afventer", "Godkendt", "Bestilt", "Modtaget", "Annulleret"]],
        ["p", "Du kan ændre status frit. Varerne grupperes efter leverandør (varer uden leverandør kommer sidst), så du kan ringe til hver enkelt med hele listen. Du kan også duplikere eller redigere en ordre."],
        ["tip", "»Modtaget« lægger til dit lager", "Når du markerer en ordre som modtaget, lægges mængderne automatisk til lageret for de varer, der har samme navn. Er der kommet noget andet end bestilt, så ret det ved at registrere det faktiske under <strong>Lager → Nyt Indkøb</strong>."],
        ["info", "Plan", "Manuelle ordrer er tilgængelige fra <strong>Home Cook</strong>; automatiske forslag fra <strong>Chef de Partie</strong>."],
      ],
    },
    {
      id: "ventas",
      title: "Salg og fakturaer",
      intro: "Registrér det, du sælger, for at sammenligne dine priser med virkeligheden: manuelt, ved at importere dit kassesystem (POS) eller ved at udstede fakturaer til dine kunder.",
      blocks: [
        ["figure", "10-ventas.jpg", "Salg: POS-import og manuel registrering samlet ét sted."],
        ["h3", "Registrér salg"],
        ["list", [
          "<strong>Manuel registrering</strong>: ideel, hvis du ikke har et POS. Vælg en opskrift eller en menu og den solgte mængde; appen beregner omsætning og kostpris.",
          "<strong>Importér dit POS</strong>: upload en .xlsx-, .xls-, .csv- eller .txt-fil. Du angiver én gang, hvilken kolonne der er ret, mængde, dato og pris, og gemmer det som en navngivet skabelon. Næste gang genkender appen den selv.",
        ]],
        ["tip", "Besværlige filer", "Appen genkender, om dine datoer står som dag/måned eller måned/dag (og lader dig rette det), og læser specialtegn korrekt fra ældre filer i Windows-format."],
        ["h3", "Fakturaer til dine kunder"],
        ["p", "Under fanen <strong>Fakturaer</strong> opretter du den faktura, du giver din kunde: vælg opskrifter eller menuer (eller skriv linjer manuelt) med automatisk nummerering, redigerbar moms, noter og din virksomheds logo på PDF'en. Hver faktura tæller automatisk som et salg i dine rapporter (uden moms)."],
        ["warn", "Ikke en officiel skattefaktura", "Gastrometrics-fakturaen indeholder ikke nummerering godkendt af nogen skattemyndighed. Tjek dit lands krav, før du bruger den som skattebilag."],
        ["h3", "Salgshistorik"],
        ["p", "Nederst på siden samler historikken alle dine salg (manuelle, POS og fakturaer), grupperet efter dag, uge, måned eller år, for det datointerval du vælger, med en knap til at eksportere den til PDF."],
        ["info", "Plan", "Fakturaer: fra <strong>Home Cook</strong>. Manuel registrering: fra <strong>Chef de Partie</strong>. POS-import: fra <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "reportes",
      title: "Rapporter",
      intro: "Her giver dine tal mening: hvilke opskrifter der tjener mest, hvad dit lager er værd, og hvordan det reelt går for din virksomhed.",
      blocks: [
        ["figure", "11-reportes.jpg", "Rapporter: overblik over virksomheden med nøgletal og grafer."],
        ["h3", "Overblik"],
        ["p", "Generelle tal, lagerværdi og varer med alarm, gennemsnitlig kostpris og margin, opskrifter pr. klassifikation, mest brugte ingredienser, opskrifterne med bedste og dårligste margin samt hver ingrediens' prishistorik med ændring."],
        ["h3", "Økonomi"],
        ["p", "Sælger du drikkevarer, adskiller kortet <strong>Køkken vs. bar</strong> salg, teoretisk og faktisk omkostning for hvert område (kapitel 6). Resultatopgørelse (P&L), din teoretiske mod reelle food cost ud fra dine salg, prisændringer pr. leverandør og <strong>Menu Engineering</strong>, som klassificerer hver ret ved at sammenligne den med gennemsnittet af din egen menu:"],
        ["table", ["Kategori", "Popularitet", "Margin", "Hvad du kan gøre"], [
          ["Stjerne", "Høj", "Høj", "Beskyt den, og fremhæv den på menuen."],
          ["Malkeko", "Høj", "Lav", "Den sælger godt: gennemgå kostprisen, eller hæv prisen lidt."],
          ["Puslespil", "Lav", "Høj", "God margin: promovér den, eller forbedr præsentationen."],
          ["Hund", "Lav", "Lav", "Overvej at lave den om eller fjerne den fra menuen."],
        ]],
        ["formula", "Vareforbrug (COGS)", ["COGS = Indledende lager + Indkøb − Afsluttende lager"], "For et præcist tal skal du have en indledende og en afsluttende optælling i perioden."],
        ["info", "Plan", "Overblik: fra <strong>Chef de Partie</strong>. Økonomi: fra <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "pdfs",
      title: "PDF-dokumenter",
      intro: "Hvert dokument er lavet til den, der skal læse det: dit køkken, din ledelse, din leverandør eller din kunde. Omkostninger blandes aldrig ind i dokumenter til udenforstående.",
      blocks: [
        ["h3", "De 8 dokumenter"],
        ["table", ["Dokument", "Til hvem", "Hvad det indeholder"], [
          ["Opskriftsark · Administrativt", "Ejer og ledelse", "Ingredienser med kostpris, poster, grafer, margin og food cost."],
          ["Opskriftsark · Køkken", "Dit køkkenteam", "Ingredienser, mængder, billede og fremgangsmåde uden tal om penge."],
          ["Opskriftsark · Hurtigt", "Leverandører eller partnere", "Det væsentlige i opskriften uden omkostninger eller priser."],
          ["Lager", "Administration", "Samlet værdi, værdi pr. kategori, vigtigste varer og status."],
          ["Menu · Gæst", "Dine gæster", "Et elegant menukort uden omkostningstal."],
          ["Menu · Intern", "Ejer", "Kostpris, pris og margin pr. ret med grafer."],
          ["Indkøbsordre", "Leverandører", "Ingredienser pr. leverandør, mængder og total."],
          ["Faktura", "Din kunde", "Dit logo, kundeoplysninger, linjer, moms og total."],
        ]],
        ["p", "Opskriftsark og gæstemenuen viser hver rets allergener, beregnet ud fra ingredienserne i det øjeblik, du eksporterer (kapitel 3)."],
        ["tip", "Automatiske advarsler", "Det administrative ark advarer dig øverst, hvis kostprisen overstiger salgsprisen, eller hvis udbyttet ser forkert indtastet ud, før du udskriver et mærkeligt tal."],
        ["p", "PDF'erne kommer på det sprog, du har valgt i appen, bruger din valuta og har din virksomheds logo og temafarve."],
        ["info", "Plan", "Køkkenarket er med i alle planer. Det administrative ark fra <strong>Home Cook</strong>."],
      ],
    },
    {
      id: "equipo",
      title: "Team",
      plan: "Plan Sous Chef eller højere",
      intro: "Invitér dit team til at arbejde sammen med dig i Gastrometrics, hver med adgang til kun det, de har brug for.",
      blocks: [
        ["h3", "Invitér en person"],
        ["p", "Under <strong>Team</strong> skriver du personens e-mail. Vedkommende får en invitation og opretter sin egen konto; dit abonnement dækker adgangen. Med Sous Chef kan du tilføje 1 person og med Chef Ejecutivo op til 4 (hver plans brugere inkluderer dig). Der er ingen faste roller: for hver person indstiller du tre ting hver for sig."],
        ["table", ["Indstilling", "Muligheder"], [
          ["Omfang", "Alle dine virksomheder eller kun én bestemt."],
          ["Værktøjer", "Uafhængige felter: opskrifter, ingredienser, svind, manuelle og automatiske ordrer, lager, menuer, rapporter, salg, økonomi og administration af teamet."],
          ["PDF", "Ingen, køkken (uden omkostninger) eller administrativ (med omkostninger)."],
        ]],
        ["tip", "Forhåndsvisning", "Slå forhåndsvisning til for at se appen præcis som den person ville se den, med de samme rettigheder."],
        ["p", "Rettighederne håndhæves reelt, ikke kun på skærmen: en person uden adgang til et værktøj kan hverken se eller gemme de data. Er noget låst, forklarer appen, om det skyldes kontoens plan, eller at ejeren har begrænset det."],
      ],
    },
    {
      id: "planes",
      title: "Planer og abonnement",
      intro: "Du starter gratis og opgraderer, når du har brug for det. Dine data går aldrig tabt, når du skifter plan.",
      blocks: [
        ["table", ["Plan", "Pris", "Virksomheder", "Brugere (inkl. dig)", "Tilføjer"], [
          ["Foodie", "Gratis", "1", "1", "Opskrifter, ingredienser og køkkenark som PDF (med i alle planer)."],
          ["Home Cook", "$15 / md.", "1", "1", "Svind, manuelle indkøbsordrer, administrativt ark og fakturaer."],
          ["Chef de Partie", "$35 / md.", "1", "1", "Lager, menuer, foreslåede ordrer, Rapporter · Overblik og manuel salgsregistrering."],
          ["Sous Chef", "$70 / md.", "2", "2", "Rapporter · Økonomi, P&L, Menu Engineering, POS-import og Team (dig + 1 person)."],
          ["Chef Ejecutivo", "$120 / md.", "5", "5", "Team på op til 4 personer ud over dig. Tilgængelig for virksomheder efter aftale."],
        ]],
        ["figure", "12-mi-plan.jpg", "Min plan: din nuværende plan, hvad den indeholder, og hvordan du administrerer dit abonnement."],
        ["h3", "Betal, skift eller opsig"],
        ["p", "Betalinger behandles af Stripe. Under <strong>Min plan</strong> kan du skifte plan eller åbne betalingsportalen for at opdatere dit kort eller opsige. Ændringer vises automatisk på din konto, og du får en bekræftelse på e-mail."],
        ["p", "Hver gang din plan ændres —fordi du selv ændrede den, fordi Gastrometrics-teamet justerede den, eller fordi en tildelt plan udløb— får du besked på e-mail og i et vindue, når du åbner Dashboardet, med en præcis liste over, hvad du <strong>får</strong>, hvad du <strong>mister</strong>, og hvad din plan nu omfatter. Mister du adgang til en sektion, slettes dine data ikke: de bliver tilgængelige igen, hvis du opgraderer senere."],
        ["p", "Opsiger du, beholder du fuld adgang til slutningen af den periode, du allerede har betalt for. Min plan viser dig den præcise dato."],
        ["info", "Når noget er låst", "Du ser en hængelås og en knap til Min plan. Bruger du appen som en del af et team, fortæller beskeden, at det er kontoens ejer, der styrer den adgang."],
      ],
    },
    {
      id: "config",
      title: "Indstillinger, sprog og e-mails",
      intro: "Tilpas appen, vælg sprog og valuta, bestem hvilke e-mails du vil have, og administrér dine kontodata.",
      blocks: [
        ["figure", "13-configuracion.jpg", "Indstillinger → Notifikationer, hvor du vælger, om du vil modtage nyheder og påmindelser."],
        ["h3", "Fanerne i Indstillinger"],
        ["list", [
          "<strong>Profil</strong>: navn, e-mail (ændring kræver din nuværende adgangskode), land og virksomhedstype.",
          "<strong>Udseende</strong>: lyst, mørkt eller efter dit system.",
          "<strong>Regional</strong>: land, valuta og sprog.",
          "<strong>Notifikationer</strong>: om du vil modtage nyheder og påmindelser via e-mail.",
          "<strong>Konto</strong>: sikkerhedskopi af dine data, juridiske dokumenter, slet indhold og slet kontoen.",
        ]],
        ["h3", "Sprog og valuta"],
        ["p", "Appen findes på <strong>spansk, engelsk, dansk, fransk, portugisisk og kinesisk</strong>. Det sprog, du vælger, bruges i hele brugerfladen, i dine PDF'er og i <strong>alle e-mails</strong>, vi sender dig. Der er 21 valutaer; skifter du valuta, ændres symbol og format, men dine beløb omregnes ikke. Decimaler skrives altid med punktum."],
        ["h3", "E-mails du kan modtage"],
        ["p", "Du får altid e-mails om din konto: bekræftelse, adgangskode, betalinger og teaminvitationer. Slår du <strong>Nyheder og påmindelser</strong> til, skriver vi også, når der er nye funktioner, og hvis du ikke har været logget ind i nogle dage, en nyttig påmindelse ud fra det, du sidst lavede:"],
        ["cards", [
          ["Påmindelse", "Ufærdig opskrift", "Din kladde i Opskriftsark venter på dig, før de 24 timer er gået."],
          ["Påmindelse", "Lager og rapporter", "Når der er gået en uge siden din seneste optælling, eller siden du så dine rapporter."],
          ["Påmindelse", "Priser og comeback", "Hvis dine priser ikke er opdateret i over 30 dage, eller hvis du ikke har været inde længe."],
        ]],
        ["p", "Og når din konto har noget konkret at fortælle dig, skriver vi med tallet:"],
        ["cards", [
          ["Hver mandag", "Ugentlig oversigt", "Dine nøgletal: gennemsnitlig food cost, lagerværdi, varer under minimum og retter med lav margin."],
          ["Advarsel", "Lavt lager og margin", "Hvis en vare når sit minimum, eller en ret ikke længere når sit food cost-mål."],
          ["Team", "Invitationer og virksomheder", "Hvis din inviterede ikke er logget ind, eller en ny virksomhed stadig ikke har opskrifter."],
          ["Milepæle", "Fremskridt og din plan", "Når du når 10, 25 eller 50 opskrifter, og hvis din plan omfatter noget, du ikke har prøvet endnu."],
        ]],
        ["p", "Vi sender aldrig mere end én påmindelse med få dages mellemrum. Hver e-mail har et link til at afmelde med ét klik, eller du kan fjerne fluebenet under Indstillinger → Notifikationer."],
        ["h3", "Dine data"],
        ["list", [
          "<strong>Download sikkerhedskopi</strong>: én fil med alt dit indhold (opskrifter, ingredienser, menuer og mere).",
          "<strong>Slet alt indhold</strong>: tømmer din konto, men holder den aktiv. Du skriver din e-mail for at bekræfte.",
          "<strong>Slet konto</strong>: opsiger dit abonnement og sletter alt permanent. Den beder også om din e-mail som bekræftelse.",
        ]],
        ["warn", "Ingen vej tilbage", "Sletning af indhold eller konto kan ikke fortrydes. Download din sikkerhedskopi først."],
      ],
    },
    {
      id: "formulas",
      appendix: "A",
      title: "Formler i overblik",
      intro: "Alle manualens formler på én side til hurtigt opslag.",
      blocks: [
        ["table", ["Begreb", "Sådan beregnes det"], [
          ["Pris pr. enhed", "Indkøbspris ÷ Nettoindhold"],
          ["Med svind", "Indkøbspris ÷ (Nettoindhold × (1 − svind %))"],
          ["Linjens kostpris", "Mængde × Pris pr. enhed"],
          ["Produktionsomkostning", "Summen af linjer (× PAX-faktor hvis aktiv)"],
          ["Enhedskostpris", "Produktionsomkostning ÷ Udbytte"],
          ["Pris · 6 poster", "Enhedskostpris + Sum af poster ÷ Udbytte, rundet op til din valutas trin"],
          ["Pris · Food Cost %", "Enhedskostpris ÷ Mål i %, rundet op til din valutas trin"],
          ["Pris med provision", "Pris uden provision ÷ (1 − Provision i %)"],
          ["Fast omkostning pr. ret", "Faste udgifter pr. måned ÷ Forventede retter pr. måned"],
          ["Samlet salg", "Endelig pris × Udbytte"],
          ["Dækningsbidrag", "(Samlet salg − Produktionsomkostning) ÷ Samlet salg"],
          ["Kostpris %", "Produktionsomkostning ÷ Samlet salg"],
          ["Forbrugsomkostning (underopskrift)", "Samlet kostpris ÷ Udbytte"],
          ["Lagerstatus", "Kritisk hvis beholdning ≤ minimum · Lav hvis beholdning ≤ 2 × minimum"],
          ["Lagerværdi", "Summen af (Beholdning × Beholderens pris ÷ Beholderens indhold)"],
          ["Teoretisk lager", "Seneste optælling + Modtagne indkøb − Forbrug fra salg"],
          ["Pris på en drik", "Pris pr. servering ÷ Mål for pour cost"],
          ["Pris pr. servering", "Serverede milliliter × Pris pr. milliliter (med svind)"],
          ["Serveringer pr. beholder", "Brugbart indhold ÷ Serverede milliliter"],
          ["Tæl efter vægt", "Uåbnede + (Vægt − Tom) ÷ (Fuld − Tom)"],
          ["Foreslået mængde", "Den største af (2 × Minimum − Beholdning) og Minimum"],
          ["Ordrens total", "Summen af linjer + Moms"],
          ["Menuens gennemsnitspris", "Summen af aktive retter ÷ Antal aktive retter"],
          ["COGS", "Indledende lager + Indkøb − Afsluttende lager"],
        ]],
      ],
    },
    {
      id: "problemas",
      appendix: "B",
      title: "Ofte stillede spørgsmål",
      intro: "De mest almindelige »det gør ikke, hvad jeg forventede«-situationer med årsag og løsning.",
      blocks: [
        ["table", ["Hvis det sker…", "Hvad du skal tjekke"], [
          ["En opskrifts kostpris bliver enorm eller absurd.", "Tjek udbyttet og hver ingrediens' enhed. Bruger du underopskrifter, så sørg for, at mængden er i gram eller milliliter og ikke stk."],
          ["Jeg ændrede en pris, og mine opskrifter flyttede sig ikke.", "Genberegningen sker med det samme. Tjek, at opskriften bruger præcis den ingrediens og ikke en dublet med et lignende navn."],
          ["Jeg kan ikke se et modul (Lager, Økonomi, Team…).", "Din plan indeholder det ikke, eller kontoens ejer har ikke givet dig adgang. Beskeden på skærmen fortæller hvilken."],
          ["Jeg markerede en ordre som »Modtaget«, og en vare blev ikke lagt til.", "Kun varer, hvis navn præcis matcher en vare på lageret, lægges til. Registrér varen under Lager → Nyt Indkøb."],
          ["Jeg gemte en opskrift med PAX aktiv ved en fejl.", "Brug »Gendan original opskrift«, og gem igen."],
          ["Jeg forlod Opskriftsark uden at gemme.", "Gå tilbage til Opskriftsark inden for 24 timer: din opskrift kommer tilbage af sig selv."],
          ["Mine e-mails kommer på et andet sprog.", "Skift sprog under Indstillinger → Regional, mens du er logget ind; de næste e-mails kommer på det sprog."],
          ["Jeg vil ikke have påmindelser.", "Brug linket »Stop med at modtage disse e-mails«, eller fjern fluebenet under Indstillinger → Notifikationer."],
          ["Min drink får en meget høj pris.", "Tjek, at klassifikationen er en »Bar«-klassifikation: så bruger prisen pour cost i stedet for en rets 6 poster."],
        ]],
        ["p", "Har du et andet spørgsmål eller et forslag? Skriv til os fra <strong>Forslag og fejlrapporter</strong> nederst i Indstillinger. Vi læser hver besked."],
      ],
    },
  ],
}
