// User manual — English. Must mirror content/es.mjs block by block (checked by scripts/build.mjs).
export default {
  ui: {
    manualName: "User manual",
    contents: "Contents",
    contentsLede: "If this is your first time, read chapter 1 and then jump straight to what you need: every chapter stands on its own.",
    inThisChapter: "In this chapter",
    figure: "Figure",
    coverKicker: "User manual",
    coverTitle: "Cost, sell and grow with Gastrometrics",
    coverLede: "The complete guide to turning your recipes into fair prices, keeping your inventory under control and understanding the numbers behind your kitchen.",
    coverModules: ["Ingredients", "Recipe Sheet", "Inventory", "Menus", "Purchase Orders", "Sales", "Reports", "Team"],
    edition: "September 2026 edition",
  },
  chapters: [
    {
      id: "bienvenida",
      title: "Welcome to Gastrometrics",
      intro: "Gastrometrics turns your recipes into clear numbers: what each dish costs you, what to sell it for and how much it leaves you. This chapter shows you the big picture and the fastest path to your first result.",
      blocks: [
        ["h3", "What Gastrometrics does for you"],
        ["p", "You enter your ingredients with what you pay for them, build your recipes with the quantities you use, and the app works out the <strong>real cost of every dish</strong>, suggests a <strong>selling price</strong> and shows your <strong>margin</strong>. From there, everything else —inventory, menus, purchasing, sales and reports— uses those same numbers, so you never have to type them twice."],
        ["h3", "How the modules connect"],
        ["flow", [
          ["Ingredients", "price and shrinkage"],
          ["Recipes", "cost and price"],
          ["Menus", "menus and events"],
          ["Purchasing", "supplier orders"],
          ["Sub-recipes", "become ingredients again"],
          ["Inventory", "stock and counts"],
          ["Sales", "manual, POS, invoices"],
          ["Reports", "real margin and P&L"],
          "Solid arrow = automatic · dashed arrow = you record it (a count or a purchase)",
        ]],
        ["p", "<strong>Recipes</strong> are at the center: they read your ingredient prices and feed menus, purchase orders and reports. Change an ingredient's price and every recipe that uses it recalculates on its own."],
        ["h3", "Your first 10 minutes"],
        ["steps", [
          "<strong>Add 3 or 4 ingredients</strong> in Ingredients, with their purchase price and net content. You don't need your full inventory to get started.",
          "<strong>Create your first recipe</strong> in the Recipe Sheet: pick those ingredients and enter the quantity you use of each.",
          "<strong>See the result</strong>: production cost, suggested price and margin appear on the same screen, in real time.",
          "<strong>Save and export</strong> the sheet as a PDF for your kitchen or your accountant.",
          "<strong>Carry on whenever you like</strong> with inventory, menus or purchasing. They aren't required to see your first price.",
        ]],
        ["tip", "Rather see an example first?", "If you don't have any recipes yet, the Dashboard offers <strong>“See an example first”</strong>: it creates a sample recipe with its cost and price already calculated so you can see how it works. You can delete it anytime."],
        ["h3", "How to read this manual"],
        ["cards", [
          ["", "Tip", "Shortcuts and good habits that save you time."],
          ["", "Important", "Details worth knowing before you press a button."],
          ["", "Plan", "Features that depend on your subscription plan (chapter 14)."],
        ]],
      ],
    },
    {
      id: "cuenta",
      title: "Your account and businesses",
      intro: "Everything in Gastrometrics belongs to a business. Here you'll see how to sign up, create businesses, move between them and make the most of the Dashboard.",
      blocks: [
        ["h3", "Creating your account"],
        ["p", "Sign-up is a 5-step wizard: your details and password, your professional information (country, currency, business type and size), the <strong>plan</strong> you want, acceptance of the terms, and a final summary. If you arrive from the pricing page with a plan already chosen, it comes preselected."],
        ["p", "The last step has an optional box to <strong>receive updates and reminders by email</strong>. It starts unchecked and you can change it anytime in Settings (chapter 15)."],
        ["h3", "Creating a business"],
        ["steps", [
          "<strong>Basics and logo.</strong> Name, description, business type and, if you like, a logo that will appear in the header of your PDFs.",
          "<strong>Monthly fixed costs.</strong> Rent, utilities, staff, marketing and others. They're used to spread your fixed costs into the price of each dish (chapter 4).",
          "<strong>Default pricing method.</strong> “Gastrometrics” (6 cost items) or “Food Cost %”. Every new recipe inherits it, and you can change it recipe by recipe.",
        ]],
        ["chips", ["Restaurant", "Coffee shop", "Bakery", "Pastry shop", "Food Truck", "Catering", "Bar", "Pizzeria", "Fast Food", "Other"]],
        ["p", "Each business has its own ingredients, recipes, inventory, menus and purchasing: nothing mixes between businesses. Inside each business panel you can choose from 12 theme colors, which also color the accents of its PDFs."],
        ["h3", "Switching between businesses"],
        ["p", "<strong>Businesses</strong> shows one card per business with an “Open” button. While you work in any module, the side menu also lists your businesses so you can jump between them without going back to the start."],
        ["h3", "The Dashboard"],
        ["figure", "01-dashboard.jpg", "The Dashboard: what needs your attention today, your key figures and shortcuts to every module."],
        ["list", [
          "<strong>What to do today</strong>: ingredients below their minimum, recipes without a selling price and your average margin. Each card takes you straight to where you can fix it.",
          "<strong>Key figures</strong>: total recipes, ingredients, businesses and average cost, across all your businesses.",
          "<strong>Quick actions</strong>: one shortcut per module so you can jump in without the side menu.",
        ]],
        ["h3", "The side menu"],
        ["table", ["Section", "What it's for"], [
          ["Dashboard", "An overview of your whole account and what needs attention."],
          ["Recipe Sheet", "Create or edit a recipe, with its cost and price."],
          ["My Recipes", "Search, duplicate, move and recover recipes."],
          ["Ingredients", "Your ingredient database, prices and shrinkage."],
          ["Inventory", "Stock, counts and minimum-level alerts."],
          ["Team", "Invite people and give them permissions."],
          ["Menus", "Build menus by course for service or events."],
          ["Purchase Orders", "Supplier orders, by hand or suggested."],
          ["Sales", "Record sales, import your POS and issue invoices."],
          ["Reports", "Business overview and finances."],
          ["Businesses", "Create, open and delete businesses."],
        ]],
        ["info", "Settings and My Plan", "Settings isn't a page: it's a window you open from any screen with the gear icon. Your plan and subscription live in <strong>My Plan</strong>, at the bottom of the menu."],
      ],
    },
    {
      id: "ingredientes",
      title: "Ingredients",
      intro: "Your ingredients are the foundation of all costing. If their prices are up to date, so are your recipes, menus and reports.",
      blocks: [
        ["figure", "02-ingredientes.jpg", "The business's ingredient database, with category, unit, price and supplier."],
        ["h3", "What an ingredient contains"],
        ["p", "Name, category, unit of measure, supplier, purchase pack (optional) and its price: what you pay for the whole pack and how much it contains. From that the app calculates the <strong>price per unit</strong>, which is what your recipes actually use."],
        ["formula", "Price per unit", ["Price per unit = Purchase price ÷ Net content"], "Net content is in the ingredient's base unit (grams, milliliters, units…)."],
        ["example", "Example · a sack of flour", [
          ["Purchase price of the sack", "450.00"],
          ["Net content", "25000 g"],
          ["Price per gram", "0.018", true],
          ["A recipe using 300 g costs", "300 × 0.018 = 5.40"],
        ]],
        ["h3", "Categories and units"],
        ["p", "Categories are a fixed list of 40 (Poultry, Beef, Fish, Dairy, Flour, Spices, Beverages, Spirits, Wine, Beer, Soft drinks & mixers, Disposables…), plus a special one, <strong>Sub-recipe / production</strong>, assigned automatically to preparations you use as an ingredient (chapter 5). The available units are:"],
        ["chips", ["Grams", "Kilograms", "Milliliters", "Liters", "Ounces", "Fluid ounces", "Pounds", "Gallons", "Unit"]],
        ["p", "Use <strong>Unit</strong> for items you count (eggs, cans, bread rolls). The app treats them specially, for example to warn you if a recipe's yield looks too low."],
        ["tip", "Don't forget packaging", "Cups, takeout boxes, bags, napkins or straws are part of each dish's cost too. Add them as ingredients in the <strong>Disposables</strong> category (for example, a pack of 100 boxes, by unit) and put them in the recipe of what you sell to go. Otherwise your price won't cover them."],
        ["h3", "Purchase packs"],
        ["p", "If you buy by the Box, Sack, Bottle, Can, Bag or Jar, save how much each pack contains. That way your purchase orders say “4 boxes” instead of a quantity in grams nobody would order."],
        ["h3", "Importing from Excel"],
        ["p", "You can load or export your whole database in Excel with a template the app generates from its real categories and units. Column headers are recognized in all 6 app languages."],
        ["h3", "Shrinkage"],
        ["p", "Shrinkage is what you pay for but can't use: peels, bones, trimmings, evaporation. In <strong>Manage Shrinkage</strong> you switch the system on and, for each ingredient, choose the typical percentage for its category or your own (or a fixed amount)."],
        ["formula", "Real cost with shrinkage", ["Usable content = Net content × (1 − shrinkage %)", "Price per unit = Purchase price ÷ Usable content"], "You pay for all of it but only use part, so the real price per unit goes up. Turn shrinkage off and everything returns to the original values."],
        ["p", "Some typical percentages by category: Seafood 63 %, Fish 52 %, Beef 33 %, Poultry 27 %, Fruit 24 %, Vegetables 21 %. Dry and packaged goods start at 0 %. Bar categories have their own typical shrinkage: spirits 2 %, wine 5 %, draft beer 18 % and bottled beer 0 % (chapter 6)."],
        ["info", "Plan", "Shrinkage management is available from the <strong>Home Cook</strong> plan."],
        ["h3", "Allergens"],
        ["p", "In the last step of each ingredient you tick which of the 14 allergens that must be declared it contains (gluten, milk, eggs, tree nuts, soy, fish, crustaceans, sesame…). Recipes that use it —also through their sub-recipes— show them automatically in the Recipe Sheet, in the recipe's three PDFs and under each dish on the customer menu. They're never typed into the recipe by hand, so they don't go out of date."],
        ["h3", "Deleting an ingredient"],
        ["p", "Before you confirm, the app shows which recipes use it. It won't stop you, but you'll know which recipes will be left with a missing ingredient."],
      ],
    },
    {
      id: "ficha",
      title: "Recipes and the Recipe Sheet",
      intro: "The heart of Gastrometrics: you turn a list of ingredients into an exact cost and a well-founded selling price, always seeing where each number comes from.",
      blocks: [
        ["figure", "03-ficha-tecnica.jpg", "A recipe open in the Recipe Sheet: general details, ingredients and cost calculation."],
        ["h3", "Filling in the sheet"],
        ["list", [
          "<strong>Name</strong> and <strong>Classification</strong> (22 options, from Hot line to Pastry or R&D). The “Sub-recipe” classification turns the recipe into an ingredient (chapter 5). The 5 “Bar · …” classifications calculate the price with pour cost (chapter 6).",
          "<strong>Course</strong>: where it goes in service (starter, main, dessert…).",
          "<strong>Yield</strong>: how much the recipe makes (8 portions, 1200 g…) with its unit.",
          "<strong>Ingredients</strong>: search your database and enter the quantity. Each line shows what it costs.",
          "<strong>Procedure and notes</strong>, plus a <strong>photo</strong> of the dish.",
        ]],
        ["tip", "Move on with Enter", "In the first fields, pressing Enter takes you to the next one, so you can fill in the sheet almost without touching the mouse."],
        ["h3", "Your progress is saved for 24 hours"],
        ["p", "While you create a new recipe, Gastrometrics keeps an <strong>automatic draft</strong>. If you close the tab, lose your connection or go to another module, coming back to the Recipe Sheet brings the recipe back exactly as you left it, with a notice at the top. The draft lasts <strong>24 hours from your last change</strong> and is also there if you sign in from another device."],
        ["figure", "05-borrador.jpg", "When you come back, a notice confirms your recipe was recovered. “Clear sheet” leaves it blank."],
        ["p", "Want to start from scratch? Use <strong>Clear sheet</strong> (next to “Save Recipe” or in the notice). It asks for confirmation and erases everything: name, ingredients, procedure, photo, prices and the saved draft. Saving the recipe deletes the draft automatically."],
        ["h3", "Production cost"],
        ["formula", "Cost of each ingredient and of the recipe", ["Line cost = Quantity × Price per unit", "Production cost = Sum of all lines"]],
        ["formula", "Unit cost", ["Unit cost = Production cost ÷ Yield"], "If you don't enter a yield, the app estimates it from the total weight of ingredients measured in g, ml, kg or liters."],
        ["h3", "Two ways to calculate the price"],
        ["p", "Each recipe uses one of two methods. Your business sets the default, but you can change it recipe by recipe without losing anything: both start from the same real cost."],
        ["cards", [
          ["Method 1", "Gastrometrics (6 cost items)", "Spreads your profit across six items, each a percentage of production cost: utilities 10 %, marketing 10 %, operating costs 30 %, labor 25 %, tax 0 % and net profit 30 % (all editable)."],
          ["Method 2", "Food Cost %", "You choose what share of the price the ingredient cost should represent (usually 28 % to 35 %) and the price is worked out from there. It's the industry standard."],
        ]],
        ["formula", "Suggested selling price", ["6 cost items: Price = Unit cost + (Sum of items ÷ Yield)", "Food Cost: Price = Unit cost ÷ Target %"], "In both cases the price is rounded <strong>up</strong> to your currency's step: to 5 in lempiras (61 becomes 65, never 60), to 0.50 in dollars or euros (10.60 becomes 11.00), to 100 in colones. It's the only rounding in the calculation. The example below is in lempiras."],
        ["example", "Example · same cost, two methods (unit cost 20, yield 1)", [
          ["6 items: 2 + 2 + 6 + 5 + 0 + 6", "21"],
          ["20 + 21 = 41 → rounded", "45", true],
          ["Food Cost 30 %: 20 ÷ 0.30 = 66.67 → rounded", "70", true],
        ]],
        ["p", "If your business has fixed costs and an estimate of dishes per month, their proportional share is added to the price automatically as one more item:"],
        ["formula", "Fixed cost per dish", ["Fixed cost per dish = Monthly fixed costs ÷ Estimated dishes per month"]],
        ["h3", "Delivery or card commission"],
        ["p", "If you sell through a delivery app or take card payments, enter in the recipe the <strong>commission %</strong> they keep from the price. The suggested price covers it, and the sheet shows the commission per unit and what you keep after paying it. Profit and margin already deduct it."],
        ["formula", "Price with commission", ["Price = Price without commission ÷ (1 − Commission %)"], "It works with both methods and is rounded afterwards, as always."],
        ["example", "Example · unit cost 20, Food Cost 30 %, commission 30 % (in lempiras)", [
          ["Price without commission: 20 ÷ 0.30", "66.67"],
          ["66.67 ÷ (1 − 0.30) = 95.24 → rounded", "100", true],
          ["The app keeps 30 %", "30"],
          ["You keep per dish", "70", true],
        ]],
        ["figure", "04-ficha-tecnica-precio.jpg", "The selling-price calculation with the recipe's chosen method, followed by the cost summary."],
        ["h3", "Margins and manual prices"],
        ["formula", "Recipe indicators", ["Total sales = Final price × Yield", "Contribution margin = (Total sales − Production cost) ÷ Total sales", "Cost % = Production cost ÷ Total sales"]],
        ["p", "The suggested price is never mandatory: you can type your own <strong>selling price</strong> or your own <strong>unit profit</strong>. Margins recalculate with your number, but cost always reflects what you really pay."],
        ["h3", "Scaling with the PAX modifier"],
        ["p", "Enter how many people you want to serve and the app scales every quantity and cost instantly, always rounding <strong>up</strong> so you never fall short. It's a preview: the saved recipe doesn't change."],
        ["list", [
          "<strong>Export PDF</strong> or <strong>Generate Purchase Order</strong> with PAX active uses the scaled quantities, without saving anything. The button warns you “Scaled to N”.",
          "<strong>Saving</strong> with PAX active asks for confirmation: the recipe is stored at the new size and the previous size is kept as the “original”.",
          "<strong>Restore original recipe</strong> goes back to that original size. Then press Save to confirm it.",
        ]],
        ["warn", "Suspicious yield", "If any ingredient measured in “units” is 20 times the declared yield or more (for example, 200 eggs for a yield of 1), you'll see a yellow warning in the sheet and in the PDF. It doesn't block anything: it just helps you catch a typo."],
        ["h3", "My Recipes: duplicate, move and trash"],
        ["figure", "06-mis-recetas.jpg", "My Recipes: all your recipes with their cost, yield and quick actions."],
        ["list", [
          "<strong>Duplicate</strong> creates a copy in the same business, with “(copy)” in the name.",
          "<strong>Migrate</strong> copies the recipe to another of your businesses. It asks whether to bring its ingredients and sub-recipes too (reusing those that already exist there) or just the recipe: in that case its sheet opens in the business so you pick the ingredients from its own database (those with the same name are linked automatically).",
          "<strong>Delete</strong> sends it to the <strong>trash</strong>, where you can recover it for 30 days before it's removed automatically.",
        ]],
      ],
    },
    {
      id: "subrecetas",
      title: "Sub-recipes",
      intro: "A base sauce, a stock or a dough you use in many dishes. You create it once and use it like any other ingredient.",
      blocks: [
        ["h3", "Creating a sub-recipe"],
        ["p", "Create the recipe as usual and give it the classification <strong>“Sub-recipe / production (Mise en place)”</strong>. When you save it, Gastrometrics creates an ingredient with the same name that you can search for and add to any other recipe sheet."],
        ["formula", "Cost of use", ["Cost of use = Total cost of the sub-recipe ÷ Yield"], "It's what each unit of the preparation costs (each gram of sauce, for example) when you use it in another recipe."],
        ["h3", "What's different in a sub-recipe"],
        ["p", "Since it isn't sold on its own, it has no selling price, cost items or margins. Its summary shows just three figures: <strong>production cost</strong>, <strong>yield</strong> and <strong>cost of use</strong>."],
        ["h3", "Everything updates in a chain"],
        ["p", "If an ingredient in your base sauce goes up, its cost of use recalculates and the change reaches every dish that uses it automatically. You don't have to open a single recipe."],
        ["warn", "Watch the quantities", "Cost of use is usually per gram or milliliter. If you type “150” thinking of units instead of grams, the dish's cost shoots up. Check the unit before saving."],
      ],
    },
    {
      id: "barra",
      title: "Bar and drinks",
      intro: "Wine, beer, cocktails and non-alcoholic drinks are costed just like food: they're ingredients and recipes with a few bar adjustments. There's no separate module to learn.",
      blocks: [
        ["h3", "Drinks as ingredients"],
        ["p", "Enter each bottle, can or keg as an ingredient, in milliliters or liters, with its price and content. There are bar categories of their own, each with its typical shrinkage (spills, bottom of the bottle, foam):"],
        ["table", ["Category", "Typical shrinkage", "Served as"], [
          ["Spirits", "2 %", "Shot 45 ml, double 90 ml, bottle"],
          ["Wine", "5 %", "Glass 150 or 125 ml, carafe 500 ml, bottle"],
          ["Draft beer", "18 %", "Pint 473 ml, half liter, glass 330 ml"],
          ["Bottled beer", "0 %", "Whole bottle or can"],
          ["Soft drinks & mixers", "2 %", "Whole container or glass 250 ml"],
        ]],
        ["h3", "Cocktails in the Recipe Sheet"],
        ["p", "A cocktail is a recipe with its lines in milliliters. When you pick a <strong>Bar · …</strong> classification, the price is calculated with <strong>pour cost</strong>: the share of the price that is product cost. That target belongs to that recipe only: it doesn't change your dishes' target."],
        ["table", ["Classification", "Default pour cost", "Typical range"], [
          ["Bar · Cocktails", "20 %", "15–22 %"],
          ["Bar · Wine", "30 %", "25–35 %"],
          ["Bar · Beer", "24 %", "20–28 %"],
          ["Bar · Non-alcoholic", "15 %", "10–20 %"],
          ["Bar · Coffee & tea", "20 %", "15–25 %"],
        ]],
        ["formula", "Price of a drink", ["Price = Cost per serving ÷ Target pour cost"], "It's rounded up to your currency's step, like any suggested price."],
        ["example", "Example · gin and tonic (in dollars)", [
          ["Gin, 45 ml", "1.69"],
          ["Tonic, 150 ml", "0.55"],
          ["Lime", "0.10"],
          ["Cost of the drink", "2.34", true],
          ["2.34 ÷ 0.22 = 10.64 → rounded", "11.00", true],
        ]],
        ["h3", "Sell by the glass or bottle"],
        ["steps", [
          "In <strong>Ingredients</strong>, find the drink and tap the <strong>glass</strong> icon on its row.",
          "Choose how it's served: a measure (glass, shot, pint…), another amount in milliliters or the whole container.",
          "Check the cost per serving, how many servings each container gives and the suggested price; you can type your own price.",
          "Tap <strong>Create recipe</strong>: it appears in My Recipes and can be used right away in menus, sales and theoretical stock.",
        ]],
        ["formula", "Cost per serving", ["Cost per serving = Milliliters served × Price per milliliter", "Servings per container = Usable content ÷ Milliliters served"], "The price per milliliter already includes the ingredient's shrinkage. Selling the whole bottle costs exactly its purchase price."],
        ["example", "Example · glass of wine", [
          ["750 ml bottle", "20.00"],
          ["With 5 % shrinkage you have", "712.5 ml"],
          ["Price per milliliter", "0.028"],
          ["150 ml glass", "4.21", true],
          ["Glasses per bottle", "4.75"],
        ]],
        ["h3", "Counting the bar"],
        ["p", "When you record inventory by pack you can use decimals (2.3 bottles). In the Inventory table, drinks show their stock, their minimum and the last count's difference in bottles too."],
        ["formula", "Count by weight", ["Open fraction = (Weight − Empty) ÷ (Full − Empty)", "Containers = Unopened + Open fraction"], "Tap the <strong>scale</strong> icon when counting. You weigh an unopened full bottle and an empty one of the same product just once; they're saved for future counts."],
        ["tip", "What the count tells you", "In a bar, actual cost usually ends up several points above theoretical because of spills, over-pouring or comps. The count's difference, in bottles, tells you where to look first."],
        ["h3", "Kitchen and bar in Reports"],
        ["p", "In Reports → Finance, the <strong>Kitchen vs. bar</strong> card shows each area's sales, share of sales and theoretical cost, plus the actual cost if you did an opening and a closing count in the period. Menu Engineering has an All / Kitchen / Bar filter to compare drinks with drinks and dishes with dishes."],
        ["info", "Plan", "Bar recipes and “Sell by the glass”: all plans. Shrinkage: from <strong>Home Cook</strong>. Inventory: from <strong>Chef de Partie</strong>. Kitchen vs. bar in Finance: from <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "inventario",
      title: "Inventory",
      plan: "Chef de Partie plan or higher",
      intro: "Know what you have, what's running out and what your storeroom is worth. Every count is kept as history.",
      blocks: [
        ["figure", "07-inventario.jpg", "Inventory: current stock, minimums, the status of each item and total value."],
        ["h3", "Statuses: normal, low and critical"],
        ["p", "Each item has a <strong>minimum</strong> you set yourself, right in the table. The app uses it to mark its status:"],
        ["table", ["Status", "When it appears"], [
          ["Critical", "Stock is equal to or below the minimum."],
          ["Low", "Stock is equal to or below twice the minimum."],
          ["Normal", "Stock is above twice the minimum, or it hasn't been counted yet."],
        ]],
        ["h3", "Registering inventory"],
        ["p", "“Register Inventory” saves a snapshot of your stock at that moment and updates current quantities. There are three types:"],
        ["cards", [
          ["Count", "Initial Inventory", "What you have at the start of a shift, week or month."],
          ["Count", "Final Inventory", "What's left at the end of the period, to compare with the initial count."],
          ["Stock in", "New Purchase", "Goods that just arrived, with the price you paid. Updates your recipe costs if the price changed."],
        ]],
        ["p", "You can count in the base unit (grams, for example) or by pack (3 sacks), and the app does the conversion. When counting by pack you can use decimals: 2.3 bottles means 2 full ones and 3 tenths of the open one. The real content of the container is always counted, even if the ingredient has shrinkage."],
        ["h3", "What your inventory is worth"],
        ["formula", "Inventory value", ["Item value = Stock × Container price ÷ Container content", "Total value = Sum of all items"], "Stock is stored in the ingredient's unit (ml, g…) and the price is for the whole bottle, sack or box: that's why it's divided by its content. Three 750 ml bottles at 20 are worth 60."],
        ["p", "With every new purchase the app also keeps a <strong>weighted average cost</strong> as a valuation reference. Recipe costing always uses the price of the latest purchase."],
        ["tip", "Automatic recalculation", "If a purchase changes an ingredient's price, every recipe and sub-recipe that uses it recalculates, and the app tells you how many."],
        ["h3", "Theoretical stock: how much should be left"],
        ["p", "Besides the counted stock, each item shows its <strong>theoretical stock</strong>: what should be left based on the sales you recorded after the last count (manual, POS and invoices). Gastrometrics expands every sale through its recipe —including sub-recipes and shrinkage— and deducts it automatically. Editing or deleting a sale corrects the number instantly."],
        ["formula", "Theoretical stock", ["Theoretical stock = Last count + Purchases received − Sales consumption"], "A dish sold consumes one portion of its recipe; a menu sold, one portion of each active dish."],
        ["p", "When you do a new count, you'll see the <strong>last count difference</strong>: what you counted minus what the theory expected. If it's negative, more went out than your recipes explain (shrinkage, waste, larger portions or missing stock): that's your cue to look into it."],
      ],
    },
    {
      id: "menus",
      title: "Menus",
      plan: "Chef de Partie plan or higher",
      intro: "Group your recipes into courses to build a menu, a daily special or an event, with its average price and purchase order.",
      blocks: [
        ["figure", "08-menus.jpg", "Menus: each menu with its courses, active dishes and average price."],
        ["h3", "Creating a menu in 4 steps"],
        ["steps", [
          "<strong>Details</strong>: name, type (lunch, dinner, brunch, buffet, tasting, catering, special event or other), date and number of guests.",
          "<strong>Courses</strong>: Starter, Main and Dessert by default. You can rename, remove or add more.",
          "<strong>Dishes</strong>: the app suggests first the recipes whose “Course” matches each one.",
          "<strong>Review</strong>: the full summary, with the option to set how many portions of each dish you need for that service.",
        ]],
        ["tip", "Drinks menu", "Pick the <strong>Drinks menu</strong> type and the courses change to Cocktails, Wines, Beers and Non-alcoholic drinks. Each one suggests the recipes with the matching bar classification (chapter 6)."],
        ["p", "Each dish can have its own price (otherwise it uses its recipe sheet price) and can be temporarily turned off without removing it from the menu."],
        ["formula", "Menu average price", ["Average price = Sum of active dish prices ÷ Number of active dishes"], "Dishes that are turned off don't count."],
        ["h3", "Export and purchase"],
        ["p", "From each menu you can export the PDF for your guests or the internal version with costs (chapter 12), or generate the purchase order with everything needed to produce it."],
      ],
    },
    {
      id: "compras",
      title: "Purchase Orders",
      intro: "Tell each supplier exactly what and how much you need: by hand, from a menu or a recipe, or by letting the app suggest it from your inventory.",
      blocks: [
        ["figure", "09-ordenes-compra.jpg", "Purchase Orders: the automatic low-stock suggestion and the list of orders with their status."],
        ["h3", "Four ways to create an order"],
        ["list", [
          "<strong>By hand</strong>: search for each ingredient and the app fills in its unit, supplier and price.",
          "<strong>Suggested from low stock</strong>: checks your inventory and builds the order with everything that's low or critical.",
          "<strong>From a menu</strong>: everything needed to produce it, minus what you already have.",
          "<strong>From a recipe</strong>: the “Generate Purchase Order” button in the Recipe Sheet, already scaled if you use the PAX modifier.",
        ]],
        ["formula", "Suggested quantity for low stock", ["Quantity to order = Larger of (2 × Minimum − Current stock) and the Minimum"], "It restocks up to twice your minimum to give you headroom, and never suggests less than the minimum itself."],
        ["formula", "Order total", ["Line cost = Quantity × Price per unit", "Total = Sum of lines + Tax"], "Tax is 0 % by default and you can change it. If the ingredient has a pack, the order also tells you how many packs to buy, rounding up."],
        ["h3", "Statuses and receiving"],
        ["chips", ["Pending", "Approved", "Ordered", "Received", "Cancelled"]],
        ["p", "You can change the status freely. Items are grouped by supplier (those without a supplier go last) so you can call each one with their full list. You can also duplicate or edit an order."],
        ["tip", "“Received” adds to your inventory", "When you mark an order as received, its quantities are added automatically to the stock of inventory items with the same name. If what arrived differs from the order, correct it by recording the real amounts in <strong>Inventory → New Purchase</strong>."],
        ["info", "Plan", "Manual orders are available from <strong>Home Cook</strong>; automatic suggestions from <strong>Chef de Partie</strong>."],
      ],
    },
    {
      id: "ventas",
      title: "Sales and invoices",
      intro: "Record what you sell to compare your prices with reality: by hand, by importing your point-of-sale (POS) system or by issuing invoices to your customers.",
      blocks: [
        ["figure", "10-ventas.jpg", "Sales: POS import and manual entry in one place."],
        ["h3", "Recording sales"],
        ["list", [
          "<strong>Manual entry</strong>: ideal if you don't have a POS. Pick a recipe or a menu and the quantity sold; the app calculates revenue and cost.",
          "<strong>Import your POS</strong>: upload an .xlsx, .xls, .csv or .txt file. You tell it once which column is the dish, quantity, date and price, and save that as a named template. Next time, the app recognizes it on its own.",
        ]],
        ["tip", "Tricky files", "The app detects whether your dates come as day/month or month/day (and lets you correct it), and reads accents and special characters correctly from older Windows-format files."],
        ["h3", "Invoices for your customers"],
        ["p", "In the <strong>Invoices</strong> tab you create the invoice you hand to your customer: pick recipes or menus (or type lines by hand), with automatic numbering, editable tax, notes and your business logo on the PDF. Each invoice automatically counts as a sale in your reports (without tax)."],
        ["warn", "Not an official tax invoice", "The Gastrometrics invoice doesn't include numbering authorized by any tax authority. Check your country's requirements before using it as a tax document."],
        ["h3", "Sales history"],
        ["p", "At the bottom of the page, the history brings together all your sales (manual, POS and invoices), grouped by day, week, month or year, for the date range you choose, with a button to export it to PDF."],
        ["info", "Plan", "Invoices: from <strong>Home Cook</strong>. Manual entry: from <strong>Chef de Partie</strong>. POS import: from <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "reportes",
      title: "Reports",
      intro: "This is where your numbers make sense: which recipes earn the most, what your inventory is worth and how your business is really doing.",
      blocks: [
        ["figure", "11-reportes.jpg", "Reports: a business overview with its indicators and charts."],
        ["h3", "Overview"],
        ["p", "General counts, inventory value and items on alert, average cost and margin, recipes by classification, most-used ingredients, the recipes with the best and worst margin, and each ingredient's price history with its change."],
        ["h3", "Finance"],
        ["p", "If you sell drinks, the <strong>Kitchen vs. bar</strong> card separates sales, theoretical cost and actual cost for each area (chapter 6). Profit and loss statement (P&L), your theoretical versus real food cost based on your sales, price changes by supplier, and <strong>Menu Engineering</strong>, which classifies each dish by comparing it with the average of your own menu:"],
        ["table", ["Category", "Popularity", "Margin", "What to do"], [
          ["Star", "High", "High", "Protect it and feature it on your menu."],
          ["Cash cow", "High", "Low", "It sells well: review its cost or raise its price a little."],
          ["Puzzle", "Low", "High", "Good margin: promote it or improve its presentation."],
          ["Dog", "Low", "Low", "Consider redesigning it or taking it off the menu."],
        ]],
        ["formula", "Cost of goods sold (COGS)", ["COGS = Opening inventory + Purchases − Closing inventory"], "For an exact figure you need an opening and a closing count in the period."],
        ["info", "Plan", "Overview: from <strong>Chef de Partie</strong>. Finance: from <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "pdfs",
      title: "PDF documents",
      intro: "Each document is designed for whoever will read it: your kitchen, your management, your supplier or your customer. Costs never mix with documents meant for outsiders.",
      blocks: [
        ["h3", "The 8 documents"],
        ["table", ["Document", "For", "What it includes"], [
          ["Recipe sheet · Administrative", "Owner and management", "Ingredients with costs, cost items, charts, margin and food cost."],
          ["Recipe sheet · Kitchen", "Your kitchen team", "Ingredients, quantities, photo and procedure, with no money figures."],
          ["Recipe sheet · Quick", "Suppliers or partners", "The essentials of the recipe, without costs or prices."],
          ["Inventory", "Management", "Total value, value by category, top items and statuses."],
          ["Menu · Guest", "Your diners", "An elegant menu, with no cost figures."],
          ["Menu · Internal", "Owner", "Cost, price and margin per dish, with charts."],
          ["Purchase order", "Suppliers", "Ingredients by supplier, quantities and total."],
          ["Invoice", "Your customer", "Your logo, customer details, lines, tax and total."],
        ]],
        ["p", "Recipe sheets and the customer menu include each dish's allergens, calculated from its ingredients at the moment you export (chapter 3)."],
        ["tip", "Automatic warnings", "The administrative sheet warns you at the top if cost exceeds the selling price or if the yield looks mistyped, before you print an odd number."],
        ["p", "PDFs come out in the language selected in the app, use your currency and carry your business's logo and theme color."],
        ["info", "Plan", "The kitchen sheet is included in every plan. The administrative sheet, from <strong>Home Cook</strong>."],
      ],
    },
    {
      id: "equipo",
      title: "Team",
      plan: "Sous Chef plan or higher",
      intro: "Invite your team to work with you in Gastrometrics, each person with access only to what they need.",
      blocks: [
        ["h3", "Inviting someone"],
        ["p", "In <strong>Team</strong> you enter the person's email. They receive an invitation and create their own account; your subscription covers their access. With Sous Chef you can add 1 person and with Chef Ejecutivo up to 4 (each plan's users include you). There are no fixed roles: you set three things separately for each person."],
        ["table", ["Setting", "Options"], [
          ["Scope", "All your businesses, or just one."],
          ["Tools", "Independent boxes: recipes, ingredients, shrinkage, manual and automatic orders, inventory, menus, reports, sales, finance and managing the team."],
          ["PDF", "None, kitchen (no costs) or administrative (with costs)."],
        ]],
        ["tip", "Preview", "Turn on preview to see the app exactly as that person would, with the same permissions."],
        ["p", "Permissions are truly enforced, not just on screen: someone without access to a tool can't see or save that data. If something is locked, the app explains whether it's because of the account's plan or because the owner restricted it."],
      ],
    },
    {
      id: "planes",
      title: "Plans and subscription",
      intro: "Start for free and move up when you need to. Your data is never lost when you change plans.",
      blocks: [
        ["table", ["Plan", "Price", "Businesses", "Users (incl. you)", "Adds"], [
          ["Foodie", "Free", "1", "1", "Recipes, ingredients and kitchen recipe sheet PDF (included in every plan)."],
          ["Home Cook", "$15 / month", "1", "1", "Shrinkage, manual purchase orders, administrative sheet and invoices."],
          ["Chef de Partie", "$35 / month", "1", "1", "Inventory, menus, suggested orders, Reports · Overview and manual sales entry."],
          ["Sous Chef", "$70 / month", "2", "2", "Reports · Finance, P&L, Menu Engineering, POS import and Team (you + 1 person)."],
          ["Chef Ejecutivo", "$120 / month", "5", "5", "Team of up to 4 people besides you. Available for businesses on request."],
        ]],
        ["figure", "12-mi-plan.jpg", "My Plan: your current plan, what it includes and how to manage your subscription."],
        ["h3", "Paying, changing or cancelling"],
        ["p", "Payments are processed by Stripe. From <strong>My Plan</strong> you can change plans or open the billing portal to update your card or cancel. Changes show up in your account automatically and you get a confirmation email."],
        ["p", "Whenever your plan changes —because you changed it, because the Gastrometrics team adjusted it, or because an assigned plan expired— we let you know by email and with a window when you open the Dashboard, listing exactly what you <strong>gain</strong>, what you <strong>lose</strong> and what your plan includes now. If you lose access to a section, your data isn't deleted: it becomes available again if you upgrade later."],
        ["p", "If you cancel, you keep full access until the end of the period you've already paid for. My Plan shows you the exact date."],
        ["info", "When something is locked", "You'll see a padlock and a button to My Plan. If you use the app as part of a team, the message tells you it's the account owner who controls that access."],
      ],
    },
    {
      id: "config",
      title: "Settings, language and emails",
      intro: "Make the app your own, choose your language and currency, decide which emails you get and manage your account data.",
      blocks: [
        ["figure", "13-configuracion.jpg", "Settings → Notifications, where you decide whether to receive updates and reminders."],
        ["h3", "The Settings tabs"],
        ["list", [
          "<strong>Profile</strong>: name, email (changing it asks for your current password), country and business type.",
          "<strong>Appearance</strong>: light, dark or follow your system.",
          "<strong>Regional</strong>: country, currency and language.",
          "<strong>Notifications</strong>: whether you want product updates and reminders by email.",
          "<strong>Account</strong>: data backup, legal documents, delete content and delete the account.",
        ]],
        ["h3", "Language and currency"],
        ["p", "The app is available in <strong>Spanish, English, Danish, French, Portuguese and Chinese</strong>. The language you choose is used across the interface, in your PDFs and in <strong>every email</strong> we send you. There are 21 currencies; changing currency changes the symbol and format, it doesn't convert your amounts. Decimals always use a point."],
        ["h3", "Emails you can receive"],
        ["p", "You always get your account emails: confirmation, password, payments and team invitations. If you turn on <strong>Updates and reminders</strong>, we'll also write when there are new features and, if you haven't signed in for a few days, a helpful reminder based on what you did last:"],
        ["cards", [
          ["Reminder", "Unfinished recipe", "Your Recipe Sheet draft is waiting for you before the 24 hours are up."],
          ["Reminder", "Inventory and reports", "When a week has passed since your last count or since you checked your reports."],
          ["Reminder", "Prices and coming back", "If your prices haven't been updated in over 30 days, or if you haven't visited in a while."],
        ]],
        ["p", "We never send more than one reminder every few days. Every email has a link to unsubscribe in one click, or you can uncheck the box in Settings → Notifications."],
        ["h3", "Your data"],
        ["list", [
          "<strong>Download backup</strong>: a single file with all your content (recipes, ingredients, menus and more).",
          "<strong>Delete all content</strong>: empties your account but keeps it active. You type your email to confirm.",
          "<strong>Delete account</strong>: cancels your subscription and erases everything permanently. It also asks for your email to confirm.",
        ]],
        ["warn", "No going back", "Deleting content or the account can't be undone. Download your backup first."],
      ],
    },
    {
      id: "formulas",
      appendix: "A",
      title: "Formulas at a glance",
      intro: "Every formula in this manual on one page, for quick reference.",
      blocks: [
        ["table", ["Concept", "How it's calculated"], [
          ["Price per unit", "Purchase price ÷ Net content"],
          ["With shrinkage", "Purchase price ÷ (Net content × (1 − shrinkage %))"],
          ["Line cost", "Quantity × Price per unit"],
          ["Production cost", "Sum of lines (× PAX multiplier if active)"],
          ["Unit cost", "Production cost ÷ Yield"],
          ["Price · 6 cost items", "Unit cost + Sum of items ÷ Yield, rounded up to your currency's step"],
          ["Price · Food Cost %", "Unit cost ÷ Target %, rounded up to your currency's step"],
          ["Price with commission", "Price without commission ÷ (1 − Commission %)"],
          ["Fixed cost per dish", "Monthly fixed costs ÷ Estimated dishes per month"],
          ["Total sales", "Final price × Yield"],
          ["Contribution margin", "(Total sales − Production cost) ÷ Total sales"],
          ["Cost %", "Production cost ÷ Total sales"],
          ["Cost of use (sub-recipe)", "Total cost ÷ Yield"],
          ["Inventory status", "Critical if stock ≤ minimum · Low if stock ≤ 2 × minimum"],
          ["Inventory value", "Sum of (Stock × Container price ÷ Container content)"],
          ["Theoretical stock", "Last count + Purchases received − Sales consumption"],
          ["Price of a drink", "Cost per serving ÷ Target pour cost"],
          ["Cost per serving", "Milliliters served × Price per milliliter (with shrinkage)"],
          ["Servings per container", "Usable content ÷ Milliliters served"],
          ["Count by weight", "Unopened + (Weight − Empty) ÷ (Full − Empty)"],
          ["Suggested quantity", "Larger of (2 × Minimum − Stock) and the Minimum"],
          ["Order total", "Sum of lines + Tax"],
          ["Menu average price", "Sum of active dishes ÷ Number of active dishes"],
          ["COGS", "Opening inventory + Purchases − Closing inventory"],
        ]],
      ],
    },
    {
      id: "problemas",
      appendix: "B",
      title: "Frequently asked questions",
      intro: "The most common “this isn't doing what I expected” situations, with their cause and fix.",
      blocks: [
        ["table", ["If this happens…", "What to check"], [
          ["A recipe's cost comes out huge or absurd.", "Check the yield and each ingredient's unit. If you use sub-recipes, make sure the quantity is in grams or milliliters, not units."],
          ["I changed a price and my recipes didn't move.", "Recalculation is immediate. Make sure the recipe uses exactly that ingredient and not a duplicate with a similar name."],
          ["I can't see a module (Inventory, Finance, Team…).", "Your plan doesn't include it, or the account owner didn't give you access. The on-screen message tells you which."],
          ["I marked an order as “Received” and an item wasn't added.", "Only items whose name exactly matches one in inventory are added. Record that item in Inventory → New Purchase."],
          ["I saved a recipe with PAX active by mistake.", "Use “Restore original recipe” and save again."],
          ["I left the Recipe Sheet without saving.", "Go back to the Recipe Sheet within 24 hours: your recipe comes back on its own."],
          ["My emails arrive in another language.", "Change the language in Settings → Regional while signed in; the next emails will arrive in that language."],
          ["I don't want reminders.", "Use the “Stop receiving these emails” link or uncheck the box in Settings → Notifications."],
          ["My drink comes out with a very high price.", "Check that its classification is a “Bar” one: that way the price uses pour cost instead of a dish's 6 cost items."],
        ]],
        ["p", "Another question or a suggestion? Write to us from <strong>Suggestions and reports</strong>, at the bottom of Settings. We read every message."],
      ],
    },
  ],
}
