// Manual de usuario — español (idioma de referencia: los otros 5 deben tener exactamente
// la misma estructura, lo verifica scripts/build.mjs). Texto con HTML mínimo (<strong>, <em>).
export default {
  ui: {
    manualName: "Manual de usuario",
    contents: "Contenido",
    contentsLede: "Si es tu primera vez, lee el capítulo 1 y luego salta directo a lo que necesites: cada capítulo se entiende por sí solo.",
    inThisChapter: "En este capítulo",
    figure: "Figura",
    coverKicker: "Manual de usuario",
    coverTitle: "Costea, vende y crece con Gastrometrics",
    coverLede: "La guía completa para convertir tus recetas en precios justos, controlar tu inventario y entender los números de tu cocina.",
    coverModules: ["Ingredientes", "Ficha Técnica", "Inventario", "Menús", "Órdenes de Compra", "Ventas", "Reportes", "Equipo"],
    edition: "Edición septiembre 2026",
  },
  chapters: [
    {
      id: "bienvenida",
      title: "Bienvenido a Gastrometrics",
      intro: "Gastrometrics convierte tus recetas en números claros: cuánto te cuesta cada plato, a cuánto venderlo y cuánto te deja. Este capítulo te muestra la idea general y el camino más corto a tu primer resultado.",
      blocks: [
        ["h3", "Qué hace Gastrometrics por ti"],
        ["p", "Cargas tus ingredientes con lo que pagas por ellos, armas tus recetas con las cantidades que usas, y la app calcula sola el <strong>costo real de cada plato</strong>, te sugiere un <strong>precio de venta</strong> y te muestra tu <strong>margen</strong>. A partir de ahí, todo lo demás —inventario, menús, compras, ventas y reportes— usa esos mismos números, así que nunca tienes que volver a escribirlos."],
        ["h3", "Cómo se conectan los módulos"],
        ["flow", [
          ["Ingredientes", "precio y merma"],
          ["Recetas", "costo y precio"],
          ["Menús", "cartas y eventos"],
          ["Compras", "pedidos a proveedores"],
          ["Sub-recetas", "vuelven a ser ingrediente"],
          ["Inventario", "stock y conteos"],
          ["Ventas", "manual, POS, facturas"],
          ["Reportes", "margen real y P&L"],
          "Flecha continua = automático · flecha punteada = lo registras tú (un conteo o una compra)",
        ]],
        ["p", "El centro de todo son las <strong>recetas</strong>: leen el precio de tus ingredientes y alimentan menús, órdenes de compra y reportes. Si cambias el precio de un ingrediente, todas las recetas que lo usan se recalculan solas."],
        ["h3", "Tus primeros 10 minutos"],
        ["steps", [
          "<strong>Carga 3 o 4 ingredientes</strong> en Ingredientes, con su precio de compra y su contenido neto. No necesitas tu inventario completo para empezar.",
          "<strong>Crea tu primera receta</strong> en Ficha Técnica: elige esos ingredientes y escribe la cantidad que usas de cada uno.",
          "<strong>Mira el resultado</strong>: el costo de producción, el precio sugerido y el margen aparecen en la misma pantalla, en tiempo real.",
          "<strong>Guarda y exporta</strong> la ficha en PDF para tu cocina o para tu contador.",
          "<strong>Sigue cuando quieras</strong> con inventario, menús o compras. No son obligatorios para ver tu primer precio.",
        ]],
        ["tip", "¿Prefieres ver un ejemplo primero?", "Si todavía no tienes recetas, el Dashboard te ofrece <strong>«Ver un ejemplo primero»</strong>: crea una receta de muestra con su costo y precio ya calculados para que veas cómo funciona. Puedes borrarla cuando quieras."],
        ["h3", "Cómo leer este manual"],
        ["cards", [
          ["", "Consejo", "Atajos y buenas prácticas que te ahorran tiempo."],
          ["", "Importante", "Detalles que conviene saber antes de tocar un botón."],
          ["", "Plan", "Funciones que dependen de tu plan de suscripción (capítulo 14)."],
        ]],
      ],
    },
    {
      id: "cuenta",
      title: "Tu cuenta y tus negocios",
      intro: "Todo en Gastrometrics pertenece a un negocio. Aquí verás cómo registrarte, crear negocios, moverte entre ellos y aprovechar el Dashboard.",
      blocks: [
        ["h3", "Crear tu cuenta"],
        ["p", "El registro es un asistente de 5 pasos: tus datos y contraseña, tu información profesional (país, moneda, tipo y tamaño de negocio), el <strong>plan</strong> que quieres usar, la aceptación de los términos y un resumen final. Si llegas desde la página de planes con uno ya elegido, aparece preseleccionado."],
        ["p", "En el último paso hay una casilla opcional para <strong>recibir novedades y recordatorios por correo</strong>. Viene desmarcada y puedes cambiarla cuando quieras en Configuración (capítulo 15)."],
        ["p", "Al iniciar sesión, la casilla <strong>Recuérdame en este dispositivo</strong> viene marcada: tu sesión se mantiene abierta. Desmárcala en una computadora compartida y la sesión se cerrará al cerrar el navegador."],
        ["h3", "Crear un negocio"],
        ["steps", [
          "<strong>Datos básicos y logo.</strong> Nombre, descripción, tipo de negocio y, si quieres, el logo, que aparecerá en el encabezado de tus PDFs.",
          "<strong>Gastos fijos mensuales.</strong> Renta, servicios, personal, marketing y otros. Sirven para repartir tus costos fijos en el precio de cada plato (capítulo 4).",
          "<strong>Método de precio por defecto.</strong> «Gastrometrics» (6 rubros) o «Food Cost %». Cada receta nueva lo hereda, y puedes cambiarlo receta por receta.",
        ]],
        ["chips", ["Restaurante", "Cafetería", "Panadería", "Pastelería", "Food Truck", "Catering", "Bar", "Pizzería", "Comida Rápida", "Otro"]],
        ["p", "Cada negocio tiene su propia base de ingredientes, recetas, inventario, menús y compras: nada se mezcla entre negocios. Dentro del panel de cada negocio puedes elegir entre 12 colores de tema, que también pintan los acentos de sus PDFs."],
        ["h3", "Moverte entre negocios"],
        ["p", "En <strong>Negocios</strong> ves una tarjeta por cada negocio con el botón «Acceder». Mientras trabajas en cualquier módulo, el menú lateral también muestra tus negocios para saltar de uno a otro sin volver al inicio."],
        ["h3", "El Dashboard"],
        ["figure", "01-dashboard.jpg", "El Dashboard: lo que requiere tu atención hoy, tus indicadores y accesos directos a cada módulo."],
        ["list", [
          "<strong>Qué hacer hoy</strong>: ingredientes bajo su mínimo, recetas sin precio de venta y tu margen promedio. Cada tarjeta te lleva directo a donde puedes resolverlo.",
          "<strong>Indicadores</strong>: total de recetas, ingredientes, negocios y costo promedio, sumando todos tus negocios.",
          "<strong>Acciones rápidas</strong>: un acceso por módulo para entrar sin pasar por el menú lateral.",
        ]],
        ["p", "Mientras empiezas, el Dashboard muestra <strong>Tu camino</strong>: cargar ingredientes, crear tu primera receta, llegar a 3 recetas y explorar lo nuevo. Cada paso te lleva directo a donde se hace. Puedes ocultarlo con la X."],
        ["p", "Los botones de Tu camino abren directamente la importación: «Importar mis ingredientes» y «Importar una receta». Si prefieres empezar de cero, cada paso tiene también la opción a mano."],
        ["h3", "El menú lateral"],
        ["table", ["Sección", "Para qué sirve"], [
          ["Dashboard", "Resumen de toda tu cuenta y lo que requiere atención."],
          ["Ficha Técnica", "Crear o editar una receta, con su costo y precio."],
          ["Mis Recetas", "Buscar, duplicar, mover y recuperar recetas."],
          ["Ingredientes", "Tu base de ingredientes, precios y mermas."],
          ["Inventario", "Stock, conteos y alertas de mínimo."],
          ["Equipo", "Invitar personas y darles permisos."],
          ["Menús", "Armar cartas por tiempos para servicio o eventos."],
          ["Órdenes de Compra", "Pedidos a proveedores, a mano o sugeridos."],
          ["Ventas", "Registrar ventas, importar tu POS y emitir facturas."],
          ["Reportes", "Panorama del negocio y finanzas."],
          ["Negocios", "Crear, abrir y eliminar negocios."],
        ]],
        ["info", "El menú se va completando", "Para no abrumarte, el menú empieza con lo esencial. Con tu primera receta aparecen Reportes y Ventas; con 3 recetas, Inventario, Menús, Órdenes de compra y Equipo, marcados como «Nuevo». Si quieres verlo todo desde el inicio, usa «Ver todos los módulos ahora» al final del menú."],
        ["info", "Configuración y Mi Plan", "Configuración no es una página: es una ventana que abres desde cualquier pantalla con el ícono de engranaje. Tu plan y tu suscripción están en <strong>Mi Plan</strong>, en la parte inferior del menú."],
      ],
    },
    {
      id: "ingredientes",
      title: "Ingredientes",
      intro: "Tus ingredientes son la base de todo el costeo. Si sus precios están al día, tus recetas, menús y reportes también lo estarán.",
      blocks: [
        ["figure", "02-ingredientes.jpg", "La base de ingredientes del negocio, con su categoría, unidad, precio y proveedor."],
        ["h3", "Qué datos lleva un ingrediente"],
        ["p", "Nombre, categoría, unidad de medida, proveedor, presentación de compra (opcional) y su precio: lo que pagas por la presentación completa y cuánto trae. Con eso la app calcula el <strong>precio por unidad</strong>, que es el que realmente se usa en tus recetas."],
        ["formula", "Precio por unidad", ["Precio por unidad = Precio de compra ÷ Contenido neto"], "El contenido neto va en la unidad base del ingrediente (gramos, mililitros, unidades…)."],
        ["example", "Ejemplo · un saco de harina", [
          ["Precio de compra del saco", "450.00"],
          ["Contenido neto", "25000 g"],
          ["Precio por gramo", "0.018", true],
          ["Una receta que usa 300 g cuesta", "300 × 0.018 = 5.40"],
        ]],
        ["h3", "Categorías y unidades"],
        ["p", "Las categorías son una lista fija de 40 (Aves, Res, Pescado, Lácteos, Harina, Especias, Bebidas, Destilados, Vinos, Cervezas, Refrescos y mixers, Desechables…), más una especial, <strong>Sub Receta / producción</strong>, que se asigna sola a las preparaciones que usas como ingrediente (capítulo 5). Las unidades disponibles son:"],
        ["chips", ["Gramos", "Kilogramos", "Mililitros", "Litros", "Onzas", "Onzas líquidas", "Libras", "Galones", "Unidad"]],
        ["p", "Usa <strong>Unidad</strong> para piezas que se cuentan (huevos, latas, panes). La app las trata de forma especial, por ejemplo para avisarte si el rendimiento de una receta parece demasiado bajo."],
        ["tip", "No olvides el empaque", "Vasos, cajas para llevar, bolsas, servilletas o pajillas también son costo de cada plato. Cárgalos como ingredientes en la categoría <strong>Desechables</strong> (por ejemplo, un paquete de 100 cajas, en unidad) y agrégalos a la receta de lo que vendes para llevar. Si no, tu precio no los cubre."],
        ["h3", "Presentaciones de compra"],
        ["p", "Si compras por Caja, Saco, Botella, Lata, Bolsa o Frasco, guarda cuánto trae cada presentación. Así tus órdenes de compra dicen «4 cajas» en lugar de una cantidad en gramos que nadie pediría así."],
        ["h3", "Importar tu lista de ingredientes"],
        ["p", "Carga toda tu base de una vez desde Excel, CSV o una lista pegada, y expórtala a Excel cuando quieras. Si prefieres partir de un formato, la app te genera una plantilla con sus categorías y unidades reales; los encabezados se reconocen en los 6 idiomas."],
        ["p", "El recorrido guiado de Ingredientes termina abriendo esta importación, para que cargues toda tu lista de una vez. Si prefieres, también puedes agregarlos uno por uno con «Nuevo ingrediente»."],
        ["p", "No necesitas la plantilla: sube tu archivo tal como lo tienes (.xlsx, .xls o .csv) o <strong>pega tu lista</strong> copiada de Excel, Google Sheets, un correo o WhatsApp, una por línea (por ejemplo «Tomate, 2 kg, 3.50»). La app reconoce las columnas aunque tengan otros nombres o no tengan títulos, los precios con símbolo de moneda y coma o punto decimal («₡1.500», «$8,50») y el contenido escrito junto a la unidad («saco 25 kg»). Si la lista no trae categoría, se sugiere por el nombre."],
        ["tip", "Ves todo antes de importar", "La vista previa muestra cada ingrediente con su contenido, precio y estado: «Listo», «Sin precio» o «Ya existe» (esos se omiten). Al terminar, la app te ofrece el siguiente paso: importar tus recetas."],
        ["info", "Precios y moneda", "Los precios se guardan en la moneda de tu cuenta (Configuración); la app no convierte de una moneda a otra. Se aceptan con símbolo o código y con coma o punto decimal: «$8,50» y «8.50» son 8.50, «1.250,75» y «1,250.75» son 1250.75. Un número como «1.500» se lee como mil quinientos si tu moneda se usa sin decimales (colón, peso colombiano, chileno o argentino, guaraní) o si lleva «₡»; con las demás monedas es 1.5. Revisa la columna Precio de la vista previa antes de importar."],
        ["h3", "Merma"],
        ["p", "La merma es lo que pagas pero no aprovechas: cáscaras, huesos, recortes, evaporación. En <strong>Gestionar mermas</strong> activas el sistema y, por ingrediente, eliges usar el porcentaje típico de su categoría o uno propio (o una cantidad fija)."],
        ["formula", "Costo real con merma", ["Contenido aprovechable = Contenido neto × (1 − % de merma)", "Precio por unidad = Precio de compra ÷ Contenido aprovechable"], "Pagas por todo el contenido, pero solo aprovechas una parte: por eso el precio real por unidad sube. Si apagas la merma, todo vuelve a los valores originales."],
        ["p", "Algunos porcentajes típicos por categoría: Mariscos 63 %, Pescado 52 %, Res 33 %, Aves 27 %, Fruta 24 %, Vegetales 21 %. Los productos secos y envasados parten de 0 %. Las categorías de barra tienen su propia merma típica: destilados 2 %, vinos 5 %, cerveza de barril 18 % y cerveza embotellada 0 % (capítulo 6)."],
        ["info", "Plan", "La gestión de merma está disponible desde el plan <strong>Home Cook</strong>."],
        ["h3", "Alérgenos"],
        ["p", "En el último paso de cada ingrediente marcas cuáles de los 14 alérgenos de declaración obligatoria contiene (gluten, leche, huevo, frutos secos, soya, pescado, crustáceos, sésamo…). Las recetas que lo usan —también a través de sus sub-recetas— los muestran solas en la Ficha Técnica, en los tres PDF de la ficha y bajo cada plato en la carta del cliente. Nunca se escriben a mano en la receta, así que no quedan desactualizados."],
        ["h3", "Borrar un ingrediente"],
        ["p", "Antes de confirmar, la app te muestra en qué recetas se usa. No te impide borrarlo, pero así sabes qué recetas quedarán con un ingrediente faltante."],
      ],
    },
    {
      id: "ficha",
      title: "Recetas y Ficha Técnica",
      intro: "El corazón de Gastrometrics: conviertes una lista de ingredientes en un costo exacto y un precio de venta justificado, viendo siempre de dónde sale cada número.",
      blocks: [
        ["figure", "03-ficha-tecnica.jpg", "Una receta abierta en la Ficha Técnica: datos generales, ingredientes y cálculo de costos."],
        ["h3", "Llenar la ficha"],
        ["list", [
          "<strong>Nombre</strong> y <strong>Clasificación</strong> (22 opciones, desde Línea caliente hasta Pastelería o I+D). La clasificación «Sub Receta» convierte la receta en ingrediente (capítulo 5). Las 5 clasificaciones «Barra · …» calculan el precio con pour cost (capítulo 6).",
          "<strong>Paso</strong>: en qué momento del servicio va (entrada, plato fuerte, postre…).",
          "<strong>Rendimiento</strong>: cuánto produce la receta (8 porciones, 1200 g…) con su unidad.",
          "<strong>Ingredientes</strong>: búscalos en tu base y escribe la cantidad. Cada línea muestra cuánto cuesta.",
          "<strong>Procedimiento y observaciones</strong>, y una <strong>imagen</strong> del plato.",
        ]],
        ["tip", "Avanza con Enter", "En los primeros campos, presionar Enter te lleva al siguiente. Así puedes llenar la ficha casi sin tocar el mouse."],
        ["h3", "Tu avance se guarda solo por 24 horas"],
        ["p", "Mientras creas una receta nueva, Gastrometrics guarda un <strong>borrador automático</strong>. Si cierras la pestaña, se te va el internet o te vas a otro módulo, al volver a Ficha Técnica la receta aparece tal como la dejaste, con un aviso arriba. El borrador dura <strong>24 horas desde tu último cambio</strong> y también lo encuentras si entras desde otro dispositivo."],
        ["figure", "05-borrador.jpg", "Al volver, un aviso confirma que tu receta fue recuperada. «Limpiar ficha» la deja en blanco."],
        ["p", "¿Quieres empezar de cero? Usa <strong>Limpiar ficha</strong> (junto a «Guardar receta» o en el aviso). Te pide confirmación y borra todo: nombre, ingredientes, procedimiento, imagen, precios y el borrador guardado. Al guardar la receta, el borrador se borra solo."],
        ["h3", "El costo de producción"],
        ["formula", "Costo de cada ingrediente y de la receta", ["Costo de la línea = Cantidad × Precio por unidad", "Costo de producción = Suma de todas las líneas"]],
        ["formula", "Costo unitario", ["Costo unitario = Costo de producción ÷ Rendimiento"], "Si no declaras un rendimiento, la app usa el peso total de los ingredientes medidos en g, ml, kg o litros como estimación."],
        ["h3", "Dos formas de calcular el precio"],
        ["p", "Cada receta usa uno de dos métodos. Tu negocio define cuál va por defecto, pero puedes cambiarlo receta por receta sin perder nada: ambos parten del mismo costo real."],
        ["cards", [
          ["Método 1", "Gastrometrics (6 rubros)", "Reparte tu ganancia en seis rubros, cada uno como porcentaje del costo de producción: servicios públicos 10 %, marketing 10 %, costos operativos 30 %, costos laborales 25 %, impuesto 0 % y ganancia neta 30 % (todos editables)."],
          ["Método 2", "Food Cost %", "Eliges qué porcentaje del precio quieres que represente el costo de los ingredientes (lo usual es 28 % a 35 %) y el precio se calcula a partir de ahí. Es el estándar de la industria."],
        ]],
        ["formula", "Precio de venta sugerido", ["Método 6 rubros: Precio = Costo unitario + (Suma de rubros ÷ Rendimiento)", "Método Food Cost: Precio = Costo unitario ÷ % objetivo"], "En ambos casos el precio se redondea <strong>hacia arriba</strong> al escalón de tu moneda: al 5 en lempiras (61 pasa a 65, nunca baja a 60), al 0.50 en dólares o euros (10.60 pasa a 11.00), al 100 en colones. Es el único redondeo del cálculo. El ejemplo de abajo está en lempiras."],
        ["example", "Ejemplo · mismo costo, dos métodos (costo unitario 20, rendimiento 1)", [
          ["6 rubros: 2 + 2 + 6 + 5 + 0 + 6", "21"],
          ["20 + 21 = 41 → redondeado", "45", true],
          ["Food Cost 30 %: 20 ÷ 0.30 = 66.67 → redondeado", "70", true],
        ]],
        ["p", "Si tu negocio tiene gastos fijos y una estimación de platos al mes, su parte proporcional se suma sola al precio como un rubro más:"],
        ["formula", "Costo fijo por plato", ["Costo fijo por plato = Gastos fijos del mes ÷ Platos estimados al mes"]],
        ["h3", "Comisión de delivery o tarjeta"],
        ["p", "Si vendes por una app de delivery o cobras con tarjeta, escribe en la ficha el <strong>% de comisión</strong> que se quedan sobre el precio. El precio sugerido la cubre, y la ficha te muestra cuánto es la comisión por unidad y cuánto te queda después de pagarla. La ganancia y el margen ya la descuentan."],
        ["formula", "Precio con comisión", ["Precio = Precio sin comisión ÷ (1 − % de comisión)"], "Funciona con los dos métodos y se redondea después, como siempre."],
        ["example", "Ejemplo · costo unitario 20, Food Cost 30 %, comisión 30 % (en lempiras)", [
          ["Precio sin comisión: 20 ÷ 0.30", "66.67"],
          ["66.67 ÷ (1 − 0.30) = 95.24 → redondeado", "100", true],
          ["La app se queda el 30 %", "30"],
          ["Te queda por plato", "70", true],
        ]],
        ["figure", "04-ficha-tecnica-precio.jpg", "El cálculo del precio de venta con el método elegido en la receta, seguido del resumen de costos."],
        ["h3", "Márgenes y precio a mano"],
        ["formula", "Indicadores de la receta", ["Venta total = Precio final × Rendimiento", "Margen de contribución = (Venta total − Costo de producción) ÷ Venta total", "Costo % = Costo de producción ÷ Venta total"]],
        ["p", "El precio sugerido nunca es obligatorio: puedes escribir tu propio <strong>precio de venta</strong> o tu propia <strong>ganancia unitaria</strong>. Los márgenes se recalculan con tu número, pero el costo siempre refleja lo que realmente pagas."],
        ["h3", "Escalar con el modificador de PAX"],
        ["p", "Escribe cuántas personas quieres servir y la app escala todas las cantidades y costos al instante, siempre redondeando <strong>hacia arriba</strong> para que nunca te quedes corto. Es una vista previa: la receta guardada no cambia."],
        ["list", [
          "<strong>Exportar PDF</strong> o <strong>Generar orden de compra</strong> con el PAX activo usa las cantidades escaladas, sin guardar nada. El botón te avisa «Escalado a N».",
          "<strong>Guardar</strong> con el PAX activo te pide confirmación: la receta queda en el nuevo tamaño y el tamaño anterior se conserva como «original».",
          "<strong>Restaurar receta original</strong> vuelve a ese tamaño original. Después presiona Guardar para confirmarlo.",
        ]],
        ["warn", "Rendimiento sospechoso", "Si algún ingrediente medido en «unidad» es 20 veces mayor o más que el rendimiento declarado (por ejemplo, 200 huevos para un rendimiento de 1), verás un aviso amarillo en la ficha y en el PDF. No bloquea nada: solo te ayuda a detectar un error de escritura."],
        ["h3", "Importar tus recetas"],
        ["p", "En Mis Recetas, <strong>Importar receta</strong> convierte una receta que ya tienes en una ficha técnica: pégala tal como la tienes (de Word, WhatsApp o una web), sube un archivo de texto (.txt, .csv, .md), un <strong>Excel</strong> (.xlsx, .xls) o un <strong>PDF</strong>, o <strong>tómale una foto</strong> con la cámara del celular. La app reconoce el nombre, las porciones, los ingredientes con su cantidad y unidad (200 g, 2 tazas, ½ kg, «al gusto», tablas, listas…) y los pasos."],
        ["tip", "Revisas antes de abrirla", "Cada ingrediente se empareja con tu base y su cantidad se convierte a la unidad de ese ingrediente. Los que no tienes se pueden crear (sin precio, lo completas después en Ingredientes), elegir de tu lista u omitir. Nada se guarda hasta que pulsas Guardar en la Ficha Técnica."],
        ["info", "Fotos de recetas", "La foto se lee en tu propio celular o computadora (no se sube a ningún servidor). Verás la foto al lado del texto leído, con la confianza de lectura y las líneas dudosas marcadas: tócalas para corregirlas antes de seguir. Para mejores resultados, toma la foto de frente, con buena luz y sin sombras, y elige el idioma en que está escrita la receta."],
        ["info", "Idioma de la receta", "No tienes que elegirlo: la app asume que la receta está en el idioma que usas en la app y detecta sola si está en otro (por ejemplo, una receta en inglés o en chino), y entonces la vuelve a leer con el idioma correcto. Si quieres fijarlo tú, usa «Cambiar» junto al idioma; si lo cambias después de leer una foto o un PDF escaneado, aparece «Leer de nuevo». Los PDF con texto se leen tal cual, sin OCR; las páginas escaneadas pasan por la misma lectura que las fotos."],
        ["info", "Qué puede y qué no", "Lee recetas impresas, escritas a mano con letra clara, en pantalla o en PDF, en los 6 idiomas de la app; tablas, listas y párrafos; fracciones, rangos («2-3»), números en palabras y «al gusto». No lee bien letra cursiva muy apretada, fotos borrosas, oscuras o muy inclinadas, ni páginas con varias recetas mezcladas (importa una por vez). De un PDF lee hasta 6 páginas y de un Excel la primera hoja. Nunca guarda nada sin que lo confirmes: siempre puedes corregir el texto, cada ingrediente y su cantidad."],
        ["p", "Al guardar una receta importada vuelves a Mis Recetas con la opción «Importar otra receta», para pasar tus recetas una tras otra: los ingredientes que ya creaste se reconocen solos."],
        ["h3", "Mis Recetas: duplicar, mover y papelera"],
        ["figure", "06-mis-recetas.jpg", "Mis Recetas: todas tus recetas con su costo, rendimiento y accesos rápidos."],
        ["list", [
          "<strong>Duplicar</strong> crea una copia en el mismo negocio, con «(copia)» en el nombre.",
          "<strong>Migrar</strong> copia la receta a otro de tus negocios. Te pregunta si llevar también sus ingredientes y sub-recetas (reutiliza los que ya existan allá) o solo la receta: en ese caso se abre su ficha en el negocio para que elijas los ingredientes de su propia base de datos (los que tengan el mismo nombre se vinculan solos).",
          "<strong>Eliminar</strong> la envía a la <strong>papelera</strong>, donde puedes recuperarla durante 30 días antes de que se borre sola.",
        ]],
      ],
    },
    {
      id: "subrecetas",
      title: "Sub-recetas",
      intro: "Una salsa base, un fondo o una masa que usas en muchos platos. Las creas una vez y las usas como un ingrediente más.",
      blocks: [
        ["h3", "Crear una sub-receta"],
        ["p", "Crea la receta normalmente y dale la clasificación <strong>«Sub Receta»</strong>. Al guardarla, Gastrometrics crea un ingrediente con su mismo nombre que ya puedes buscar y agregar en cualquier otra ficha técnica."],
        ["formula", "Costo de uso", ["Costo de uso = Costo total de la sub-receta ÷ Rendimiento"], "Es lo que cuesta cada unidad de la preparación (cada gramo de salsa, por ejemplo) cuando la usas en otra receta."],
        ["h3", "Qué cambia en una sub-receta"],
        ["p", "Como no se vende sola, no tiene precio de venta, rubros ni márgenes. Su resumen muestra solo tres datos: <strong>costo de producción</strong>, <strong>rendimiento</strong> y <strong>costo de uso</strong>."],
        ["h3", "Todo se actualiza en cadena"],
        ["p", "Si sube el precio de un ingrediente de tu salsa base, su costo de uso se recalcula y el cambio llega automáticamente a cada plato que la usa. No tienes que abrir ninguna receta."],
        ["warn", "Cuidado con las cantidades", "El costo de uso suele ser por gramo o mililitro. Si al usarla escribes «150» pensando en unidades en vez de gramos, el costo del plato se dispara. Revisa la unidad antes de guardar."],
      ],
    },
    {
      id: "barra",
      title: "Barra y bebidas",
      intro: "Vino, cerveza, tragos y bebidas sin alcohol se costean igual que la comida: son ingredientes y recetas con algunos ajustes de barra. No hay un módulo aparte que aprender.",
      blocks: [
        ["h3", "Bebidas como ingredientes"],
        ["p", "Carga cada botella, lata o barril como un ingrediente, en mililitros o litros, con su precio y su contenido. Hay categorías propias de barra, cada una con su merma típica (derrames, fondo de botella, espuma):"],
        ["table", ["Categoría", "Merma típica", "Se sirve en"], [
          ["Destilados", "2 %", "Shot 45 ml, doble 90 ml, botella"],
          ["Vinos", "5 %", "Copa 150 o 125 ml, jarra 500 ml, botella"],
          ["Cerveza de barril", "18 %", "Pinta 473 ml, medio litro, vaso 330 ml"],
          ["Cerveza embotellada", "0 %", "Botella o lata completa"],
          ["Refrescos y mixers", "2 %", "Envase completo o vaso 250 ml"],
        ]],
        ["h3", "Tragos en la Ficha Técnica"],
        ["p", "Un cóctel es una receta con sus líneas en mililitros. Al elegir una clasificación <strong>Barra · …</strong>, el precio pasa a calcularse con <strong>pour cost</strong>: el porcentaje del precio que es costo de producto. Ese objetivo es solo de esa receta: no cambia el de tus platos."],
        ["table", ["Clasificación", "Pour cost por defecto", "Rango típico"], [
          ["Barra · Cócteles", "20 %", "15–22 %"],
          ["Barra · Vinos", "30 %", "25–35 %"],
          ["Barra · Cervezas", "24 %", "20–28 %"],
          ["Barra · Sin alcohol", "15 %", "10–20 %"],
          ["Barra · Café y té", "20 %", "15–25 %"],
        ]],
        ["formula", "Precio de una bebida", ["Precio = Costo por servicio ÷ Pour cost objetivo"], "Se redondea hacia arriba al escalón de tu moneda, como cualquier precio sugerido."],
        ["example", "Ejemplo · gin tonic (en dólares)", [
          ["Gin, 45 ml", "1.69"],
          ["Tónica, 150 ml", "0.55"],
          ["Limón", "0.10"],
          ["Costo del trago", "2.34", true],
          ["2.34 ÷ 0.22 = 10.64 → redondeado", "11.00", true],
        ]],
        ["h3", "Vender por copa o botella"],
        ["steps", [
          "En <strong>Ingredientes</strong>, busca la bebida y toca el ícono de <strong>copa</strong> de su fila.",
          "Elige cómo se sirve: una medida (copa, shot, pinta…), otra cantidad en mililitros o el envase completo.",
          "Revisa el costo por servicio, cuántos servicios salen de cada envase y el precio sugerido; puedes escribir tu propio precio.",
          "Toca <strong>Crear ficha</strong>: aparece en Mis Recetas y ya se puede usar en menús, ventas y stock teórico.",
        ]],
        ["formula", "Costo por servicio", ["Costo por servicio = Mililitros servidos × Precio por mililitro", "Servicios por envase = Contenido aprovechable ÷ Mililitros servidos"], "El precio por mililitro ya incluye la merma del ingrediente. Vender la botella entera cuesta exactamente su precio de compra."],
        ["example", "Ejemplo · copa de vino", [
          ["Botella de 750 ml", "20.00"],
          ["Con 5 % de merma quedan", "712.5 ml"],
          ["Precio por mililitro", "0.028"],
          ["Copa de 150 ml", "4.21", true],
          ["Copas por botella", "4.75"],
        ]],
        ["h3", "Contar la barra"],
        ["p", "Al registrar inventario por presentación puedes usar decimales (2.3 botellas). En la tabla de Inventario, las bebidas muestran su stock, su mínimo y la diferencia del último conteo también en botellas."],
        ["formula", "Contar por peso", ["Fracción de la abierta = (Peso − Vacía) ÷ (Llena − Vacía)", "Envases = Cerradas + Fracción de la abierta"], "Toca el ícono de <strong>báscula</strong> al contar. Pesas una sola vez una botella llena sin abrir y una vacía del mismo producto; se guardan para los siguientes conteos."],
        ["tip", "Lo que el conteo te dice", "En una barra, el costo real suele quedar varios puntos por encima del teórico por derrames, sobre-servido o cortesías. La diferencia del conteo, en botellas, te dice dónde mirar primero."],
        ["h3", "Cocina y barra en Reportes"],
        ["p", "En Reportes → Finanzas, la tarjeta <strong>Cocina vs. barra</strong> muestra las ventas, el porcentaje de las ventas y el costo teórico de cada área, y el costo real si hiciste un conteo inicial y uno final en el período. Menu Engineering tiene un filtro Todo / Cocina / Barra para comparar tragos con tragos y platos con platos."],
        ["info", "Plan", "Recetas de barra y «Vender por copa»: todos los planes. Merma: desde <strong>Home Cook</strong>. Inventario: desde <strong>Chef de Partie</strong>. Cocina vs. barra en Finanzas: desde <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "inventario",
      title: "Inventario",
      plan: "Plan Chef de Partie o superior",
      intro: "Sabe cuánto tienes, qué se está acabando y cuánto vale tu bodega. Cada conteo queda guardado como historial.",
      blocks: [
        ["figure", "07-inventario.jpg", "Inventario: stock actual, mínimos, estado de cada producto y valor total."],
        ["h3", "Estados: normal, bajo y crítico"],
        ["p", "Cada producto tiene un <strong>mínimo</strong> que defines tú, directamente en la tabla. Con él, la app marca su estado:"],
        ["table", ["Estado", "Cuándo aparece"], [
          ["Crítico", "El stock es igual o menor al mínimo."],
          ["Bajo", "El stock es igual o menor al doble del mínimo."],
          ["Normal", "El stock está por encima del doble del mínimo, o todavía no se ha contado."],
        ]],
        ["h3", "Registrar inventario"],
        ["p", "«Registrar inventario» guarda una fotografía del stock en ese momento y actualiza las cantidades actuales. Hay tres tipos:"],
        ["cards", [
          ["Conteo", "Inventario inicial", "Lo que tienes al empezar un turno, una semana o un mes."],
          ["Conteo", "Inventario final", "Lo que queda al cerrar el período, para compararlo con el inicial."],
          ["Entrada", "Nueva compra", "Mercadería que acaba de llegar, con el precio que pagaste. Actualiza el costo de tus recetas si el precio cambió."],
        ]],
        ["p", "Puedes contar en la unidad base (gramos, por ejemplo) o por presentación (3 sacos), y la app hace la conversión. Por presentación puedes usar decimales: 2.3 botellas son 2 enteras y 3 décimos de la abierta. Siempre se cuenta el contenido real del envase, aunque el ingrediente tenga merma."],
        ["h3", "Valor de tu inventario"],
        ["formula", "Valor del inventario", ["Valor de un producto = Stock × Precio del envase ÷ Contenido del envase", "Valor total = Suma de todos los productos"], "El stock se guarda en la unidad del ingrediente (ml, g…) y el precio es el de la botella, el saco o la caja completa: por eso se divide entre su contenido. Tres botellas de 750 ml a 20 valen 60."],
        ["p", "Con cada nueva compra, la app lleva además un <strong>costo promedio ponderado</strong> como referencia de valuación. El costeo de tus recetas siempre usa el precio de la última compra."],
        ["tip", "Recálculo automático", "Si una compra cambia el precio de un ingrediente, todas las recetas y sub-recetas que lo usan se recalculan, y la app te dice cuántas fueron."],
        ["h3", "Stock teórico: cuánto debería quedar"],
        ["p", "Además del stock contado, cada producto muestra su <strong>stock teórico</strong>: lo que debería quedar según las ventas que registraste después del último conteo (manuales, del POS y facturas). Gastrometrics expande cada venta por su receta —incluidas sub-recetas y merma— y la descuenta sola. Editar o borrar una venta corrige el número al instante."],
        ["formula", "Stock teórico", ["Stock teórico = Último conteo + Compras recibidas − Consumo de las ventas"], "Un plato vendido consume una porción de su receta; un menú vendido, una porción de cada plato activo."],
        ["p", "Cuando haces un conteo nuevo, verás la <strong>diferencia en el último conteo</strong>: lo que contaste menos lo que la teoría esperaba. Si es negativa, salió más de lo que explican tus recetas (merma, desperdicio, porciones más grandes o faltantes): es la señal para revisar."],
      ],
    },
    {
      id: "menus",
      title: "Menús",
      plan: "Plan Chef de Partie o superior",
      intro: "Agrupa tus recetas en tiempos de servicio para armar una carta, un menú del día o un evento, con su precio promedio y su orden de compra.",
      blocks: [
        ["figure", "08-menus.jpg", "Menús: cada menú con sus tiempos, sus platos activos y su precio promedio."],
        ["h3", "Crear un menú en 4 pasos"],
        ["steps", [
          "<strong>Datos</strong>: nombre, tipo (almuerzo, cena, brunch, buffet, degustación, catering, evento especial u otro), fecha y número de comensales.",
          "<strong>Tiempos</strong>: por defecto Entrada, Plato fuerte y Postre. Puedes renombrarlos, quitarlos o agregar más.",
          "<strong>Platos</strong>: la app te sugiere primero las recetas cuyo «Paso» coincide con cada tiempo.",
          "<strong>Revisión</strong>: el resumen completo, con la opción de indicar cuántas porciones de cada plato necesitas para ese servicio.",
        ]],
        ["tip", "Carta de bebidas", "Elige el tipo <strong>Carta de bebidas</strong> y los tiempos cambian a Cócteles, Vinos, Cervezas y Bebidas sin alcohol. En cada uno se sugieren solas las recetas con la clasificación de barra que corresponde (capítulo 6)."],
        ["p", "Cada plato puede tener un precio propio (si no, usa el de su ficha técnica) y se puede desactivar temporalmente sin quitarlo del menú."],
        ["formula", "Precio promedio del menú", ["Precio promedio = Suma de precios de platos activos ÷ Número de platos activos"], "Los platos desactivados no cuentan."],
        ["h3", "Exportar y comprar"],
        ["p", "Desde cada menú puedes exportar el PDF para tus clientes o la versión interna con costos (capítulo 12), o generar directamente la orden de compra con todo lo necesario para producirlo."],
      ],
    },
    {
      id: "compras",
      title: "Órdenes de Compra",
      intro: "Dile a cada proveedor exactamente qué y cuánto necesitas: a mano, desde un menú o una receta, o dejando que la app lo sugiera mirando tu inventario.",
      blocks: [
        ["figure", "09-ordenes-compra.jpg", "Órdenes de Compra: la sugerencia automática por stock bajo y la lista de órdenes con su estado."],
        ["h3", "Cuatro formas de crear una orden"],
        ["list", [
          "<strong>A mano</strong>: buscas cada ingrediente y la app completa su unidad, proveedor y precio.",
          "<strong>Sugerida por stock bajo</strong>: revisa tu inventario y arma la orden con todo lo que está bajo o crítico.",
          "<strong>Desde un menú</strong>: todo lo necesario para producirlo, descontando lo que ya tienes.",
          "<strong>Desde una receta</strong>: el botón «Generar orden de compra» de la Ficha Técnica, ya escalada si usas el modificador de PAX.",
        ]],
        ["formula", "Cantidad sugerida por stock bajo", ["Cantidad a pedir = Mayor entre (2 × Mínimo − Stock actual) y el Mínimo"], "Repone hasta el doble de tu mínimo para darte margen, y nunca sugiere menos que el propio mínimo."],
        ["formula", "Total de la orden", ["Costo de la línea = Cantidad × Precio por unidad", "Total = Suma de líneas + Impuesto"], "El impuesto es 0 % por defecto y lo puedes cambiar. Si el ingrediente tiene presentación, la orden también te dice cuántos paquetes comprar, redondeando hacia arriba."],
        ["h3", "Estados y recepción"],
        ["chips", ["Pendiente", "Aprobada", "Ordenada", "Recibida", "Cancelada"]],
        ["p", "Puedes cambiar el estado libremente. Los ítems se agrupan por proveedor (los que no tienen proveedor van al final), para que llames a cada uno con su lista completa. También puedes duplicar o editar una orden."],
        ["tip", "«Recibida» suma a tu inventario", "Al marcar una orden como recibida, sus cantidades se suman solas al stock de los productos del inventario con el mismo nombre. Si llegó algo distinto a lo pedido, corrígelo registrando lo real en <strong>Inventario → Nueva compra</strong>."],
        ["info", "Plan", "Las órdenes manuales están disponibles desde <strong>Home Cook</strong>; la sugerencia automática, desde <strong>Chef de Partie</strong>."],
      ],
    },
    {
      id: "ventas",
      title: "Ventas y facturas",
      intro: "Registra lo que vendes para comparar tus precios con la realidad: a mano, importando tu sistema de punto de venta (POS) o emitiendo facturas a tus clientes.",
      blocks: [
        ["figure", "10-ventas.jpg", "Ventas: importación de tu POS y registro manual en un solo lugar."],
        ["h3", "Registrar ventas"],
        ["list", [
          "<strong>Registro manual</strong>: ideal si no tienes POS. Eliges una receta o un menú y la cantidad vendida; la app calcula el ingreso y el costo.",
          "<strong>Importar tu POS</strong>: sube un archivo .xlsx, .xls, .csv o .txt. Indicas una vez qué columna es el plato, la cantidad, la fecha y el precio, y lo guardas como plantilla con nombre. La próxima vez, la app la reconoce sola.",
        ]],
        ["tip", "Archivos difíciles", "La app detecta si tus fechas vienen como día/mes o mes/día (y te deja corregirlo), y lee bien los acentos y la ñ de archivos antiguos en formatos de Windows."],
        ["h3", "Facturas a tus clientes"],
        ["p", "En la pestaña <strong>Facturas</strong> creas la factura que le entregas a tu cliente: eliges recetas o menús (o escribes líneas a mano), con numeración automática, impuesto editable, notas y el logo de tu negocio en el PDF. Cada factura se cuenta automáticamente como una venta en tus reportes (sin el impuesto)."],
        ["warn", "No es una factura fiscal oficial", "La factura de Gastrometrics no incluye numeración autorizada por ninguna autoridad tributaria. Verifica los requisitos de tu país antes de usarla como comprobante fiscal."],
        ["h3", "Historial de ventas"],
        ["p", "Al final de la página, el historial reúne todas tus ventas (manuales, del POS y facturas), agrupadas por día, semana, mes o año, con el rango de fechas que elijas y un botón para exportarlo a PDF."],
        ["info", "Plan", "Facturas: desde <strong>Home Cook</strong>. Registro manual: desde <strong>Chef de Partie</strong>. Importar el POS: desde <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "reportes",
      title: "Reportes",
      intro: "Aquí ves qué significan tus números: qué recetas te dejan más, cuánto vale tu inventario y cómo le va realmente a tu negocio.",
      blocks: [
        ["figure", "11-reportes.jpg", "Reportes: panorama general del negocio con sus indicadores y gráficas."],
        ["h3", "Panorama"],
        ["p", "Conteos generales, valor del inventario y productos en alerta, costo y margen promedio, recetas por clasificación, ingredientes más usados, las recetas con mejor y peor margen, y el historial de precio de cada ingrediente con su variación."],
        ["h3", "Finanzas"],
        ["p", "Si vendes bebidas, la tarjeta <strong>Cocina vs. barra</strong> separa ventas, costo teórico y costo real de cada área (capítulo 6). Estado de resultados (P&L), comparación entre tu food cost teórico y el real según tus ventas, variación de precios por proveedor y análisis de <strong>Menu Engineering</strong>, que clasifica cada plato comparándolo con el promedio de tu propio menú:"],
        ["table", ["Categoría", "Popularidad", "Margen", "Qué hacer"], [
          ["Estrella", "Alta", "Alto", "Protégelo y destácalo en tu carta."],
          ["Vaca", "Alta", "Bajo", "Se vende bien: revisa su costo o sube un poco su precio."],
          ["Puzzle", "Baja", "Alto", "Deja buen margen: promociónalo o mejora su presentación."],
          ["Perro", "Baja", "Bajo", "Considera rediseñarlo o sacarlo del menú."],
        ]],
        ["formula", "Costo de lo vendido (COGS)", ["COGS = Inventario inicial + Compras − Inventario final"], "Para un cálculo exacto necesitas un conteo inicial y uno final en el período."],
        ["info", "Plan", "Panorama: desde <strong>Chef de Partie</strong>. Finanzas: desde <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "pdfs",
      title: "Documentos PDF",
      intro: "Cada documento está pensado para quien lo va a leer: tu cocina, tu gerencia, tu proveedor o tu cliente. Nunca se mezclan costos con documentos para externos.",
      blocks: [
        ["h3", "Los 8 documentos"],
        ["table", ["Documento", "Para quién", "Qué incluye"], [
          ["Ficha técnica · Administrativa", "Dueño y gerencia", "Ingredientes con costos, rubros, gráficas, margen y food cost."],
          ["Ficha técnica · De cocina", "Tu equipo de cocina", "Ingredientes, cantidades, foto y procedimiento, sin ningún dato de dinero."],
          ["Ficha técnica · Rápida", "Proveedores o socios", "Lo esencial de la receta, sin costos ni precios."],
          ["Inventario", "Administración", "Valor total, valor por categoría, productos principales y estados."],
          ["Menú · Cliente", "Tus comensales", "Una carta elegante, sin cifras de costo."],
          ["Menú · Interno", "Dueño", "Costo, precio y margen por plato, con gráficas."],
          ["Orden de compra", "Proveedores", "Ingredientes por proveedor, cantidades y total."],
          ["Factura", "Tu cliente", "Tu logo, datos del cliente, líneas, impuesto y total."],
        ]],
        ["p", "Las fichas técnicas y la carta del cliente incluyen los alérgenos de cada plato, calculados desde sus ingredientes en el momento de exportar (capítulo 3)."],
        ["tip", "Avisos automáticos", "La ficha administrativa te avisa arriba si el costo supera el precio de venta o si el rendimiento parece mal escrito, antes de que imprimas un número extraño."],
        ["p", "Los PDF salen en el idioma que tengas seleccionado en la app, usan tu moneda y llevan el logo y el color de tema de tu negocio."],
        ["info", "Plan", "La ficha de cocina está incluida en todos los planes. La ficha administrativa, desde <strong>Home Cook</strong>."],
      ],
    },
    {
      id: "equipo",
      title: "Equipo",
      plan: "Plan Sous Chef o superior",
      intro: "Invita a tu equipo para que trabaje contigo en Gastrometrics, cada quien con acceso solo a lo que necesita.",
      blocks: [
        ["h3", "Invitar a alguien"],
        ["p", "Desde <strong>Equipo</strong> escribes el correo de la persona. Le llega una invitación y crea su propia cuenta; tu suscripción cubre su acceso. Con Sous Chef puedes sumar a 1 persona y con Chef Ejecutivo hasta 4 (los usuarios de cada plan te incluyen a ti). No hay roles fijos: a cada persona le configuras tres cosas por separado."],
        ["table", ["Ajuste", "Opciones"], [
          ["Alcance", "Todos tus negocios, o solo uno en particular."],
          ["Herramientas", "Casillas independientes: recetas, ingredientes, merma, órdenes manuales y automáticas, inventario, menús, reportes, ventas, finanzas y administrar el equipo."],
          ["PDF", "Ninguno, de cocina (sin costos) o administrativo (con costos)."],
        ]],
        ["tip", "Vista previa", "Activa la vista previa para ver la app exactamente como la vería esa persona, con sus mismos permisos."],
        ["p", "Los permisos se aplican de verdad, no solo en pantalla: una persona sin acceso a una herramienta no puede ver ni guardar esos datos. Si algo está bloqueado, la app le explica si es por el plan de la cuenta o porque el dueño se lo restringió."],
      ],
    },
    {
      id: "planes",
      title: "Planes y suscripción",
      intro: "Empiezas gratis y subes de plan cuando lo necesites. Tus datos nunca se pierden al cambiar de plan.",
      blocks: [
        ["table", ["Plan", "Precio", "Negocios", "Usuarios (contigo)", "Agrega"], [
          ["Foodie", "Gratis", "1", "1", "Recetas, ingredientes y ficha de cocina en PDF (incluidos en todos los planes)."],
          ["Home Cook", "$15 / mes", "1", "1", "Merma, órdenes de compra manuales, ficha administrativa y facturas."],
          ["Chef de Partie", "$35 / mes", "1", "1", "Inventario, menús, órdenes sugeridas, Reportes · Panorama y registro manual de ventas."],
          ["Sous Chef", "$70 / mes", "2", "2", "Reportes · Finanzas, P&L, Menu Engineering, importación del POS y Equipo (tú + 1 persona)."],
          ["Chef Ejecutivo", "$120 / mes", "5", "5", "Equipo de hasta 4 personas además de ti. Disponible para empresas, a pedido."],
        ]],
        ["figure", "12-mi-plan.jpg", "Mi Plan: tu plan actual, lo que incluye y cómo gestionar tu suscripción."],
        ["h3", "Pagar, cambiar o cancelar"],
        ["p", "Los pagos se procesan con Stripe. Desde <strong>Mi Plan</strong> puedes cambiar de plan o abrir el portal de pagos para actualizar tu tarjeta o cancelar. Los cambios se reflejan solos en tu cuenta y te llega un correo de confirmación."],
        ["p", "Cada vez que tu plan cambia —porque lo cambiaste tú, porque lo ajustó el equipo de Gastrometrics o porque venció un plan asignado— te avisamos por correo y con una ventana al entrar al Dashboard, con la lista exacta de lo que <strong>ganas</strong>, lo que <strong>pierdes</strong> y lo que incluye tu plan ahora. Si pierdes acceso a una sección, tus datos no se borran: vuelven a estar disponibles si subes de plan otra vez."],
        ["p", "Si cancelas, mantienes el acceso completo hasta el final del período que ya pagaste. Mi Plan te lo muestra con la fecha exacta."],
        ["info", "Cuando algo está bloqueado", "Verás un candado y un botón hacia Mi Plan. Si usas la app como parte de un equipo, el mensaje te indica que es el dueño de la cuenta quien controla ese acceso."],
      ],
    },
    {
      id: "config",
      title: "Configuración, idioma y correos",
      intro: "Ajusta la app a tu gusto, elige tu idioma y moneda, decide qué correos recibir y administra los datos de tu cuenta.",
      blocks: [
        ["figure", "13-configuracion.jpg", "Configuración → Notificaciones, donde decides si recibir novedades y recordatorios."],
        ["h3", "Las pestañas de Configuración"],
        ["list", [
          "<strong>Perfil</strong>: nombre, correo (cambiarlo pide tu contraseña actual), país y tipo de negocio.",
          "<strong>Apariencia</strong>: modo claro, oscuro o según tu sistema.",
          "<strong>Regional</strong>: país, moneda e idioma.",
          "<strong>Notificaciones</strong>: si quieres recibir novedades y recordatorios por correo.",
          "<strong>Cuenta</strong>: respaldo de tus datos, documentos legales, borrar contenido y eliminar la cuenta.",
        ]],
        ["h3", "Idioma y moneda"],
        ["p", "La app está en <strong>español, inglés, danés, francés, portugués y chino</strong>. El idioma que elijas se usa en toda la interfaz, en tus PDF y en <strong>todos los correos</strong> que te enviamos. Hay 21 monedas disponibles; cambiar de moneda cambia el símbolo y el formato, no convierte tus montos. Los decimales siempre se escriben con punto."],
        ["h3", "Correos que puedes recibir"],
        ["p", "Siempre recibes los correos de tu cuenta: confirmación, contraseña, pagos e invitaciones de equipo. Si activas <strong>Novedades y recordatorios</strong>, además te escribimos cuando hay funciones nuevas y, si llevas unos días sin entrar, un recordatorio útil según lo último que hiciste:"],
        ["cards", [
          ["Recordatorio", "Receta sin terminar", "Tu borrador de Ficha Técnica te espera antes de que se cumplan las 24 horas."],
          ["Recordatorio", "Inventario y reportes", "Cuando pasó una semana desde tu último conteo o desde que revisaste tus reportes."],
          ["Recordatorio", "Precios y regreso", "Si tus precios tienen más de 30 días sin actualizar, o si hace tiempo que no entras."],
        ]],
        ["p", "Y cuando tu cuenta tiene algo concreto que contarte, te escribimos con el dato:"],
        ["cards", [
          ["Cada lunes", "Resumen semanal", "Tus números clave: food cost promedio, valor del inventario, productos bajo mínimo y platos con margen bajo."],
          ["Alerta", "Stock bajo y margen", "Si un producto llega a su mínimo o un plato deja de cubrir su meta de food cost."],
          ["Equipo", "Invitaciones y negocios", "Si tu invitado no ha entrado, o si un negocio nuevo sigue sin recetas."],
          ["Logros", "Avances y tu plan", "Cuando llegas a 10, 25 o 50 recetas, y si tu plan incluye algo que aún no has probado."],
        ]],
        ["p", "Nunca te enviamos más de un recordatorio cada pocos días. Cada correo trae un enlace para darte de baja con un clic, o puedes desmarcar la casilla en Configuración → Notificaciones."],
        ["h3", "Tus datos"],
        ["list", [
          "<strong>Descargar respaldo</strong>: un solo archivo con todo tu contenido (recetas, ingredientes, menús y más).",
          "<strong>Borrar todo el contenido</strong>: vacía tu cuenta pero la mantiene activa. Pide escribir tu correo para confirmar.",
          "<strong>Eliminar la cuenta</strong>: cancela tu suscripción y borra todo de forma permanente. También pide tu correo para confirmar.",
        ]],
        ["warn", "Sin vuelta atrás", "Borrar el contenido o eliminar la cuenta no se puede deshacer. Descarga tu respaldo antes."],
      ],
    },
    {
      id: "formulas",
      appendix: "A",
      title: "Fórmulas de un vistazo",
      intro: "Todas las fórmulas del manual en una sola página, para consultarlas rápido.",
      blocks: [
        ["table", ["Concepto", "Cómo se calcula"], [
          ["Precio por unidad", "Precio de compra ÷ Contenido neto"],
          ["Con merma", "Precio de compra ÷ (Contenido neto × (1 − % merma))"],
          ["Costo de una línea", "Cantidad × Precio por unidad"],
          ["Costo de producción", "Suma de las líneas (× multiplicador de PAX si está activo)"],
          ["Costo unitario", "Costo de producción ÷ Rendimiento"],
          ["Precio · 6 rubros", "Costo unitario + Suma de rubros ÷ Rendimiento, redondeado hacia arriba al escalón de tu moneda"],
          ["Precio · Food Cost %", "Costo unitario ÷ % objetivo, redondeado hacia arriba al escalón de tu moneda"],
          ["Precio con comisión", "Precio sin comisión ÷ (1 − % de comisión)"],
          ["Costo fijo por plato", "Gastos fijos del mes ÷ Platos estimados al mes"],
          ["Venta total", "Precio final × Rendimiento"],
          ["Margen de contribución", "(Venta total − Costo de producción) ÷ Venta total"],
          ["Costo %", "Costo de producción ÷ Venta total"],
          ["Costo de uso (sub-receta)", "Costo total ÷ Rendimiento"],
          ["Estado de inventario", "Crítico si stock ≤ mínimo · Bajo si stock ≤ 2 × mínimo"],
          ["Valor del inventario", "Suma de (Stock × Precio del envase ÷ Contenido del envase)"],
          ["Stock teórico", "Último conteo + Compras recibidas − Consumo de las ventas"],
          ["Precio de una bebida", "Costo por servicio ÷ Pour cost objetivo"],
          ["Costo por servicio", "Mililitros servidos × Precio por mililitro (con merma)"],
          ["Servicios por envase", "Contenido aprovechable ÷ Mililitros servidos"],
          ["Contar por peso", "Cerradas + (Peso − Vacía) ÷ (Llena − Vacía)"],
          ["Cantidad sugerida", "Mayor entre (2 × Mínimo − Stock) y el Mínimo"],
          ["Total de la orden", "Suma de líneas + Impuesto"],
          ["Precio promedio de menú", "Suma de platos activos ÷ Número de platos activos"],
          ["COGS", "Inventario inicial + Compras − Inventario final"],
        ]],
      ],
    },
    {
      id: "problemas",
      appendix: "B",
      title: "Preguntas frecuentes",
      intro: "Las situaciones más comunes de «esto no hace lo que esperaba», con su causa y su solución.",
      blocks: [
        ["table", ["Si te pasa esto…", "Qué revisar"], [
          ["El costo de una receta sale altísimo o absurdo.", "Revisa el rendimiento y las unidades de cada ingrediente. Si usas sub-recetas, confirma que la cantidad esté en gramos o mililitros y no en unidades."],
          ["Cambié un precio y mis recetas no se movieron.", "El recálculo es inmediato. Confirma que la receta usa exactamente ese ingrediente y no uno duplicado con nombre parecido."],
          ["No veo un módulo (Inventario, Finanzas, Equipo…).", "Tu plan no lo incluye, o el dueño de la cuenta no te dio acceso. El mensaje en pantalla te dice cuál de los dos."],
          ["Marqué una orden como «Recibida» y un producto no se sumó.", "Solo se suman los productos cuyo nombre coincide exactamente con uno del inventario. Registra ese producto en Inventario → Nueva compra."],
          ["Guardé una receta con el PAX activo sin querer.", "Usa «Restaurar receta original» y vuelve a guardar."],
          ["Salí de la Ficha Técnica sin guardar.", "Vuelve a Ficha Técnica antes de 24 horas: tu receta se recupera sola."],
          ["Me llegan correos en otro idioma.", "Cambia el idioma en Configuración → Regional estando dentro de tu cuenta; los correos siguientes llegarán en ese idioma."],
          ["No quiero recibir recordatorios.", "Usa el enlace «Dejar de recibir estos correos» o desmarca la casilla en Configuración → Notificaciones."],
          ["Mi trago sale con un precio altísimo.", "Revisa que su clasificación sea de «Barra»: así el precio usa pour cost en lugar de los 6 rubros de un plato."],
        ]],
        ["p", "¿Tienes otra duda o una sugerencia? Escríbenos desde <strong>Sugerencias y reportes</strong>, en la parte inferior de Configuración. Leemos cada mensaje."],
      ],
    },
  ],
}
