// Manuel utilisateur — français. Doit suivre content/es.mjs bloc par bloc (vérifié par scripts/build.mjs).
export default {
  ui: {
    manualName: "Manuel utilisateur",
    contents: "Sommaire",
    contentsLede: "Chaque chapitre commence sur sa propre page. Si c'est votre première fois, lisez le chapitre 1 puis allez directement à ce dont vous avez besoin.",
    inThisChapter: "Dans ce chapitre",
    figure: "Figure",
    coverKicker: "Manuel utilisateur",
    coverTitle: "Calculez, vendez et grandissez avec Gastrometrics",
    coverLede: "Le guide complet pour transformer vos recettes en prix justes, maîtriser votre inventaire et comprendre les chiffres de votre cuisine.",
    coverModules: ["Ingrédients", "Fiche Technique", "Inventaire", "Menus", "Commandes d'Achat", "Ventes", "Rapports", "Équipe"],
    edition: "Édition septembre 2026",
  },
  chapters: [
    {
      id: "bienvenida",
      title: "Bienvenue sur Gastrometrics",
      intro: "Gastrometrics transforme vos recettes en chiffres clairs : ce que coûte chaque plat, à quel prix le vendre et ce qu'il vous rapporte. Ce chapitre vous montre la vue d'ensemble et le chemin le plus court vers votre premier résultat.",
      blocks: [
        ["h3", "Ce que Gastrometrics fait pour vous"],
        ["p", "Vous saisissez vos ingrédients avec ce que vous les payez, vous construisez vos recettes avec les quantités utilisées, et l'application calcule seule le <strong>coût réel de chaque plat</strong>, vous suggère un <strong>prix de vente</strong> et affiche votre <strong>marge</strong>. Ensuite, tout le reste —inventaire, menus, achats, ventes et rapports— utilise ces mêmes chiffres : vous n'avez jamais à les ressaisir."],
        ["h3", "Comment les modules sont reliés"],
        ["flow", [
          ["Ingrédients", "prix et pertes"],
          ["Recettes", "coût et prix"],
          ["Menus", "cartes et événements"],
          ["Achats", "commandes fournisseurs"],
          ["Sous-recettes", "redeviennent ingrédients"],
          ["Inventaire", "stock et comptages"],
          ["Ventes", "manuel, caisse, factures"],
          ["Rapports", "marge réelle et P&L"],
          "Flèche pleine = automatique · flèche en pointillé = c'est vous qui l'enregistrez (un comptage ou un achat)",
        ]],
        ["p", "Les <strong>recettes</strong> sont au centre : elles lisent le prix de vos ingrédients et alimentent menus, commandes d'achat et rapports. Si vous changez le prix d'un ingrédient, toutes les recettes qui l'utilisent se recalculent d'elles-mêmes."],
        ["h3", "Vos 10 premières minutes"],
        ["steps", [
          "<strong>Ajoutez 3 ou 4 ingrédients</strong> dans Ingrédients, avec leur prix d'achat et leur contenu net. Pas besoin de tout votre inventaire pour commencer.",
          "<strong>Créez votre première recette</strong> dans la Fiche Technique : choisissez ces ingrédients et indiquez la quantité utilisée pour chacun.",
          "<strong>Regardez le résultat</strong> : coût de production, prix suggéré et marge s'affichent sur le même écran, en temps réel.",
          "<strong>Enregistrez et exportez</strong> la fiche en PDF pour votre cuisine ou votre comptable.",
          "<strong>Continuez quand vous voulez</strong> avec l'inventaire, les menus ou les achats. Ils ne sont pas nécessaires pour voir votre premier prix.",
        ]],
        ["tip", "Vous préférez voir un exemple d'abord ?", "Si vous n'avez encore aucune recette, le Tableau de bord propose <strong>« Voir un exemple d'abord »</strong> : il crée une recette d'exemple avec son coût et son prix déjà calculés pour que vous voyiez comment cela fonctionne. Vous pouvez la supprimer à tout moment."],
        ["h3", "Comment lire ce manuel"],
        ["cards", [
          ["", "Conseil", "Raccourcis et bonnes pratiques qui vous font gagner du temps."],
          ["", "Important", "Des détails à connaître avant d'appuyer sur un bouton."],
          ["", "Forfait", "Fonctions qui dépendent de votre forfait (chapitre 13)."],
        ]],
      ],
    },
    {
      id: "cuenta",
      title: "Votre compte et vos établissements",
      intro: "Dans Gastrometrics, tout appartient à un établissement. Vous verrez ici comment vous inscrire, créer des établissements, passer de l'un à l'autre et tirer parti du Tableau de bord.",
      blocks: [
        ["h3", "Créer votre compte"],
        ["p", "L'inscription est un assistant en 5 étapes : vos coordonnées et mot de passe, vos informations professionnelles (pays, devise, type et taille d'établissement), le <strong>forfait</strong> souhaité, l'acceptation des conditions et un récapitulatif final. Si vous arrivez depuis la page des forfaits avec un forfait déjà choisi, il est présélectionné."],
        ["p", "La dernière étape comporte une case facultative pour <strong>recevoir les nouveautés et rappels par e-mail</strong>. Elle est décochée par défaut et vous pouvez la modifier à tout moment dans Paramètres (chapitre 14)."],
        ["h3", "Créer un établissement"],
        ["steps", [
          "<strong>Informations de base et logo.</strong> Nom, description, type d'établissement et, si vous le souhaitez, un logo qui apparaîtra en en-tête de vos PDF.",
          "<strong>Frais fixes mensuels.</strong> Loyer, charges, personnel, marketing et autres. Ils servent à répartir vos frais fixes dans le prix de chaque plat (chapitre 4).",
          "<strong>Méthode de prix par défaut.</strong> « Gastrometrics » (6 postes) ou « Food Cost % ». Chaque nouvelle recette en hérite, et vous pouvez la changer recette par recette.",
        ]],
        ["chips", ["Restaurant", "Café", "Boulangerie", "Pâtisserie", "Food Truck", "Traiteur", "Bar", "Pizzeria", "Restauration rapide", "Autre"]],
        ["p", "Chaque établissement a ses propres ingrédients, recettes, inventaire, menus et achats : rien ne se mélange entre établissements. Dans le panneau de chaque établissement, vous pouvez choisir parmi 12 couleurs de thème, qui colorent aussi les accents de ses PDF."],
        ["h3", "Passer d'un établissement à l'autre"],
        ["p", "<strong>Établissements</strong> affiche une carte par établissement avec le bouton « Ouvrir ». Pendant que vous travaillez dans un module, le menu latéral liste aussi vos établissements pour passer de l'un à l'autre sans revenir au début."],
        ["h3", "Le Tableau de bord"],
        ["figure", "01-dashboard.jpg", "Le Tableau de bord : ce qui demande votre attention aujourd'hui, vos indicateurs et des raccourcis vers chaque module."],
        ["list", [
          "<strong>À faire aujourd'hui</strong> : ingrédients sous leur minimum, recettes sans prix de vente et votre marge moyenne. Chaque carte vous mène directement là où vous pouvez agir.",
          "<strong>Indicateurs</strong> : nombre de recettes, d'ingrédients, d'établissements et coût moyen, tous établissements confondus.",
          "<strong>Actions rapides</strong> : un raccourci par module pour entrer sans passer par le menu latéral.",
        ]],
        ["h3", "Le menu latéral"],
        ["table", ["Section", "À quoi elle sert"], [
          ["Tableau de bord", "Vue d'ensemble de tout votre compte et de ce qui demande votre attention."],
          ["Fiche Technique", "Créer ou modifier une recette, avec son coût et son prix."],
          ["Mes Recettes", "Rechercher, dupliquer, déplacer et récupérer des recettes."],
          ["Ingrédients", "Votre base d'ingrédients, prix et pertes."],
          ["Inventaire", "Stock, comptages et alertes de minimum."],
          ["Équipe", "Inviter des personnes et leur donner des droits."],
          ["Menus", "Composer des cartes par étapes pour le service ou des événements."],
          ["Commandes d'Achat", "Commandes aux fournisseurs, à la main ou suggérées."],
          ["Ventes", "Enregistrer des ventes, importer votre caisse et émettre des factures."],
          ["Rapports", "Vue d'ensemble de l'activité et finances."],
          ["Établissements", "Créer, ouvrir et supprimer des établissements."],
        ]],
        ["info", "Paramètres et Mon forfait", "Paramètres n'est pas une page : c'est une fenêtre que vous ouvrez depuis n'importe quel écran avec l'icône d'engrenage. Votre forfait et votre abonnement se trouvent dans <strong>Mon forfait</strong>, en bas du menu."],
      ],
    },
    {
      id: "ingredientes",
      title: "Ingrédients",
      intro: "Vos ingrédients sont la base de tout le calcul des coûts. Si leurs prix sont à jour, vos recettes, menus et rapports le sont aussi.",
      blocks: [
        ["figure", "02-ingredientes.jpg", "La base d'ingrédients de l'établissement, avec catégorie, unité, prix et fournisseur."],
        ["h3", "Ce que contient un ingrédient"],
        ["p", "Nom, catégorie, unité de mesure, fournisseur, conditionnement d'achat (facultatif) et son prix : ce que vous payez pour le conditionnement complet et ce qu'il contient. À partir de là, l'application calcule le <strong>prix par unité</strong>, celui que vos recettes utilisent réellement."],
        ["formula", "Prix par unité", ["Prix par unité = Prix d'achat ÷ Contenu net"], "Le contenu net s'exprime dans l'unité de base de l'ingrédient (grammes, millilitres, unités…)."],
        ["example", "Exemple · un sac de farine", [
          ["Prix d'achat du sac", "450.00"],
          ["Contenu net", "25000 g"],
          ["Prix par gramme", "0.018", true],
          ["Une recette qui utilise 300 g coûte", "300 × 0.018 = 5.40"],
        ]],
        ["h3", "Catégories et unités"],
        ["p", "Les catégories forment une liste fixe de 35 (Volaille, Bœuf, Poisson, Produits laitiers, Farine, Épices, Boissons, Jetables…), plus une catégorie spéciale, <strong>Sous-recette / production</strong>, attribuée automatiquement aux préparations utilisées comme ingrédient (chapitre 5). Les unités disponibles sont :"],
        ["chips", ["Grammes", "Kilogrammes", "Millilitres", "Litres", "Onces", "Onces liquides", "Livres", "Gallons", "Unité"]],
        ["p", "Utilisez <strong>Unité</strong> pour ce qui se compte (œufs, boîtes, petits pains). L'application les traite de façon particulière, par exemple pour vous avertir si le rendement d'une recette semble trop faible."],
        ["h3", "Conditionnements d'achat"],
        ["p", "Si vous achetez par caisse, sac, bouteille, boîte, sachet ou bocal, enregistrez ce que contient chaque conditionnement. Vos commandes indiqueront ainsi « 4 caisses » plutôt qu'une quantité en grammes que personne ne commanderait."],
        ["h3", "Importer depuis Excel"],
        ["p", "Vous pouvez charger ou exporter toute votre base dans Excel avec un modèle généré par l'application à partir de ses vraies catégories et unités. Les en-têtes de colonnes sont reconnus dans les 6 langues de l'application."],
        ["h3", "Pertes"],
        ["p", "Les pertes, c'est ce que vous payez sans pouvoir l'utiliser : épluchures, os, parures, évaporation. Dans <strong>Gérer les Pertes</strong>, vous activez le système et choisissez pour chaque ingrédient le pourcentage type de sa catégorie ou le vôtre (ou une quantité fixe)."],
        ["formula", "Coût réel avec pertes", ["Contenu utilisable = Contenu net × (1 − % de pertes)", "Prix par unité = Prix d'achat ÷ Contenu utilisable"], "Vous payez la totalité mais n'en utilisez qu'une partie : le prix réel par unité augmente donc. Si vous désactivez les pertes, tout revient aux valeurs d'origine."],
        ["p", "Quelques pourcentages types par catégorie : Fruits de mer 63 %, Poisson 52 %, Bœuf 33 %, Volaille 27 %, Fruits 24 %, Légumes 21 %. Les produits secs et emballés partent de 0 %."],
        ["info", "Forfait", "La gestion des pertes est disponible à partir du forfait <strong>Home Cook</strong>."],
        ["h3", "Supprimer un ingrédient"],
        ["p", "Avant de confirmer, l'application vous montre dans quelles recettes il est utilisé. Elle ne vous empêche pas de le supprimer, mais vous savez quelles recettes auront un ingrédient manquant."],
      ],
    },
    {
      id: "ficha",
      title: "Recettes et Fiche Technique",
      intro: "Le cœur de Gastrometrics : vous transformez une liste d'ingrédients en un coût exact et un prix de vente justifié, en voyant toujours d'où vient chaque chiffre.",
      blocks: [
        ["figure", "03-ficha-tecnica.jpg", "Une recette ouverte dans la Fiche Technique : informations générales, ingrédients et calcul des coûts."],
        ["h3", "Remplir la fiche"],
        ["list", [
          "<strong>Nom</strong> et <strong>Classification</strong> (17 options, de la Ligne chaude à la Pâtisserie ou R&D). La classification « Sous-recette » transforme la recette en ingrédient (chapitre 5).",
          "<strong>Étape</strong> : à quel moment du service elle intervient (entrée, plat, dessert…).",
          "<strong>Rendement</strong> : ce que produit la recette (8 portions, 1200 g…) avec son unité.",
          "<strong>Ingrédients</strong> : recherchez-les dans votre base et indiquez la quantité. Chaque ligne affiche son coût.",
          "<strong>Procédure et observations</strong>, ainsi qu'une <strong>photo</strong> du plat.",
        ]],
        ["tip", "Avancez avec Entrée", "Dans les premiers champs, la touche Entrée vous amène au champ suivant : vous pouvez remplir la fiche presque sans toucher la souris."],
        ["h3", "Votre travail est conservé 24 heures"],
        ["p", "Pendant que vous créez une nouvelle recette, Gastrometrics enregistre un <strong>brouillon automatique</strong>. Si vous fermez l'onglet, perdez la connexion ou passez à un autre module, en revenant à la Fiche Technique la recette réapparaît telle que vous l'aviez laissée, avec un avis en haut. Le brouillon dure <strong>24 heures après votre dernière modification</strong> et vous le retrouvez aussi depuis un autre appareil."],
        ["figure", "05-borrador.jpg", "À votre retour, un avis confirme que votre recette a été récupérée. « Vider la fiche » la remet à blanc."],
        ["p", "Vous voulez repartir de zéro ? Utilisez <strong>Vider la fiche</strong> (à côté de « Enregistrer la Recette » ou dans l'avis). Une confirmation est demandée, puis tout est effacé : nom, ingrédients, procédure, photo, prix et brouillon enregistré. Enregistrer la recette supprime automatiquement le brouillon."],
        ["h3", "Le coût de production"],
        ["formula", "Coût de chaque ingrédient et de la recette", ["Coût de la ligne = Quantité × Prix par unité", "Coût de production = Somme de toutes les lignes"]],
        ["formula", "Coût unitaire", ["Coût unitaire = Coût de production ÷ Rendement"], "Si vous n'indiquez pas de rendement, l'application l'estime à partir du poids total des ingrédients mesurés en g, ml, kg ou litres."],
        ["h3", "Deux façons de calculer le prix"],
        ["p", "Chaque recette utilise l'une de deux méthodes. Votre établissement définit celle par défaut, mais vous pouvez la changer recette par recette sans rien perdre : les deux partent du même coût réel."],
        ["cards", [
          ["Méthode 1", "Gastrometrics (6 postes)", "Répartit votre bénéfice en six postes, chacun en pourcentage du coût de production : charges 10 %, marketing 10 %, frais d'exploitation 30 %, main-d'œuvre 25 %, taxe 0 % et bénéfice net 30 % (tous modifiables)."],
          ["Méthode 2", "Food Cost %", "Vous choisissez la part du prix que doit représenter le coût des ingrédients (en général 28 % à 35 %) et le prix est calculé à partir de là. C'est la norme du secteur."],
        ]],
        ["formula", "Prix de vente suggéré", ["6 postes : Prix = Coût unitaire + (Somme des postes ÷ Rendement)", "Food Cost : Prix = Coût unitaire ÷ % cible"], "Dans les deux cas, le prix est arrondi <strong>au-dessus</strong> au multiple de 5 suivant : 61 devient 65, jamais 60. C'est le seul arrondi du calcul."],
        ["example", "Exemple · même coût, deux méthodes (coût unitaire 20, rendement 1)", [
          ["6 postes : 2 + 2 + 6 + 5 + 0 + 6", "21"],
          ["20 + 21 = 41 → arrondi", "45", true],
          ["Food Cost 30 % : 20 ÷ 0.30 = 66.67 → arrondi", "70", true],
        ]],
        ["p", "Si votre établissement a des frais fixes et une estimation du nombre de plats par mois, leur part proportionnelle s'ajoute automatiquement au prix comme un poste de plus :"],
        ["formula", "Frais fixes par plat", ["Frais fixes par plat = Frais fixes du mois ÷ Plats estimés par mois"]],
        ["figure", "04-ficha-tecnica-precio.jpg", "Le calcul du prix de vente avec la méthode choisie pour la recette, suivi du récapitulatif des coûts."],
        ["h3", "Marges et prix manuel"],
        ["formula", "Indicateurs de la recette", ["Vente totale = Prix final × Rendement", "Marge de contribution = (Vente totale − Coût de production) ÷ Vente totale", "Coût % = Coût de production ÷ Vente totale"]],
        ["p", "Le prix suggéré n'est jamais obligatoire : vous pouvez saisir votre propre <strong>prix de vente</strong> ou votre propre <strong>bénéfice unitaire</strong>. Les marges se recalculent avec votre chiffre, mais le coût reflète toujours ce que vous payez réellement."],
        ["h3", "Adapter avec le modificateur de PAX"],
        ["p", "Indiquez pour combien de personnes vous voulez servir et l'application adapte instantanément toutes les quantités et tous les coûts, en arrondissant toujours <strong>au-dessus</strong> pour ne jamais manquer. C'est un aperçu : la recette enregistrée ne change pas."],
        ["list", [
          "<strong>Exporter en PDF</strong> ou <strong>Générer un Bon de Commande</strong> avec le PAX actif utilise les quantités adaptées, sans rien enregistrer. Le bouton vous prévient « Adapté à N ».",
          "<strong>Enregistrer</strong> avec le PAX actif demande une confirmation : la recette est enregistrée à la nouvelle taille et l'ancienne taille est conservée comme « originale ».",
          "<strong>Restaurer la recette originale</strong> revient à cette taille d'origine. Appuyez ensuite sur Enregistrer pour confirmer.",
        ]],
        ["warn", "Rendement suspect", "Si un ingrédient mesuré en « unité » atteint 20 fois le rendement déclaré ou plus (par exemple 200 œufs pour un rendement de 1), un avertissement jaune apparaît dans la fiche et dans le PDF. Il ne bloque rien : il vous aide seulement à repérer une faute de frappe."],
        ["h3", "Mes Recettes : dupliquer, déplacer et corbeille"],
        ["figure", "06-mis-recetas.jpg", "Mes Recettes : toutes vos recettes avec leur coût, leur rendement et des actions rapides."],
        ["list", [
          "<strong>Dupliquer</strong> crée une copie dans le même établissement, avec « (copie) » dans le nom.",
          "<strong>Migrer</strong> déplace la recette vers un autre de vos établissements, avec ses sous-recettes et ingrédients, en réutilisant ceux qui y existent déjà.",
          "<strong>Supprimer</strong> l'envoie à la <strong>corbeille</strong>, où vous pouvez la récupérer pendant 30 jours avant sa suppression automatique.",
        ]],
      ],
    },
    {
      id: "subrecetas",
      title: "Sous-recettes",
      intro: "Une sauce de base, un fond ou une pâte que vous utilisez dans de nombreux plats. Vous la créez une fois et l'utilisez comme n'importe quel ingrédient.",
      blocks: [
        ["h3", "Créer une sous-recette"],
        ["p", "Créez la recette normalement et donnez-lui la classification <strong>« Sous-recette / production (Mise en place) »</strong>. À l'enregistrement, Gastrometrics crée un ingrédient du même nom que vous pouvez rechercher et ajouter dans n'importe quelle autre fiche technique."],
        ["formula", "Coût d'utilisation", ["Coût d'utilisation = Coût total de la sous-recette ÷ Rendement"], "C'est ce que coûte chaque unité de la préparation (chaque gramme de sauce, par exemple) quand vous l'utilisez dans une autre recette."],
        ["h3", "Ce qui change dans une sous-recette"],
        ["p", "Comme elle ne se vend pas seule, elle n'a ni prix de vente, ni postes, ni marges. Son récapitulatif n'affiche que trois chiffres : <strong>coût de production</strong>, <strong>rendement</strong> et <strong>coût d'utilisation</strong>."],
        ["h3", "Tout se met à jour en chaîne"],
        ["p", "Si le prix d'un ingrédient de votre sauce de base augmente, son coût d'utilisation se recalcule et le changement se répercute automatiquement sur chaque plat qui l'utilise. Vous n'avez aucune recette à ouvrir."],
        ["warn", "Attention aux quantités", "Le coût d'utilisation est généralement par gramme ou millilitre. Si vous saisissez « 150 » en pensant à des unités au lieu de grammes, le coût du plat s'envole. Vérifiez l'unité avant d'enregistrer."],
      ],
    },
    {
      id: "inventario",
      title: "Inventaire",
      plan: "Forfait Chef de Partie ou supérieur",
      intro: "Sachez ce que vous avez, ce qui s'épuise et ce que vaut votre réserve. Chaque comptage est conservé dans l'historique.",
      blocks: [
        ["figure", "07-inventario.jpg", "Inventaire : stock actuel, minimums, état de chaque produit et valeur totale."],
        ["h3", "États : normal, bas et critique"],
        ["p", "Chaque produit a un <strong>minimum</strong> que vous définissez vous-même, directement dans le tableau. L'application s'en sert pour indiquer son état :"],
        ["table", ["État", "Quand il apparaît"], [
          ["Critique", "Le stock est égal ou inférieur au minimum."],
          ["Bas", "Le stock est égal ou inférieur au double du minimum."],
          ["Normal", "Le stock dépasse le double du minimum, ou le produit n'a pas encore été compté."],
        ]],
        ["h3", "Enregistrer l'inventaire"],
        ["p", "« Enregistrer l'Inventaire » garde une photographie du stock à ce moment-là et met à jour les quantités actuelles. Il existe trois types :"],
        ["cards", [
          ["Comptage", "Inventaire Initial", "Ce que vous avez au début d'un service, d'une semaine ou d'un mois."],
          ["Comptage", "Inventaire Final", "Ce qui reste à la fin de la période, pour le comparer au comptage initial."],
          ["Entrée", "Nouvel Achat", "Marchandise qui vient d'arriver, avec le prix payé. Met à jour le coût de vos recettes si le prix a changé."],
        ]],
        ["p", "Vous pouvez compter dans l'unité de base (grammes, par exemple) ou par conditionnement (3 sacs), et l'application fait la conversion."],
        ["h3", "La valeur de votre inventaire"],
        ["formula", "Valeur de l'inventaire", ["Valeur d'un produit = Stock actuel × Prix", "Valeur totale = Somme de tous les produits"]],
        ["p", "À chaque nouvel achat, l'application tient aussi un <strong>coût moyen pondéré</strong> comme référence de valorisation. Le calcul du coût des recettes utilise toujours le prix du dernier achat."],
        ["tip", "Recalcul automatique", "Si un achat change le prix d'un ingrédient, toutes les recettes et sous-recettes qui l'utilisent se recalculent, et l'application vous indique combien."],
      ],
    },
    {
      id: "menus",
      title: "Menus",
      plan: "Forfait Chef de Partie ou supérieur",
      intro: "Regroupez vos recettes par étapes de service pour composer une carte, un menu du jour ou un événement, avec son prix moyen et sa commande d'achat.",
      blocks: [
        ["figure", "08-menus.jpg", "Menus : chaque menu avec ses étapes, ses plats actifs et son prix moyen."],
        ["h3", "Créer un menu en 4 étapes"],
        ["steps", [
          "<strong>Informations</strong> : nom, type (déjeuner, dîner, brunch, buffet, dégustation, traiteur, événement spécial ou autre), date et nombre de couverts.",
          "<strong>Étapes</strong> : Entrée, Plat et Dessert par défaut. Vous pouvez les renommer, les supprimer ou en ajouter.",
          "<strong>Plats</strong> : l'application suggère d'abord les recettes dont l'« Étape » correspond.",
          "<strong>Vérification</strong> : le récapitulatif complet, avec la possibilité d'indiquer combien de portions de chaque plat il vous faut pour ce service.",
        ]],
        ["p", "Chaque plat peut avoir son propre prix (sinon il utilise celui de sa fiche technique) et peut être désactivé temporairement sans être retiré du menu."],
        ["formula", "Prix moyen du menu", ["Prix moyen = Somme des prix des plats actifs ÷ Nombre de plats actifs"], "Les plats désactivés ne comptent pas."],
        ["h3", "Exporter et acheter"],
        ["p", "Depuis chaque menu, vous pouvez exporter le PDF pour vos clients ou la version interne avec les coûts (chapitre 11), ou générer directement la commande d'achat avec tout le nécessaire pour le produire."],
      ],
    },
    {
      id: "compras",
      title: "Commandes d'Achat",
      intro: "Dites à chaque fournisseur exactement quoi et combien il vous faut : à la main, depuis un menu ou une recette, ou en laissant l'application le suggérer à partir de votre inventaire.",
      blocks: [
        ["figure", "09-ordenes-compra.jpg", "Commandes d'Achat : la suggestion automatique pour stock bas et la liste des commandes avec leur état."],
        ["h3", "Quatre façons de créer une commande"],
        ["list", [
          "<strong>À la main</strong> : recherchez chaque ingrédient et l'application complète unité, fournisseur et prix.",
          "<strong>Suggérée pour stock bas</strong> : vérifie votre inventaire et prépare la commande avec tout ce qui est bas ou critique.",
          "<strong>Depuis un menu</strong> : tout le nécessaire pour le produire, moins ce que vous avez déjà.",
          "<strong>Depuis une recette</strong> : le bouton « Générer un Bon de Commande » de la Fiche Technique, déjà adapté si vous utilisez le modificateur de PAX.",
        ]],
        ["formula", "Quantité suggérée pour stock bas", ["Quantité à commander = Le plus grand entre (2 × Minimum − Stock actuel) et le Minimum"], "Elle réapprovisionne jusqu'au double de votre minimum pour vous laisser de la marge, et ne suggère jamais moins que le minimum lui-même."],
        ["formula", "Total de la commande", ["Coût de la ligne = Quantité × Prix par unité", "Total = Somme des lignes + Taxe"], "La taxe est de 0 % par défaut et modifiable. Si l'ingrédient a un conditionnement, la commande indique aussi combien en acheter, arrondi au-dessus."],
        ["h3", "États et réception"],
        ["chips", ["En attente", "Approuvée", "Commandée", "Reçue", "Annulée"]],
        ["p", "Vous pouvez changer l'état librement. Les articles sont regroupés par fournisseur (ceux sans fournisseur à la fin) pour appeler chacun avec sa liste complète. Vous pouvez aussi dupliquer ou modifier une commande."],
        ["warn", "« Reçue » ne modifie pas votre inventaire", "Marquer une commande comme reçue change seulement son état. Pour mettre à jour le stock, enregistrez ce qui est réellement arrivé dans <strong>Inventaire → Nouvel Achat</strong>, avec la quantité et le prix payés."],
        ["info", "Forfait", "Les commandes manuelles sont disponibles à partir de <strong>Home Cook</strong> ; la suggestion automatique à partir de <strong>Chef de Partie</strong>."],
      ],
    },
    {
      id: "ventas",
      title: "Ventes et factures",
      intro: "Enregistrez ce que vous vendez pour comparer vos prix à la réalité : à la main, en important votre système de caisse (POS) ou en émettant des factures à vos clients.",
      blocks: [
        ["figure", "10-ventas.jpg", "Ventes : import de la caisse et saisie manuelle au même endroit."],
        ["h3", "Enregistrer des ventes"],
        ["list", [
          "<strong>Saisie manuelle</strong> : idéale si vous n'avez pas de caisse. Choisissez une recette ou un menu et la quantité vendue ; l'application calcule le chiffre d'affaires et le coût.",
          "<strong>Importer votre caisse</strong> : téléversez un fichier .xlsx, .xls, .csv ou .txt. Vous indiquez une fois quelle colonne correspond au plat, à la quantité, à la date et au prix, et l'enregistrez comme modèle nommé. La fois suivante, l'application le reconnaît seule.",
        ]],
        ["tip", "Fichiers difficiles", "L'application détecte si vos dates sont au format jour/mois ou mois/jour (et vous laisse corriger), et lit correctement les accents des anciens fichiers au format Windows."],
        ["h3", "Factures pour vos clients"],
        ["p", "Dans l'onglet <strong>Factures</strong>, vous créez la facture remise à votre client : choisissez des recettes ou des menus (ou saisissez des lignes à la main), avec numérotation automatique, taxe modifiable, notes et le logo de votre établissement sur le PDF. Chaque facture compte automatiquement comme une vente dans vos rapports (hors taxe)."],
        ["warn", "Ce n'est pas une facture fiscale officielle", "La facture Gastrometrics ne comporte aucune numérotation autorisée par une autorité fiscale. Vérifiez les exigences de votre pays avant de l'utiliser comme justificatif fiscal."],
        ["h3", "Historique des ventes"],
        ["p", "En bas de la page, l'historique réunit toutes vos ventes (manuelles, caisse et factures), regroupées par jour, semaine, mois ou année, sur la période de votre choix, avec un bouton pour l'exporter en PDF."],
        ["info", "Forfait", "Factures : à partir de <strong>Home Cook</strong>. Saisie manuelle : à partir de <strong>Chef de Partie</strong>. Import de la caisse : à partir de <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "reportes",
      title: "Rapports",
      intro: "C'est ici que vos chiffres prennent sens : quelles recettes rapportent le plus, ce que vaut votre inventaire et comment se porte réellement votre établissement.",
      blocks: [
        ["figure", "11-reportes.jpg", "Rapports : vue d'ensemble de l'activité avec ses indicateurs et graphiques."],
        ["h3", "Vue d'ensemble"],
        ["p", "Chiffres généraux, valeur de l'inventaire et produits en alerte, coût et marge moyens, recettes par classification, ingrédients les plus utilisés, recettes à la meilleure et à la pire marge, et l'historique de prix de chaque ingrédient avec sa variation."],
        ["h3", "Finances"],
        ["p", "Compte de résultat (P&L), food cost théorique face au réel d'après vos ventes, variation des prix par fournisseur et <strong>Menu Engineering</strong>, qui classe chaque plat en le comparant à la moyenne de votre propre menu :"],
        ["table", ["Catégorie", "Popularité", "Marge", "Que faire"], [
          ["Étoile", "Haute", "Haute", "Protégez-le et mettez-le en avant sur votre carte."],
          ["Vache à lait", "Haute", "Basse", "Il se vend bien : revoyez son coût ou augmentez un peu son prix."],
          ["Énigme", "Basse", "Haute", "Bonne marge : faites-en la promotion ou améliorez sa présentation."],
          ["Poids mort", "Basse", "Basse", "Envisagez de le retravailler ou de le retirer du menu."],
        ]],
        ["formula", "Coût des marchandises vendues (COGS)", ["COGS = Inventaire initial + Achats − Inventaire final"], "Pour un chiffre exact, il vous faut un comptage initial et un comptage final sur la période."],
        ["info", "Forfait", "Vue d'ensemble : à partir de <strong>Chef de Partie</strong>. Finances : à partir de <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "pdfs",
      title: "Documents PDF",
      intro: "Chaque document est conçu pour son lecteur : votre cuisine, votre direction, votre fournisseur ou votre client. Les coûts ne se retrouvent jamais dans les documents destinés à l'extérieur.",
      blocks: [
        ["h3", "Les 8 documents"],
        ["table", ["Document", "Pour qui", "Ce qu'il contient"], [
          ["Fiche technique · Administrative", "Propriétaire et direction", "Ingrédients avec coûts, postes, graphiques, marge et food cost."],
          ["Fiche technique · Cuisine", "Votre équipe de cuisine", "Ingrédients, quantités, photo et procédure, sans aucun montant."],
          ["Fiche technique · Rapide", "Fournisseurs ou partenaires", "L'essentiel de la recette, sans coûts ni prix."],
          ["Inventaire", "Administration", "Valeur totale, valeur par catégorie, principaux produits et états."],
          ["Menu · Client", "Vos convives", "Une carte élégante, sans chiffres de coût."],
          ["Menu · Interne", "Propriétaire", "Coût, prix et marge par plat, avec graphiques."],
          ["Commande d'achat", "Fournisseurs", "Ingrédients par fournisseur, quantités et total."],
          ["Facture", "Votre client", "Votre logo, les données du client, les lignes, la taxe et le total."],
        ]],
        ["tip", "Avertissements automatiques", "La fiche administrative vous avertit en haut si le coût dépasse le prix de vente ou si le rendement semble mal saisi, avant que vous n'imprimiez un chiffre étrange."],
        ["p", "Les PDF sortent dans la langue sélectionnée dans l'application, utilisent votre devise et portent le logo et la couleur de thème de votre établissement."],
        ["info", "Forfait", "La fiche de cuisine est incluse dans tous les forfaits. La fiche administrative, à partir de <strong>Home Cook</strong>."],
      ],
    },
    {
      id: "equipo",
      title: "Équipe",
      plan: "Forfait Chef Ejecutivo",
      intro: "Invitez votre équipe à travailler avec vous dans Gastrometrics, chacun n'ayant accès qu'à ce dont il a besoin.",
      blocks: [
        ["h3", "Inviter quelqu'un"],
        ["p", "Dans <strong>Équipe</strong>, saisissez l'e-mail de la personne. Elle reçoit une invitation et crée son propre compte ; votre abonnement couvre son accès. Il n'y a pas de rôles fixes : vous réglez trois éléments séparément pour chaque personne."],
        ["table", ["Réglage", "Options"], [
          ["Portée", "Tous vos établissements, ou un seul en particulier."],
          ["Outils", "Cases indépendantes : recettes, ingrédients, pertes, commandes manuelles et automatiques, inventaire, menus, rapports, ventes, finances et gestion de l'équipe."],
          ["PDF", "Aucun, cuisine (sans coûts) ou administratif (avec coûts)."],
        ]],
        ["tip", "Aperçu", "Activez l'aperçu pour voir l'application exactement comme cette personne la verrait, avec les mêmes droits."],
        ["p", "Les droits sont réellement appliqués, pas seulement à l'écran : une personne sans accès à un outil ne peut ni voir ni enregistrer ces données. Si quelque chose est verrouillé, l'application explique si c'est à cause du forfait du compte ou parce que le propriétaire l'a restreint."],
      ],
    },
    {
      id: "planes",
      title: "Forfaits et abonnement",
      intro: "Vous commencez gratuitement et passez à un forfait supérieur quand vous en avez besoin. Vos données ne se perdent jamais en changeant de forfait.",
      blocks: [
        ["table", ["Forfait", "Prix", "Établissements", "Utilisateurs", "Ajoute"], [
          ["Foodie", "Gratuit", "1", "1", "Recettes, ingrédients et fiche de cuisine en PDF (inclus dans tous les forfaits)."],
          ["Home Cook", "15 $ / mois", "1", "1", "Pertes, commandes d'achat manuelles, fiche administrative et factures."],
          ["Chef de Partie", "35 $ / mois", "1", "1", "Inventaire, menus, commandes suggérées, Rapports · Vue d'ensemble et saisie manuelle des ventes."],
          ["Sous Chef", "70 $ / mois", "2", "2", "Rapports · Finances, P&L, Menu Engineering et import de la caisse."],
          ["Chef Ejecutivo", "120 $ / mois", "5", "5", "Équipe avec droits par personne."],
        ]],
        ["figure", "12-mi-plan.jpg", "Mon forfait : votre forfait actuel, ce qu'il comprend et comment gérer votre abonnement."],
        ["h3", "Payer, changer ou résilier"],
        ["p", "Les paiements sont traités par Stripe. Depuis <strong>Mon forfait</strong>, vous pouvez changer de forfait ou ouvrir le portail de paiement pour mettre à jour votre carte ou résilier. Les changements apparaissent automatiquement sur votre compte et vous recevez un e-mail de confirmation."],
        ["p", "Si vous résiliez, vous gardez un accès complet jusqu'à la fin de la période déjà payée. Mon forfait vous indique la date exacte."],
        ["info", "Quand quelque chose est verrouillé", "Vous voyez un cadenas et un bouton vers Mon forfait. Si vous utilisez l'application au sein d'une équipe, le message vous indique que c'est le propriétaire du compte qui contrôle cet accès."],
      ],
    },
    {
      id: "config",
      title: "Paramètres, langue et e-mails",
      intro: "Adaptez l'application à vos goûts, choisissez votre langue et votre devise, décidez quels e-mails recevoir et gérez les données de votre compte.",
      blocks: [
        ["figure", "13-configuracion.jpg", "Paramètres → Notifications, où vous choisissez de recevoir ou non les nouveautés et rappels."],
        ["h3", "Les onglets de Paramètres"],
        ["list", [
          "<strong>Profil</strong> : nom, e-mail (le modifier demande votre mot de passe actuel), pays et type d'établissement.",
          "<strong>Apparence</strong> : mode clair, sombre ou selon votre système.",
          "<strong>Régional</strong> : pays, devise et langue.",
          "<strong>Notifications</strong> : les e-mails et alertes que vous souhaitez recevoir.",
          "<strong>Compte</strong> : sauvegarde de vos données, documents juridiques, suppression du contenu et du compte.",
        ]],
        ["h3", "Langue et devise"],
        ["p", "L'application est disponible en <strong>espagnol, anglais, danois, français, portugais et chinois</strong>. La langue choisie s'applique à toute l'interface, à vos PDF et à <strong>tous les e-mails</strong> que nous vous envoyons. 21 devises sont disponibles ; changer de devise modifie le symbole et le format, sans convertir vos montants. Les décimales s'écrivent toujours avec un point."],
        ["h3", "Les e-mails que vous pouvez recevoir"],
        ["p", "Vous recevez toujours les e-mails liés à votre compte : confirmation, mot de passe, paiements et invitations d'équipe. Si vous activez <strong>Nouveautés et rappels</strong>, nous vous écrivons aussi lors de nouvelles fonctions et, si vous ne vous êtes pas connecté depuis quelques jours, un rappel utile selon votre dernière activité :"],
        ["cards", [
          ["Rappel", "Recette inachevée", "Votre brouillon de Fiche Technique vous attend avant la fin des 24 heures."],
          ["Rappel", "Inventaire et rapports", "Quand une semaine s'est écoulée depuis votre dernier comptage ou depuis que vous avez consulté vos rapports."],
          ["Rappel", "Prix et retour", "Si vos prix n'ont pas été mis à jour depuis plus de 30 jours, ou si vous n'êtes pas venu depuis longtemps."],
        ]],
        ["p", "Nous n'envoyons jamais plus d'un rappel tous les quelques jours. Chaque e-mail contient un lien pour vous désabonner en un clic, ou vous pouvez décocher la case dans Paramètres → Notifications."],
        ["h3", "Vos données"],
        ["list", [
          "<strong>Télécharger la sauvegarde</strong> : un seul fichier avec tout votre contenu (recettes, ingrédients, menus et plus).",
          "<strong>Supprimer tout le contenu</strong> : vide votre compte tout en le gardant actif. Vous saisissez votre e-mail pour confirmer.",
          "<strong>Supprimer le compte</strong> : résilie votre abonnement et efface tout définitivement. Votre e-mail est aussi demandé pour confirmer.",
        ]],
        ["warn", "Sans retour possible", "Supprimer le contenu ou le compte est irréversible. Téléchargez d'abord votre sauvegarde."],
      ],
    },
    {
      id: "formulas",
      appendix: "A",
      title: "Les formules en un coup d'œil",
      intro: "Toutes les formules du manuel sur une seule page, pour les consulter rapidement.",
      blocks: [
        ["table", ["Notion", "Comment elle se calcule"], [
          ["Prix par unité", "Prix d'achat ÷ Contenu net"],
          ["Avec pertes", "Prix d'achat ÷ (Contenu net × (1 − % de pertes))"],
          ["Coût d'une ligne", "Quantité × Prix par unité"],
          ["Coût de production", "Somme des lignes (× multiplicateur de PAX s'il est actif)"],
          ["Coût unitaire", "Coût de production ÷ Rendement"],
          ["Prix · 6 postes", "Coût unitaire + Somme des postes ÷ Rendement, arrondi au-dessus à 5"],
          ["Prix · Food Cost %", "Coût unitaire ÷ % cible, arrondi au-dessus à 5"],
          ["Frais fixes par plat", "Frais fixes du mois ÷ Plats estimés par mois"],
          ["Vente totale", "Prix final × Rendement"],
          ["Marge de contribution", "(Vente totale − Coût de production) ÷ Vente totale"],
          ["Coût %", "Coût de production ÷ Vente totale"],
          ["Coût d'utilisation (sous-recette)", "Coût total ÷ Rendement"],
          ["État de l'inventaire", "Critique si stock ≤ minimum · Bas si stock ≤ 2 × minimum"],
          ["Valeur de l'inventaire", "Somme de (Stock × Prix)"],
          ["Quantité suggérée", "Le plus grand entre (2 × Minimum − Stock) et le Minimum"],
          ["Total de la commande", "Somme des lignes + Taxe"],
          ["Prix moyen du menu", "Somme des plats actifs ÷ Nombre de plats actifs"],
          ["COGS", "Inventaire initial + Achats − Inventaire final"],
        ]],
      ],
    },
    {
      id: "problemas",
      appendix: "B",
      title: "Questions fréquentes",
      intro: "Les situations « ça ne fait pas ce que j'attendais » les plus courantes, avec leur cause et leur solution.",
      blocks: [
        ["table", ["Si cela vous arrive…", "Que vérifier"], [
          ["Le coût d'une recette est énorme ou absurde.", "Vérifiez le rendement et l'unité de chaque ingrédient. Si vous utilisez des sous-recettes, assurez-vous que la quantité est en grammes ou millilitres et non en unités."],
          ["J'ai changé un prix et mes recettes n'ont pas bougé.", "Le recalcul est immédiat. Vérifiez que la recette utilise exactement cet ingrédient et non un doublon au nom semblable."],
          ["Je ne vois pas un module (Inventaire, Finances, Équipe…).", "Votre forfait ne l'inclut pas, ou le propriétaire du compte ne vous y a pas donné accès. Le message à l'écran vous dit lequel des deux."],
          ["J'ai marqué une commande « Reçue » et le stock n'a pas changé.", "C'est normal : enregistrez ce qui est arrivé dans Inventaire → Nouvel Achat."],
          ["J'ai enregistré une recette avec le PAX actif par erreur.", "Utilisez « Restaurer la recette originale » puis enregistrez à nouveau."],
          ["J'ai quitté la Fiche Technique sans enregistrer.", "Revenez à la Fiche Technique dans les 24 heures : votre recette réapparaît d'elle-même."],
          ["Mes e-mails arrivent dans une autre langue.", "Changez la langue dans Paramètres → Régional en étant connecté ; les e-mails suivants arriveront dans cette langue."],
          ["Je ne veux pas de rappels.", "Utilisez le lien « Ne plus recevoir ces e-mails » ou décochez la case dans Paramètres → Notifications."],
        ]],
        ["p", "Une autre question ou une suggestion ? Écrivez-nous depuis <strong>Suggestions et signalements</strong>, en bas de Paramètres. Nous lisons chaque message."],
      ],
    },
  ],
}
