// Manual do usuário — português. Deve seguir content/es.mjs bloco a bloco (verificado por scripts/build.mjs).
export default {
  ui: {
    manualName: "Manual do usuário",
    contents: "Sumário",
    contentsLede: "Se é a sua primeira vez, leia o capítulo 1 e depois vá direto ao que precisar: cada capítulo pode ser lido sozinho.",
    inThisChapter: "Neste capítulo",
    figure: "Figura",
    coverKicker: "Manual do usuário",
    coverTitle: "Calcule, venda e cresça com a Gastrometrics",
    coverLede: "O guia completo para transformar suas receitas em preços justos, controlar seu estoque e entender os números da sua cozinha.",
    coverModules: ["Ingredientes", "Ficha Técnica", "Estoque", "Cardápios", "Pedidos de Compra", "Vendas", "Relatórios", "Equipe"],
    edition: "Edição setembro 2026",
  },
  chapters: [
    {
      id: "bienvenida",
      title: "Bem-vindo à Gastrometrics",
      intro: "A Gastrometrics transforma suas receitas em números claros: quanto custa cada prato, por quanto vendê-lo e quanto ele deixa para você. Este capítulo mostra a visão geral e o caminho mais curto até o seu primeiro resultado.",
      blocks: [
        ["h3", "O que a Gastrometrics faz por você"],
        ["p", "Você cadastra seus ingredientes com o que paga por eles, monta suas receitas com as quantidades que usa, e o app calcula sozinho o <strong>custo real de cada prato</strong>, sugere um <strong>preço de venda</strong> e mostra a sua <strong>margem</strong>. A partir daí, todo o resto —estoque, cardápios, compras, vendas e relatórios— usa esses mesmos números, então você nunca precisa digitá-los de novo."],
        ["h3", "Como os módulos se conectam"],
        ["flow", [
          ["Ingredientes", "preço e perdas"],
          ["Receitas", "custo e preço"],
          ["Cardápios", "cardápios e eventos"],
          ["Compras", "pedidos a fornecedores"],
          ["Sub-receitas", "voltam a ser ingrediente"],
          ["Estoque", "saldo e contagens"],
          ["Vendas", "manual, PDV, faturas"],
          ["Relatórios", "margem real e DRE"],
          "Seta contínua = automático · seta tracejada = você registra (uma contagem ou uma compra)",
        ]],
        ["p", "O centro de tudo são as <strong>receitas</strong>: elas leem o preço dos seus ingredientes e alimentam cardápios, pedidos de compra e relatórios. Se você muda o preço de um ingrediente, todas as receitas que o usam são recalculadas sozinhas."],
        ["h3", "Seus primeiros 10 minutos"],
        ["steps", [
          "<strong>Cadastre 3 ou 4 ingredientes</strong> em Ingredientes, com o preço de compra e o conteúdo líquido. Você não precisa do estoque completo para começar.",
          "<strong>Crie sua primeira receita</strong> na Ficha Técnica: escolha esses ingredientes e informe a quantidade que usa de cada um.",
          "<strong>Veja o resultado</strong>: o custo de produção, o preço sugerido e a margem aparecem na mesma tela, em tempo real.",
          "<strong>Salve e exporte</strong> a ficha em PDF para a sua cozinha ou para o seu contador.",
          "<strong>Continue quando quiser</strong> com estoque, cardápios ou compras. Eles não são obrigatórios para ver o seu primeiro preço.",
        ]],
        ["tip", "Prefere ver um exemplo primeiro?", "Se você ainda não tem receitas, o Painel oferece <strong>«Ver um exemplo primeiro»</strong>: ele cria uma receita de exemplo com custo e preço já calculados para você ver como funciona. Você pode apagá-la quando quiser."],
        ["h3", "Como ler este manual"],
        ["cards", [
          ["", "Dica", "Atalhos e boas práticas que economizam seu tempo."],
          ["", "Importante", "Detalhes que vale a pena saber antes de apertar um botão."],
          ["", "Plano", "Funções que dependem do seu plano de assinatura (capítulo 14)."],
        ]],
      ],
    },
    {
      id: "cuenta",
      title: "Sua conta e seus negócios",
      intro: "Tudo na Gastrometrics pertence a um negócio. Aqui você verá como se cadastrar, criar negócios, alternar entre eles e aproveitar o Painel.",
      blocks: [
        ["h3", "Criar sua conta"],
        ["p", "O cadastro é um assistente de 5 etapas: seus dados e senha, suas informações profissionais (país, moeda, tipo e tamanho do negócio), o <strong>plano</strong> que você quer usar, a aceitação dos termos e um resumo final. Se você chegar da página de planos com um já escolhido, ele vem pré-selecionado."],
        ["p", "Na última etapa há uma caixa opcional para <strong>receber novidades e lembretes por e-mail</strong>. Ela vem desmarcada e você pode mudá-la quando quiser em Configurações (capítulo 15)."],
        ["h3", "Criar um negócio"],
        ["steps", [
          "<strong>Dados básicos e logo.</strong> Nome, descrição, tipo de negócio e, se quiser, o logo, que aparecerá no cabeçalho dos seus PDFs.",
          "<strong>Despesas fixas mensais.</strong> Aluguel, contas, pessoal, marketing e outras. Servem para distribuir seus custos fixos no preço de cada prato (capítulo 4).",
          "<strong>Método de preço padrão.</strong> «Gastrometrics» (6 itens) ou «Food Cost %». Cada receita nova o herda, e você pode mudá-lo receita por receita.",
        ]],
        ["chips", ["Restaurante", "Cafeteria", "Padaria", "Confeitaria", "Food Truck", "Catering", "Bar", "Pizzaria", "Fast Food", "Outro"]],
        ["p", "Cada negócio tem sua própria base de ingredientes, receitas, estoque, cardápios e compras: nada se mistura entre negócios. No painel de cada negócio você pode escolher entre 12 cores de tema, que também colorem os destaques dos PDFs dele."],
        ["h3", "Alternar entre negócios"],
        ["p", "Em <strong>Negócios</strong> você vê um cartão por negócio com o botão «Acessar». Enquanto trabalha em qualquer módulo, o menu lateral também mostra seus negócios para você pular de um para outro sem voltar ao início."],
        ["h3", "O Painel"],
        ["figure", "01-dashboard.jpg", "O Painel: o que precisa da sua atenção hoje, seus indicadores e atalhos para cada módulo."],
        ["list", [
          "<strong>O que fazer hoje</strong>: ingredientes abaixo do mínimo, receitas sem preço de venda e sua margem média. Cada cartão leva direto para onde você pode resolver.",
          "<strong>Indicadores</strong>: total de receitas, ingredientes, negócios e custo médio, somando todos os seus negócios.",
          "<strong>Ações rápidas</strong>: um atalho por módulo para entrar sem passar pelo menu lateral.",
        ]],
        ["h3", "O menu lateral"],
        ["table", ["Seção", "Para que serve"], [
          ["Painel", "Resumo de toda a sua conta e do que precisa de atenção."],
          ["Ficha Técnica", "Criar ou editar uma receita, com custo e preço."],
          ["Minhas Receitas", "Buscar, duplicar, mover e recuperar receitas."],
          ["Ingredientes", "Sua base de ingredientes, preços e perdas."],
          ["Estoque", "Saldo, contagens e alertas de mínimo."],
          ["Equipe", "Convidar pessoas e dar permissões."],
          ["Cardápios", "Montar cardápios por etapas para serviço ou eventos."],
          ["Pedidos de Compra", "Pedidos a fornecedores, manuais ou sugeridos."],
          ["Vendas", "Registrar vendas, importar seu PDV e emitir faturas."],
          ["Relatórios", "Panorama do negócio e finanças."],
          ["Negócios", "Criar, abrir e excluir negócios."],
        ]],
        ["info", "Configurações e Meu Plano", "Configurações não é uma página: é uma janela que você abre em qualquer tela pelo ícone de engrenagem. Seu plano e sua assinatura ficam em <strong>Meu Plano</strong>, na parte inferior do menu."],
      ],
    },
    {
      id: "ingredientes",
      title: "Ingredientes",
      intro: "Seus ingredientes são a base de todo o custeio. Se os preços estiverem em dia, suas receitas, cardápios e relatórios também estarão.",
      blocks: [
        ["figure", "02-ingredientes.jpg", "A base de ingredientes do negócio, com categoria, unidade, preço e fornecedor."],
        ["h3", "Quais dados um ingrediente tem"],
        ["p", "Nome, categoria, unidade de medida, fornecedor, embalagem de compra (opcional) e o preço: quanto você paga pela embalagem inteira e quanto ela contém. Com isso o app calcula o <strong>preço por unidade</strong>, que é o que realmente entra nas suas receitas."],
        ["formula", "Preço por unidade", ["Preço por unidade = Preço de compra ÷ Conteúdo líquido"], "O conteúdo líquido fica na unidade base do ingrediente (gramas, mililitros, unidades…)."],
        ["example", "Exemplo · um saco de farinha", [
          ["Preço de compra do saco", "450.00"],
          ["Conteúdo líquido", "25000 g"],
          ["Preço por grama", "0.018", true],
          ["Uma receita que usa 300 g custa", "300 × 0.018 = 5.40"],
        ]],
        ["h3", "Categorias e unidades"],
        ["p", "As categorias são uma lista fixa de 40 (Aves, Carne bovina, Peixe, Laticínios, Farinha, Especiarias, Bebidas, Destilados, Vinhos, Cervejas, Refrigerantes e mixers, Descartáveis…), mais uma especial, <strong>Sub-receita / produção</strong>, atribuída automaticamente às preparações que você usa como ingrediente (capítulo 5). As unidades disponíveis são:"],
        ["chips", ["Gramas", "Quilogramas", "Mililitros", "Litros", "Onças", "Onças líquidas", "Libras", "Galões", "Unidade"]],
        ["p", "Use <strong>Unidade</strong> para itens que se contam (ovos, latas, pães). O app os trata de forma especial, por exemplo para avisar se o rendimento de uma receita parece baixo demais."],
        ["tip", "Não esqueça a embalagem", "Copos, embalagens para viagem, sacolas, guardanapos ou canudos também são custo de cada prato. Cadastre-os como ingredientes na categoria <strong>Descartáveis</strong> (por exemplo, um pacote de 100 caixas, por unidade) e adicione-os à receita do que você vende para viagem. Senão, seu preço não os cobre."],
        ["h3", "Embalagens de compra"],
        ["p", "Se você compra por caixa, saco, garrafa, lata, pacote ou pote, registre quanto cada embalagem contém. Assim seus pedidos de compra dizem «4 caixas» em vez de uma quantidade em gramas que ninguém pediria."],
        ["h3", "Importar do Excel"],
        ["p", "Você pode carregar ou exportar toda a sua base em Excel com um modelo que o app gera a partir das suas categorias e unidades reais. Os cabeçalhos são reconhecidos nos 6 idiomas do app."],
        ["h3", "Perdas"],
        ["p", "Perda é o que você paga mas não aproveita: cascas, ossos, aparas, evaporação. Em <strong>Gerenciar Perdas</strong> você ativa o sistema e, por ingrediente, escolhe usar a porcentagem típica da categoria ou uma própria (ou uma quantidade fixa)."],
        ["formula", "Custo real com perdas", ["Conteúdo aproveitável = Conteúdo líquido × (1 − % de perda)", "Preço por unidade = Preço de compra ÷ Conteúdo aproveitável"], "Você paga por tudo, mas só aproveita uma parte: por isso o preço real por unidade sobe. Se você desativar as perdas, tudo volta aos valores originais."],
        ["p", "Algumas porcentagens típicas por categoria: Frutos do mar 63 %, Peixe 52 %, Carne bovina 33 %, Aves 27 %, Frutas 24 %, Verduras 21 %. Produtos secos e embalados começam em 0 %. As categorias de bar têm sua própria perda típica: destilados 2 %, vinhos 5 %, chope 18 % e cerveja engarrafada 0 % (capítulo 6)."],
        ["info", "Plano", "O gerenciamento de perdas está disponível a partir do plano <strong>Home Cook</strong>."],
        ["h3", "Alergênicos"],
        ["p", "No último passo de cada ingrediente você marca quais dos 14 alergênicos de declaração obrigatória ele contém (glúten, leite, ovos, oleaginosas, soja, peixe, crustáceos, gergelim…). As receitas que o usam —também através das sub-receitas— os mostram sozinhas na Ficha Técnica, nos três PDFs da ficha e embaixo de cada prato no cardápio do cliente. Nunca são digitados à mão na receita, então não ficam desatualizados."],
        ["h3", "Excluir um ingrediente"],
        ["p", "Antes de confirmar, o app mostra em quais receitas ele é usado. Ele não impede a exclusão, mas assim você sabe quais receitas ficarão com um ingrediente faltando."],
      ],
    },
    {
      id: "ficha",
      title: "Receitas e Ficha Técnica",
      intro: "O coração da Gastrometrics: você transforma uma lista de ingredientes em um custo exato e um preço de venda justificado, vendo sempre de onde vem cada número.",
      blocks: [
        ["figure", "03-ficha-tecnica.jpg", "Uma receita aberta na Ficha Técnica: dados gerais, ingredientes e cálculo de custos."],
        ["h3", "Preencher a ficha"],
        ["list", [
          "<strong>Nome</strong> e <strong>Classificação</strong> (22 opções, de Linha quente a Confeitaria ou P&D). A classificação «Sub-receita» transforma a receita em ingrediente (capítulo 5). As 5 classificações «Bar · …» calculam o preço com pour cost (capítulo 6).",
          "<strong>Etapa</strong>: em que momento do serviço ela entra (entrada, prato principal, sobremesa…).",
          "<strong>Rendimento</strong>: quanto a receita produz (8 porções, 1200 g…) com a unidade.",
          "<strong>Ingredientes</strong>: busque na sua base e informe a quantidade. Cada linha mostra quanto custa.",
          "<strong>Modo de preparo e observações</strong>, e uma <strong>foto</strong> do prato.",
        ]],
        ["tip", "Avance com Enter", "Nos primeiros campos, apertar Enter leva você ao próximo. Assim dá para preencher a ficha quase sem tocar no mouse."],
        ["h3", "Seu progresso fica salvo por 24 horas"],
        ["p", "Enquanto você cria uma receita nova, a Gastrometrics guarda um <strong>rascunho automático</strong>. Se você fechar a aba, perder a internet ou for para outro módulo, ao voltar à Ficha Técnica a receita aparece como você deixou, com um aviso no topo. O rascunho dura <strong>24 horas desde a sua última alteração</strong> e também aparece se você entrar por outro dispositivo."],
        ["figure", "05-borrador.jpg", "Ao voltar, um aviso confirma que sua receita foi recuperada. «Limpar ficha» deixa tudo em branco."],
        ["p", "Quer começar do zero? Use <strong>Limpar ficha</strong> (ao lado de «Salvar Receita» ou no aviso). Ele pede confirmação e apaga tudo: nome, ingredientes, modo de preparo, foto, preços e o rascunho salvo. Ao salvar a receita, o rascunho é apagado sozinho."],
        ["h3", "O custo de produção"],
        ["formula", "Custo de cada ingrediente e da receita", ["Custo da linha = Quantidade × Preço por unidade", "Custo de produção = Soma de todas as linhas"]],
        ["formula", "Custo unitário", ["Custo unitário = Custo de produção ÷ Rendimento"], "Se você não informar um rendimento, o app estima pelo peso total dos ingredientes medidos em g, ml, kg ou litros."],
        ["h3", "Duas formas de calcular o preço"],
        ["p", "Cada receita usa um de dois métodos. Seu negócio define o padrão, mas você pode mudá-lo receita por receita sem perder nada: ambos partem do mesmo custo real."],
        ["cards", [
          ["Método 1", "Gastrometrics (6 itens)", "Distribui seu lucro em seis itens, cada um como porcentagem do custo de produção: contas 10 %, marketing 10 %, custos operacionais 30 %, mão de obra 25 %, imposto 0 % e lucro líquido 30 % (todos editáveis)."],
          ["Método 2", "Food Cost %", "Você escolhe qual porcentagem do preço o custo dos ingredientes deve representar (o comum é 28 % a 35 %) e o preço é calculado a partir disso. É o padrão do setor."],
        ]],
        ["formula", "Preço de venda sugerido", ["6 itens: Preço = Custo unitário + (Soma dos itens ÷ Rendimento)", "Food Cost: Preço = Custo unitário ÷ % desejada"], "Nos dois casos o preço é arredondado <strong>para cima</strong> ao degrau da sua moeda: ao 5 em lempiras (61 vira 65, nunca 60), ao 0.50 em dólares ou euros (10.60 vira 11.00), ao 100 em colones. É o único arredondamento do cálculo. O exemplo abaixo está em lempiras."],
        ["example", "Exemplo · mesmo custo, dois métodos (custo unitário 20, rendimento 1)", [
          ["6 itens: 2 + 2 + 6 + 5 + 0 + 6", "21"],
          ["20 + 21 = 41 → arredondado", "45", true],
          ["Food Cost 30 %: 20 ÷ 0.30 = 66.67 → arredondado", "70", true],
        ]],
        ["p", "Se o seu negócio tem despesas fixas e uma estimativa de pratos por mês, a parte proporcional delas é somada ao preço automaticamente como mais um item:"],
        ["formula", "Custo fixo por prato", ["Custo fixo por prato = Despesas fixas do mês ÷ Pratos estimados por mês"]],
        ["h3", "Comissão de delivery ou cartão"],
        ["p", "Se você vende por um app de delivery ou recebe no cartão, informe na ficha o <strong>% de comissão</strong> que eles ficam do preço. O preço sugerido a cobre, e a ficha mostra a comissão por unidade e quanto sobra depois de pagá-la. O lucro e a margem já a descontam."],
        ["formula", "Preço com comissão", ["Preço = Preço sem comissão ÷ (1 − % de comissão)"], "Funciona com os dois métodos e é arredondado depois, como sempre."],
        ["example", "Exemplo · custo unitário 20, Food Cost 30 %, comissão 30 % (em lempiras)", [
          ["Preço sem comissão: 20 ÷ 0.30", "66.67"],
          ["66.67 ÷ (1 − 0.30) = 95.24 → arredondado", "100", true],
          ["O app fica com 30 %", "30"],
          ["Sobra para você por prato", "70", true],
        ]],
        ["figure", "04-ficha-tecnica-precio.jpg", "O cálculo do preço de venda com o método escolhido na receita, seguido do resumo de custos."],
        ["h3", "Margens e preço manual"],
        ["formula", "Indicadores da receita", ["Venda total = Preço final × Rendimento", "Margem de contribuição = (Venda total − Custo de produção) ÷ Venda total", "Custo % = Custo de produção ÷ Venda total"]],
        ["p", "O preço sugerido nunca é obrigatório: você pode digitar o seu próprio <strong>preço de venda</strong> ou o seu próprio <strong>lucro unitário</strong>. As margens são recalculadas com o seu número, mas o custo sempre reflete o que você realmente paga."],
        ["h3", "Escalar com o modificador de PAX"],
        ["p", "Informe para quantas pessoas quer servir e o app escala todas as quantidades e custos na hora, sempre arredondando <strong>para cima</strong> para você nunca ficar sem. É uma prévia: a receita salva não muda."],
        ["list", [
          "<strong>Exportar PDF</strong> ou <strong>Gerar Pedido de Compra</strong> com o PAX ativo usa as quantidades escaladas, sem salvar nada. O botão avisa «Escalado para N».",
          "<strong>Salvar</strong> com o PAX ativo pede confirmação: a receita fica no novo tamanho e o tamanho anterior é guardado como «original».",
          "<strong>Restaurar receita original</strong> volta a esse tamanho original. Depois aperte Salvar para confirmar.",
        ]],
        ["warn", "Rendimento suspeito", "Se algum ingrediente medido em «unidade» for 20 vezes o rendimento declarado ou mais (por exemplo, 200 ovos para um rendimento de 1), você verá um aviso amarelo na ficha e no PDF. Ele não bloqueia nada: só ajuda a pegar um erro de digitação."],
        ["h3", "Minhas Receitas: duplicar, mover e lixeira"],
        ["figure", "06-mis-recetas.jpg", "Minhas Receitas: todas as suas receitas com custo, rendimento e ações rápidas."],
        ["list", [
          "<strong>Duplicar</strong> cria uma cópia no mesmo negócio, com «(cópia)» no nome.",
          "<strong>Migrar</strong> copia a receita para outro dos seus negócios. Pergunta se leva também os ingredientes e sub-receitas (reaproveitando os que já existem lá) ou só a receita: nesse caso a ficha abre no negócio para você escolher os ingredientes da base dele (os que têm o mesmo nome são vinculados sozinhos).",
          "<strong>Excluir</strong> envia a receita para a <strong>lixeira</strong>, onde você pode recuperá-la por 30 dias antes de ela ser apagada sozinha.",
        ]],
      ],
    },
    {
      id: "subrecetas",
      title: "Sub-receitas",
      intro: "Um molho base, um fundo ou uma massa que você usa em muitos pratos. Você cria uma vez e usa como qualquer outro ingrediente.",
      blocks: [
        ["h3", "Criar uma sub-receita"],
        ["p", "Crie a receita normalmente e dê a ela a classificação <strong>«Sub-receita / produção (Mise en place)»</strong>. Ao salvar, a Gastrometrics cria um ingrediente com o mesmo nome, que você já pode buscar e adicionar em qualquer outra ficha técnica."],
        ["formula", "Custo de uso", ["Custo de uso = Custo total da sub-receita ÷ Rendimento"], "É quanto custa cada unidade da preparação (cada grama de molho, por exemplo) quando você a usa em outra receita."],
        ["h3", "O que muda em uma sub-receita"],
        ["p", "Como não é vendida sozinha, ela não tem preço de venda, itens de custo nem margens. O resumo mostra só três dados: <strong>custo de produção</strong>, <strong>rendimento</strong> e <strong>custo de uso</strong>."],
        ["h3", "Tudo se atualiza em cadeia"],
        ["p", "Se o preço de um ingrediente do seu molho base subir, o custo de uso é recalculado e a mudança chega automaticamente a cada prato que o usa. Você não precisa abrir nenhuma receita."],
        ["warn", "Cuidado com as quantidades", "O custo de uso costuma ser por grama ou mililitro. Se ao usá-la você digitar «150» pensando em unidades em vez de gramas, o custo do prato dispara. Confira a unidade antes de salvar."],
      ],
    },
    {
      id: "barra",
      title: "Bar e bebidas",
      intro: "Vinho, cerveja, drinks e bebidas sem álcool são custeados como a comida: são ingredientes e receitas com alguns ajustes de bar. Não há um módulo à parte para aprender.",
      blocks: [
        ["h3", "Bebidas como ingredientes"],
        ["p", "Cadastre cada garrafa, lata ou barril como um ingrediente, em mililitros ou litros, com seu preço e seu conteúdo. Há categorias próprias de bar, cada uma com sua perda típica (derramamentos, fundo da garrafa, espuma):"],
        ["table", ["Categoria", "Perda típica", "Servido em"], [
          ["Destilados", "2 %", "Dose 45 ml, dupla 90 ml, garrafa"],
          ["Vinhos", "5 %", "Taça 150 ou 125 ml, jarra 500 ml, garrafa"],
          ["Chope", "18 %", "Pint 473 ml, meio litro, copo 330 ml"],
          ["Cerveja engarrafada", "0 %", "Garrafa ou lata inteira"],
          ["Refrigerantes e mixers", "2 %", "Embalagem inteira ou copo 250 ml"],
        ]],
        ["h3", "Drinks na Ficha Técnica"],
        ["p", "Um coquetel é uma receita com as linhas em mililitros. Ao escolher uma classificação <strong>Bar · …</strong>, o preço passa a ser calculado com <strong>pour cost</strong>: a parte do preço que é custo do produto. Esse objetivo é só daquela receita: não muda o dos seus pratos."],
        ["table", ["Classificação", "Pour cost padrão", "Faixa típica"], [
          ["Bar · Coquetéis", "20 %", "15–22 %"],
          ["Bar · Vinhos", "30 %", "25–35 %"],
          ["Bar · Cervejas", "24 %", "20–28 %"],
          ["Bar · Sem álcool", "15 %", "10–20 %"],
          ["Bar · Café e chá", "20 %", "15–25 %"],
        ]],
        ["formula", "Preço de uma bebida", ["Preço = Custo por dose ÷ Pour cost alvo"], "É arredondado para cima ao degrau da sua moeda, como qualquer preço sugerido."],
        ["example", "Exemplo · gim-tônica (em dólares)", [
          ["Gim, 45 ml", "1.69"],
          ["Tônica, 150 ml", "0.55"],
          ["Limão", "0.10"],
          ["Custo do drink", "2.34", true],
          ["2.34 ÷ 0.22 = 10.64 → arredondado", "11.00", true],
        ]],
        ["h3", "Vender por taça ou garrafa"],
        ["steps", [
          "Em <strong>Ingredientes</strong>, encontre a bebida e toque no ícone de <strong>taça</strong> da linha.",
          "Escolha como é servida: uma medida (taça, dose, pint…), outra quantidade em mililitros ou a embalagem inteira.",
          "Confira o custo por dose, quantas doses saem de cada embalagem e o preço sugerido; você pode digitar seu próprio preço.",
          "Toque em <strong>Criar ficha</strong>: ela aparece em Minhas receitas e já pode ser usada em cardápios, vendas e estoque teórico.",
        ]],
        ["formula", "Custo por dose", ["Custo por dose = Mililitros servidos × Preço por mililitro", "Doses por embalagem = Conteúdo aproveitável ÷ Mililitros servidos"], "O preço por mililitro já inclui a perda do ingrediente. Vender a garrafa inteira custa exatamente o seu preço de compra."],
        ["example", "Exemplo · taça de vinho", [
          ["Garrafa de 750 ml", "20.00"],
          ["Com 5 % de perda sobram", "712.5 ml"],
          ["Preço por mililitro", "0.028"],
          ["Taça de 150 ml", "4.21", true],
          ["Taças por garrafa", "4.75"],
        ]],
        ["h3", "Contar o bar"],
        ["p", "Ao registrar o estoque por embalagem você pode usar decimais (2.3 garrafas). Na tabela de Estoque, as bebidas mostram saldo, mínimo e a diferença da última contagem também em garrafas."],
        ["formula", "Contar por peso", ["Fração da aberta = (Peso − Vazia) ÷ (Cheia − Vazia)", "Embalagens = Fechadas + Fração da aberta"], "Toque no ícone de <strong>balança</strong> ao contar. Você pesa uma única vez uma garrafa cheia fechada e uma vazia do mesmo produto; elas ficam salvas para as próximas contagens."],
        ["tip", "O que a contagem mostra", "Num bar, o custo real costuma ficar alguns pontos acima do teórico por derramamentos, doses generosas ou cortesias. A diferença da contagem, em garrafas, mostra onde olhar primeiro."],
        ["h3", "Cozinha e bar nos Relatórios"],
        ["p", "Em Relatórios → Finanças, o cartão <strong>Cozinha vs. bar</strong> mostra as vendas, a participação nas vendas e o custo teórico de cada área, e o custo real se você fez uma contagem inicial e uma final no período. O Menu Engineering tem um filtro Tudo / Cozinha / Bar para comparar drinks com drinks e pratos com pratos."],
        ["info", "Plano", "Receitas de bar e «Vender por taça»: todos os planos. Perda: a partir do <strong>Home Cook</strong>. Estoque: a partir do <strong>Chef de Partie</strong>. Cozinha vs. bar em Finanças: a partir do <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "inventario",
      title: "Estoque",
      plan: "Plano Chef de Partie ou superior",
      intro: "Saiba quanto você tem, o que está acabando e quanto vale o seu depósito. Cada contagem fica guardada como histórico.",
      blocks: [
        ["figure", "07-inventario.jpg", "Estoque: saldo atual, mínimos, situação de cada produto e valor total."],
        ["h3", "Situações: normal, baixo e crítico"],
        ["p", "Cada produto tem um <strong>mínimo</strong> definido por você, direto na tabela. Com ele, o app marca a situação:"],
        ["table", ["Situação", "Quando aparece"], [
          ["Crítico", "O saldo é igual ou menor que o mínimo."],
          ["Baixo", "O saldo é igual ou menor que o dobro do mínimo."],
          ["Normal", "O saldo está acima do dobro do mínimo, ou ainda não foi contado."],
        ]],
        ["h3", "Registrar estoque"],
        ["p", "«Registrar Estoque» guarda uma fotografia do saldo naquele momento e atualiza as quantidades atuais. Há três tipos:"],
        ["cards", [
          ["Contagem", "Estoque Inicial", "O que você tem ao começar um turno, uma semana ou um mês."],
          ["Contagem", "Estoque Final", "O que sobra ao fechar o período, para comparar com o inicial."],
          ["Entrada", "Nova Compra", "Mercadoria que acabou de chegar, com o preço que você pagou. Atualiza o custo das suas receitas se o preço mudou."],
        ]],
        ["p", "Você pode contar na unidade base (gramas, por exemplo) ou por embalagem (3 sacos), e o app faz a conversão. Por embalagem você pode usar decimais: 2.3 garrafas são 2 inteiras e 3 décimos da aberta. Sempre se conta o conteúdo real da embalagem, mesmo que o ingrediente tenha perda."],
        ["h3", "O valor do seu estoque"],
        ["formula", "Valor do estoque", ["Valor de um produto = Saldo × Preço da embalagem ÷ Conteúdo da embalagem", "Valor total = Soma de todos os produtos"], "O saldo é guardado na unidade do ingrediente (ml, g…) e o preço é o da garrafa, do saco ou da caixa inteira: por isso se divide pelo conteúdo. Três garrafas de 750 ml a 20 valem 60."],
        ["p", "A cada nova compra, o app também mantém um <strong>custo médio ponderado</strong> como referência de avaliação. O custeio das receitas sempre usa o preço da última compra."],
        ["tip", "Recálculo automático", "Se uma compra muda o preço de um ingrediente, todas as receitas e sub-receitas que o usam são recalculadas, e o app informa quantas foram."],
        ["h3", "Estoque teórico: quanto deveria sobrar"],
        ["p", "Além do estoque contado, cada produto mostra seu <strong>estoque teórico</strong>: o que deveria sobrar de acordo com as vendas registradas depois da última contagem (manuais, do PDV e faturas). A Gastrometrics desdobra cada venda pela receita —incluindo sub-receitas e perdas— e desconta sozinha. Editar ou excluir uma venda corrige o número na hora."],
        ["formula", "Estoque teórico", ["Estoque teórico = Última contagem + Compras recebidas − Consumo das vendas"], "Um prato vendido consome uma porção da receita; um cardápio vendido, uma porção de cada prato ativo."],
        ["p", "Ao fazer uma contagem nova, você verá a <strong>diferença na última contagem</strong>: o que você contou menos o que a teoria esperava. Se for negativa, saiu mais do que as receitas explicam (perdas, desperdício, porções maiores ou faltas): é o sinal para investigar."],
      ],
    },
    {
      id: "menus",
      title: "Cardápios",
      plan: "Plano Chef de Partie ou superior",
      intro: "Agrupe suas receitas em etapas de serviço para montar um cardápio, um prato do dia ou um evento, com preço médio e pedido de compra.",
      blocks: [
        ["figure", "08-menus.jpg", "Cardápios: cada cardápio com suas etapas, pratos ativos e preço médio."],
        ["h3", "Criar um cardápio em 4 etapas"],
        ["steps", [
          "<strong>Dados</strong>: nome, tipo (almoço, jantar, brunch, bufê, degustação, catering, evento especial ou outro), data e número de pessoas.",
          "<strong>Etapas</strong>: Entrada, Prato principal e Sobremesa por padrão. Você pode renomear, remover ou adicionar mais.",
          "<strong>Pratos</strong>: o app sugere primeiro as receitas cuja «Etapa» coincide com cada uma.",
          "<strong>Revisão</strong>: o resumo completo, com a opção de indicar quantas porções de cada prato você precisa para aquele serviço.",
        ]],
        ["tip", "Carta de bebidas", "Escolha o tipo <strong>Carta de bebidas</strong> e as etapas mudam para Coquetéis, Vinhos, Cervejas e Bebidas sem álcool. Cada uma sugere as receitas com a classificação de bar correspondente (capítulo 6)."],
        ["p", "Cada prato pode ter um preço próprio (se não, usa o da ficha técnica) e pode ser desativado temporariamente sem sair do cardápio."],
        ["formula", "Preço médio do cardápio", ["Preço médio = Soma dos preços dos pratos ativos ÷ Número de pratos ativos"], "Pratos desativados não contam."],
        ["h3", "Exportar e comprar"],
        ["p", "Em cada cardápio você pode exportar o PDF para seus clientes ou a versão interna com custos (capítulo 12), ou gerar direto o pedido de compra com tudo o que é preciso para produzi-lo."],
      ],
    },
    {
      id: "compras",
      title: "Pedidos de Compra",
      intro: "Diga a cada fornecedor exatamente o que e quanto você precisa: manualmente, a partir de um cardápio ou de uma receita, ou deixando o app sugerir olhando o seu estoque.",
      blocks: [
        ["figure", "09-ordenes-compra.jpg", "Pedidos de Compra: a sugestão automática por estoque baixo e a lista de pedidos com sua situação."],
        ["h3", "Quatro formas de criar um pedido"],
        ["list", [
          "<strong>Manual</strong>: você busca cada ingrediente e o app completa unidade, fornecedor e preço.",
          "<strong>Sugerido por estoque baixo</strong>: verifica o seu estoque e monta o pedido com tudo o que está baixo ou crítico.",
          "<strong>A partir de um cardápio</strong>: tudo o que é preciso para produzi-lo, descontando o que você já tem.",
          "<strong>A partir de uma receita</strong>: o botão «Gerar Pedido de Compra» da Ficha Técnica, já escalado se você usar o modificador de PAX.",
        ]],
        ["formula", "Quantidade sugerida por estoque baixo", ["Quantidade a pedir = O maior entre (2 × Mínimo − Saldo atual) e o Mínimo"], "Repõe até o dobro do seu mínimo para dar folga, e nunca sugere menos que o próprio mínimo."],
        ["formula", "Total do pedido", ["Custo da linha = Quantidade × Preço por unidade", "Total = Soma das linhas + Imposto"], "O imposto é 0 % por padrão e pode ser alterado. Se o ingrediente tem embalagem, o pedido também diz quantas comprar, arredondando para cima."],
        ["h3", "Situações e recebimento"],
        ["chips", ["Pendente", "Aprovado", "Encomendado", "Recebido", "Cancelado"]],
        ["p", "Você pode mudar a situação livremente. Os itens são agrupados por fornecedor (os sem fornecedor ficam no fim), para você ligar para cada um com a lista completa. Também dá para duplicar ou editar um pedido."],
        ["tip", "«Recebido» soma ao seu estoque", "Ao marcar um pedido como recebido, as quantidades são somadas sozinhas ao saldo dos produtos do estoque com o mesmo nome. Se chegou algo diferente do pedido, corrija registrando o real em <strong>Estoque → Nova Compra</strong>."],
        ["info", "Plano", "Pedidos manuais estão disponíveis a partir do <strong>Home Cook</strong>; a sugestão automática, a partir do <strong>Chef de Partie</strong>."],
      ],
    },
    {
      id: "ventas",
      title: "Vendas e faturas",
      intro: "Registre o que você vende para comparar seus preços com a realidade: manualmente, importando o seu sistema de ponto de venda (PDV) ou emitindo faturas para seus clientes.",
      blocks: [
        ["figure", "10-ventas.jpg", "Vendas: importação do PDV e registro manual em um só lugar."],
        ["h3", "Registrar vendas"],
        ["list", [
          "<strong>Registro manual</strong>: ideal se você não tem PDV. Escolha uma receita ou um cardápio e a quantidade vendida; o app calcula a receita e o custo.",
          "<strong>Importar seu PDV</strong>: envie um arquivo .xlsx, .xls, .csv ou .txt. Você indica uma vez qual coluna é o prato, a quantidade, a data e o preço, e salva como um modelo com nome. Na próxima vez, o app o reconhece sozinho.",
        ]],
        ["tip", "Arquivos difíceis", "O app detecta se as datas vêm como dia/mês ou mês/dia (e deixa você corrigir), e lê corretamente os acentos de arquivos antigos em formatos do Windows."],
        ["h3", "Faturas para seus clientes"],
        ["p", "Na aba <strong>Faturas</strong> você cria a fatura que entrega ao seu cliente: escolha receitas ou cardápios (ou digite linhas à mão), com numeração automática, imposto editável, observações e o logo do seu negócio no PDF. Cada fatura conta automaticamente como uma venda nos seus relatórios (sem o imposto)."],
        ["warn", "Não é uma nota fiscal oficial", "A fatura da Gastrometrics não inclui numeração autorizada por nenhuma autoridade fiscal. Verifique as exigências do seu país antes de usá-la como documento fiscal."],
        ["h3", "Histórico de vendas"],
        ["p", "No fim da página, o histórico reúne todas as suas vendas (manuais, do PDV e faturas), agrupadas por dia, semana, mês ou ano, no período que você escolher, com um botão para exportar em PDF."],
        ["info", "Plano", "Faturas: a partir do <strong>Home Cook</strong>. Registro manual: a partir do <strong>Chef de Partie</strong>. Importar o PDV: a partir do <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "reportes",
      title: "Relatórios",
      intro: "Aqui você vê o que seus números significam: quais receitas rendem mais, quanto vale o seu estoque e como o seu negócio vai de verdade.",
      blocks: [
        ["figure", "11-reportes.jpg", "Relatórios: panorama geral do negócio com indicadores e gráficos."],
        ["h3", "Panorama"],
        ["p", "Contagens gerais, valor do estoque e produtos em alerta, custo e margem médios, receitas por classificação, ingredientes mais usados, as receitas com melhor e pior margem, e o histórico de preço de cada ingrediente com sua variação."],
        ["h3", "Finanças"],
        ["p", "Se você vende bebidas, o cartão <strong>Cozinha vs. bar</strong> separa vendas, custo teórico e custo real de cada área (capítulo 6). Demonstrativo de resultados (DRE), comparação entre seu food cost teórico e o real segundo as vendas, variação de preços por fornecedor e análise de <strong>Menu Engineering</strong>, que classifica cada prato comparando-o com a média do seu próprio cardápio:"],
        ["table", ["Categoria", "Popularidade", "Margem", "O que fazer"], [
          ["Estrela", "Alta", "Alta", "Proteja e destaque no cardápio."],
          ["Vaca leiteira", "Alta", "Baixa", "Vende bem: revise o custo ou aumente um pouco o preço."],
          ["Quebra-cabeça", "Baixa", "Alta", "Boa margem: promova ou melhore a apresentação."],
          ["Cachorro", "Baixa", "Baixa", "Considere reformular ou tirar do cardápio."],
        ]],
        ["formula", "Custo da mercadoria vendida (CMV)", ["CMV = Estoque inicial + Compras − Estoque final"], "Para um cálculo exato, você precisa de uma contagem inicial e uma final no período."],
        ["info", "Plano", "Panorama: a partir do <strong>Chef de Partie</strong>. Finanças: a partir do <strong>Sous Chef</strong>."],
      ],
    },
    {
      id: "pdfs",
      title: "Documentos PDF",
      intro: "Cada documento é pensado para quem vai lê-lo: sua cozinha, sua gerência, seu fornecedor ou seu cliente. Custos nunca se misturam com documentos para terceiros.",
      blocks: [
        ["h3", "Os 8 documentos"],
        ["table", ["Documento", "Para quem", "O que inclui"], [
          ["Ficha técnica · Administrativa", "Dono e gerência", "Ingredientes com custos, itens, gráficos, margem e food cost."],
          ["Ficha técnica · De cozinha", "Sua equipe de cozinha", "Ingredientes, quantidades, foto e modo de preparo, sem nenhum valor em dinheiro."],
          ["Ficha técnica · Rápida", "Fornecedores ou sócios", "O essencial da receita, sem custos nem preços."],
          ["Estoque", "Administração", "Valor total, valor por categoria, principais produtos e situações."],
          ["Cardápio · Cliente", "Seus clientes", "Um cardápio elegante, sem números de custo."],
          ["Cardápio · Interno", "Dono", "Custo, preço e margem por prato, com gráficos."],
          ["Pedido de compra", "Fornecedores", "Ingredientes por fornecedor, quantidades e total."],
          ["Fatura", "Seu cliente", "Seu logo, dados do cliente, linhas, imposto e total."],
        ]],
        ["p", "As fichas técnicas e o cardápio do cliente incluem os alergênicos de cada prato, calculados a partir dos ingredientes no momento da exportação (capítulo 3)."],
        ["tip", "Avisos automáticos", "A ficha administrativa avisa no topo se o custo passar do preço de venda ou se o rendimento parecer digitado errado, antes que você imprima um número estranho."],
        ["p", "Os PDFs saem no idioma selecionado no app, usam a sua moeda e trazem o logo e a cor de tema do seu negócio."],
        ["info", "Plano", "A ficha de cozinha está incluída em todos os planos. A ficha administrativa, a partir do <strong>Home Cook</strong>."],
      ],
    },
    {
      id: "equipo",
      title: "Equipe",
      plan: "Plano Sous Chef ou superior",
      intro: "Convide sua equipe para trabalhar com você na Gastrometrics, cada pessoa com acesso só ao que precisa.",
      blocks: [
        ["h3", "Convidar alguém"],
        ["p", "Em <strong>Equipe</strong> você digita o e-mail da pessoa. Ela recebe um convite e cria a própria conta; a sua assinatura cobre o acesso dela. Com o Sous Chef você pode adicionar 1 pessoa e com o Chef Ejecutivo até 4 (os usuários de cada plano incluem você). Não há funções fixas: para cada pessoa você configura três coisas separadamente."],
        ["table", ["Ajuste", "Opções"], [
          ["Alcance", "Todos os seus negócios, ou apenas um em particular."],
          ["Ferramentas", "Caixas independentes: receitas, ingredientes, perdas, pedidos manuais e automáticos, estoque, cardápios, relatórios, vendas, finanças e administrar a equipe."],
          ["PDF", "Nenhum, de cozinha (sem custos) ou administrativo (com custos)."],
        ]],
        ["tip", "Pré-visualização", "Ative a pré-visualização para ver o app exatamente como aquela pessoa veria, com as mesmas permissões."],
        ["p", "As permissões são aplicadas de verdade, não só na tela: quem não tem acesso a uma ferramenta não consegue ver nem salvar esses dados. Se algo estiver bloqueado, o app explica se é pelo plano da conta ou porque o dono restringiu."],
      ],
    },
    {
      id: "planes",
      title: "Planos e assinatura",
      intro: "Você começa grátis e muda de plano quando precisar. Seus dados nunca se perdem ao trocar de plano.",
      blocks: [
        ["table", ["Plano", "Preço", "Negócios", "Usuários (com você)", "Adiciona"], [
          ["Foodie", "Grátis", "1", "1", "Receitas, ingredientes e ficha de cozinha em PDF (incluídos em todos os planos)."],
          ["Home Cook", "$15 / mês", "1", "1", "Perdas, pedidos de compra manuais, ficha administrativa e faturas."],
          ["Chef de Partie", "$35 / mês", "1", "1", "Estoque, cardápios, pedidos sugeridos, Relatórios · Panorama e registro manual de vendas."],
          ["Sous Chef", "$70 / mês", "2", "2", "Relatórios · Finanças, DRE, Menu Engineering, importação do PDV e Equipe (você + 1 pessoa)."],
          ["Chef Ejecutivo", "$120 / mês", "5", "5", "Equipe de até 4 pessoas além de você. Disponível para empresas, sob consulta."],
        ]],
        ["figure", "12-mi-plan.jpg", "Meu Plano: seu plano atual, o que ele inclui e como gerenciar sua assinatura."],
        ["h3", "Pagar, mudar ou cancelar"],
        ["p", "Os pagamentos são processados pelo Stripe. Em <strong>Meu Plano</strong> você pode mudar de plano ou abrir o portal de pagamentos para atualizar o cartão ou cancelar. As mudanças aparecem sozinhas na sua conta e você recebe um e-mail de confirmação."],
        ["p", "Sempre que seu plano muda —porque você mudou, porque a equipe da Gastrometrics ajustou ou porque um plano atribuído venceu— avisamos por e-mail e com uma janela ao abrir o Dashboard, com a lista exata do que você <strong>ganha</strong>, do que <strong>perde</strong> e do que seu plano inclui agora. Se perder acesso a uma seção, seus dados não são apagados: voltam a ficar disponíveis se você subir de plano de novo."],
        ["p", "Se cancelar, você mantém o acesso completo até o fim do período já pago. O Meu Plano mostra a data exata."],
        ["info", "Quando algo está bloqueado", "Você verá um cadeado e um botão para o Meu Plano. Se usa o app como parte de uma equipe, a mensagem indica que é o dono da conta quem controla esse acesso."],
      ],
    },
    {
      id: "config",
      title: "Configurações, idioma e e-mails",
      intro: "Ajuste o app do seu jeito, escolha idioma e moeda, decida quais e-mails receber e gerencie os dados da sua conta.",
      blocks: [
        ["figure", "13-configuracion.jpg", "Configurações → Notificações, onde você decide se quer receber novidades e lembretes."],
        ["h3", "As abas de Configurações"],
        ["list", [
          "<strong>Perfil</strong>: nome, e-mail (mudar pede sua senha atual), país e tipo de negócio.",
          "<strong>Aparência</strong>: modo claro, escuro ou conforme o seu sistema.",
          "<strong>Regional</strong>: país, moeda e idioma.",
          "<strong>Notificações</strong>: se você quer receber novidades e lembretes por e-mail.",
          "<strong>Conta</strong>: backup dos seus dados, documentos legais, apagar conteúdo e excluir a conta.",
        ]],
        ["h3", "Idioma e moeda"],
        ["p", "O app está em <strong>espanhol, inglês, dinamarquês, francês, português e chinês</strong>. O idioma escolhido é usado em toda a interface, nos seus PDFs e em <strong>todos os e-mails</strong> que enviamos. Há 21 moedas disponíveis; mudar de moeda muda o símbolo e o formato, não converte seus valores. Os decimais sempre são escritos com ponto."],
        ["h3", "E-mails que você pode receber"],
        ["p", "Você sempre recebe os e-mails da sua conta: confirmação, senha, pagamentos e convites de equipe. Se ativar <strong>Novidades e lembretes</strong>, também escrevemos quando há funções novas e, se você passar alguns dias sem entrar, um lembrete útil de acordo com o que você fez por último:"],
        ["cards", [
          ["Lembrete", "Receita não finalizada", "Seu rascunho da Ficha Técnica espera por você antes de completar 24 horas."],
          ["Lembrete", "Estoque e relatórios", "Quando passa uma semana desde a sua última contagem ou desde que você viu seus relatórios."],
          ["Lembrete", "Preços e retorno", "Se seus preços estão há mais de 30 dias sem atualizar, ou se faz tempo que você não entra."],
        ]],
        ["p", "E quando sua conta tem algo concreto para contar, escrevemos com o dado:"],
        ["cards", [
          ["Toda segunda", "Resumo semanal", "Seus números principais: food cost médio, valor do estoque, produtos abaixo do mínimo e pratos com margem baixa."],
          ["Alerta", "Estoque baixo e margem", "Se um produto chega ao mínimo ou um prato deixa de cumprir sua meta de food cost."],
          ["Equipe", "Convites e negócios", "Se seu convidado não entrou, ou se um negócio novo continua sem receitas."],
          ["Conquistas", "Avanços e seu plano", "Quando você chega a 10, 25 ou 50 receitas, e se seu plano inclui algo que você ainda não experimentou."],
        ]],
        ["p", "Nunca enviamos mais de um lembrete a cada poucos dias. Cada e-mail traz um link para cancelar a inscrição com um clique, ou você pode desmarcar a caixa em Configurações → Notificações."],
        ["h3", "Seus dados"],
        ["list", [
          "<strong>Baixar backup</strong>: um único arquivo com todo o seu conteúdo (receitas, ingredientes, cardápios e mais).",
          "<strong>Apagar todo o conteúdo</strong>: esvazia sua conta, mas a mantém ativa. Pede que você digite seu e-mail para confirmar.",
          "<strong>Excluir a conta</strong>: cancela sua assinatura e apaga tudo permanentemente. Também pede seu e-mail para confirmar.",
        ]],
        ["warn", "Sem volta", "Apagar o conteúdo ou excluir a conta não pode ser desfeito. Baixe seu backup antes."],
      ],
    },
    {
      id: "formulas",
      appendix: "A",
      title: "Fórmulas em resumo",
      intro: "Todas as fórmulas do manual em uma só página, para consulta rápida.",
      blocks: [
        ["table", ["Conceito", "Como é calculado"], [
          ["Preço por unidade", "Preço de compra ÷ Conteúdo líquido"],
          ["Com perdas", "Preço de compra ÷ (Conteúdo líquido × (1 − % de perda))"],
          ["Custo de uma linha", "Quantidade × Preço por unidade"],
          ["Custo de produção", "Soma das linhas (× multiplicador de PAX se estiver ativo)"],
          ["Custo unitário", "Custo de produção ÷ Rendimento"],
          ["Preço · 6 itens", "Custo unitário + Soma dos itens ÷ Rendimento, arredondado para cima ao degrau da sua moeda"],
          ["Preço · Food Cost %", "Custo unitário ÷ % desejada, arredondado para cima ao degrau da sua moeda"],
          ["Preço com comissão", "Preço sem comissão ÷ (1 − % de comissão)"],
          ["Custo fixo por prato", "Despesas fixas do mês ÷ Pratos estimados por mês"],
          ["Venda total", "Preço final × Rendimento"],
          ["Margem de contribuição", "(Venda total − Custo de produção) ÷ Venda total"],
          ["Custo %", "Custo de produção ÷ Venda total"],
          ["Custo de uso (sub-receita)", "Custo total ÷ Rendimento"],
          ["Situação do estoque", "Crítico se saldo ≤ mínimo · Baixo se saldo ≤ 2 × mínimo"],
          ["Valor do estoque", "Soma de (Saldo × Preço da embalagem ÷ Conteúdo da embalagem)"],
          ["Estoque teórico", "Última contagem + Compras recebidas − Consumo das vendas"],
          ["Preço de uma bebida", "Custo por dose ÷ Pour cost alvo"],
          ["Custo por dose", "Mililitros servidos × Preço por mililitro (com perda)"],
          ["Doses por embalagem", "Conteúdo aproveitável ÷ Mililitros servidos"],
          ["Contar por peso", "Fechadas + (Peso − Vazia) ÷ (Cheia − Vazia)"],
          ["Quantidade sugerida", "O maior entre (2 × Mínimo − Saldo) e o Mínimo"],
          ["Total do pedido", "Soma das linhas + Imposto"],
          ["Preço médio do cardápio", "Soma dos pratos ativos ÷ Número de pratos ativos"],
          ["CMV", "Estoque inicial + Compras − Estoque final"],
        ]],
      ],
    },
    {
      id: "problemas",
      appendix: "B",
      title: "Perguntas frequentes",
      intro: "As situações mais comuns de «isso não faz o que eu esperava», com causa e solução.",
      blocks: [
        ["table", ["Se acontecer isto…", "O que verificar"], [
          ["O custo de uma receita sai altíssimo ou absurdo.", "Confira o rendimento e a unidade de cada ingrediente. Se usa sub-receitas, confirme que a quantidade está em gramas ou mililitros, e não em unidades."],
          ["Mudei um preço e minhas receitas não mudaram.", "O recálculo é imediato. Confirme que a receita usa exatamente esse ingrediente e não um duplicado com nome parecido."],
          ["Não vejo um módulo (Estoque, Finanças, Equipe…).", "Seu plano não o inclui, ou o dono da conta não deu acesso a você. A mensagem na tela diz qual dos dois."],
          ["Marquei um pedido como «Recebido» e um produto não foi somado.", "Só são somados os produtos cujo nome coincide exatamente com um do estoque. Registre esse produto em Estoque → Nova Compra."],
          ["Salvei uma receita com o PAX ativo sem querer.", "Use «Restaurar receita original» e salve de novo."],
          ["Saí da Ficha Técnica sem salvar.", "Volte à Ficha Técnica em até 24 horas: sua receita é recuperada sozinha."],
          ["Meus e-mails chegam em outro idioma.", "Mude o idioma em Configurações → Regional estando dentro da sua conta; os próximos e-mails chegarão nesse idioma."],
          ["Não quero receber lembretes.", "Use o link «Parar de receber estes e-mails» ou desmarque a caixa em Configurações → Notificações."],
          ["Meu drink sai com um preço altíssimo.", "Confira se a classificação é de «Bar»: assim o preço usa pour cost em vez dos 6 itens de um prato."],
        ]],
        ["p", "Tem outra dúvida ou uma sugestão? Escreva para nós em <strong>Sugestões e relatórios</strong>, na parte inferior de Configurações. Lemos cada mensagem."],
      ],
    },
  ],
}
